package com.ryanjei.orushio.pve.paper;

import static org.junit.jupiter.api.Assertions.*;
import com.ryanjei.orushio.pve.application.GameThreadExecutor;
import com.ryanjei.orushio.pve.domain.*;
import com.ryanjei.orushio.pve.interference.*;
import com.ryanjei.orushio.pve.map.Cuboid;
import java.time.*;import java.util.*;import org.junit.jupiter.api.*;

class PaperInterferenceGatewayTest {
    UUID sessionId=UUID.randomUUID(),alice=UUID.randomUUID(),offline=UUID.randomUUID(),otherWorld=UUID.randomUUID(),outside=UUID.randomUUID(),stranger=UUID.randomUUID();GameSession active;Map<UUID,FakeTarget>players;PaperInterferenceGateway gateway;
    @BeforeEach void setup(){Instant now=Instant.now();active=new GameSession(sessionId,GameState.ACTIVE,List.of(new Participant(alice,"A",true),new Participant(offline,"O",false),new Participant(otherWorld,"W",true),new Participant(outside,"X",true)),now,"map-a",4,60,2,1,now,now.plusSeconds(60),Set.of());players=new HashMap<>();players.put(alice,new FakeTarget(true,"runtime",5,65,5));players.put(offline,new FakeTarget(false,"runtime",5,65,5));players.put(otherWorld,new FakeTarget(true,"lobby",5,65,5));players.put(outside,new FakeTarget(true,"runtime",50,65,50));players.put(stranger,new FakeTarget(true,"runtime",5,65,5));gateway=new PaperInterferenceGateway(new ImmediateThread(),()->active,bound->0,players::get);}
    @Test void DarknessとLevitationはCurrentParticipantかつonline_Runtime_FinalRegion内だけへ付与する(){Cuboid region=new Cuboid(0,60,0,10,80,10);var darkness=gateway.apply(sessionId,"runtime",region,List.of(alice,offline,otherWorld,outside,stranger),InterferenceType.DARKNESS,InterferenceSettings.defaults());assertEquals(1,darkness.affectedPlayerCount());assertEquals(4,darkness.skippedPlayerCount());assertEquals(new PaperInterferenceGateway.EffectState(100,0),players.get(alice).effects.get(InterferenceType.DARKNESS));assertNull(players.get(offline).effects.get(InterferenceType.DARKNESS));var levitation=gateway.apply(sessionId,"runtime",region,List.of(alice),InterferenceType.LEVITATION,InterferenceSettings.defaults());assertEquals(1,levitation.affectedPlayerCount());assertEquals(new PaperInterferenceGateway.EffectState(40,0),players.get(alice).effects.get(InterferenceType.LEVITATION));}
    @Test void Darknessは既存Effectを短縮または弱体化しない(){assertPotionProtection(InterferenceType.DARKNESS,100);}
    @Test void Levitationは既存Effectを短縮または弱体化しない(){assertPotionProtection(InterferenceType.LEVITATION,40);}
    @Test void Hotbarだけを9要素permutationしItem内容と空slotを維持する(){FakeTarget player=players.get(alice);Object a=new Object(),b=new Object(),c=new Object(),offhand=new Object(),armor=new Object(),main9=new Object();player.items=new Object[]{a,null,b,null,null,c,null,null,null};player.offhand=offhand;player.armor=armor;player.main9=main9;gateway.apply(sessionId,"runtime",new Cuboid(0,60,0,10,80,10),List.of(alice),InterferenceType.HOTBAR_SHUFFLE,InterferenceSettings.defaults());assertEquals(6,Arrays.stream(player.items).filter(Objects::isNull).count());assertEquals(1,Arrays.stream(player.items).filter(value->value==a).count());assertEquals(1,Arrays.stream(player.items).filter(value->value==b).count());assertEquals(1,Arrays.stream(player.items).filter(value->value==c).count());assertSame(offhand,player.offhand);assertSame(armor,player.armor);assertSame(main9,player.main9);}
    @Test void 別SessionをPaper操作直前に拒否する(){assertThrows(IllegalStateException.class,()->gateway.apply(UUID.randomUUID(),"runtime",new Cuboid(0,0,0,10,100,10),List.of(alice),InterferenceType.DARKNESS,InterferenceSettings.defaults()));}
    @Test void 不正Random値を拒否する(){assertThrows(IllegalStateException.class,()->PaperInterferenceGateway.permute(new Object[]{1,2},bound->bound));}
    private void assertPotionProtection(InterferenceType type,int configuredTicks){FakeTarget player=players.get(alice);Cuboid region=new Cuboid(0,60,0,10,80,10);player.effects.remove(type);gateway.apply(sessionId,"runtime",region,List.of(alice),type,InterferenceSettings.defaults());assertEquals(new PaperInterferenceGateway.EffectState(configuredTicks,0),player.effects.get(type));player.effects.put(type,new PaperInterferenceGateway.EffectState(configuredTicks/2,0));gateway.apply(sessionId,"runtime",region,List.of(alice),type,InterferenceSettings.defaults());assertEquals(new PaperInterferenceGateway.EffectState(configuredTicks,0),player.effects.get(type));player.effects.put(type,new PaperInterferenceGateway.EffectState(configuredTicks*2,0));gateway.apply(sessionId,"runtime",region,List.of(alice),type,InterferenceSettings.defaults());assertEquals(new PaperInterferenceGateway.EffectState(configuredTicks*2,0),player.effects.get(type));player.effects.put(type,new PaperInterferenceGateway.EffectState(configuredTicks,2));gateway.apply(sessionId,"runtime",region,List.of(alice),type,InterferenceSettings.defaults());assertEquals(new PaperInterferenceGateway.EffectState(configuredTicks,2),player.effects.get(type));}
    private static final class ImmediateThread implements GameThreadExecutor{public<T>T execute(java.util.concurrent.Callable<T>task,Duration timeout)throws Exception{return task.call();}public boolean isAcceptingTasks(){return true;}}
    private static final class FakeTarget implements PaperInterferenceGateway.Target{boolean online;String world;int x,y,z;Map<InterferenceType,PaperInterferenceGateway.EffectState>effects=new EnumMap<>(InterferenceType.class);Object[]items=new Object[9];Object offhand,armor,main9;FakeTarget(boolean online,String world,int x,int y,int z){this.online=online;this.world=world;this.x=x;this.y=y;this.z=z;}public boolean online(){return online;}public String worldName(){return world;}public int blockX(){return x;}public int blockY(){return y;}public int blockZ(){return z;}public PaperInterferenceGateway.EffectState potionEffect(InterferenceType type){return effects.get(type);}public void potionEffect(InterferenceType type,int ticks,int amplifier){effects.put(type,new PaperInterferenceGateway.EffectState(ticks,amplifier));}public Object[]hotbar(){return items.clone();}public void hotbar(Object[]items){this.items=items.clone();}}
}
