let csrf = '', current = null, loading = false, onlinePlayers = [];
const $ = id => document.getElementById(id);
const escapeHtml = value => { const node = document.createElement('div'); node.textContent = String(value); return node.innerHTML; };
async function api(path, options = {}) { options.headers = { 'Content-Type': 'application/json', ...(options.headers || {}), 'X-CSRF-Token': csrf }; const response = await fetch('/api/v1' + path, options); const json = await response.json(); if (!response.ok) { const error = new Error(json.error?.message || '操作に失敗しました'); error.traceId = json.error?.traceId; throw error; } return json.data; }
function notify(message, type = 'info', traceId = '') { $('notice').className = type; $('notice').textContent = traceId ? `${message}（追跡ID: ${traceId}）` : message; }
function setLoading(value) { loading = value; document.body.classList.toggle('loading', value); for (const element of document.querySelectorAll('button:not(nav button), input')) { if (value && !element.disabled) { element.disabled = true; element.dataset.loadingDisabled = 'true'; } if (!value && element.dataset.loadingDisabled) { element.disabled = false; delete element.dataset.loadingDisabled; } } }
function show(page) { for (const id of ['home', 'game', 'maps-page', 'system']) $(id).hidden = true; $(page).hidden = false; $('title').textContent = { home: 'ホーム', game: 'ゲーム操作', 'maps-page': 'マップ管理', system: 'システム' }[page]; if (page === 'system') loadDiagnostics(); if(page === 'maps-page') loadMaps(); }
document.querySelectorAll('[data-page]').forEach(button => button.addEventListener('click', () => show(button.dataset.page)));
function renderStatus(status) { current = status; $('paper').textContent = status.paperRunning ? '稼働中' : '停止'; $('state').textContent = status.gameState; $('participants').textContent = `${status.participantCount} / ${status.participantLimit}`; $('warnings').innerHTML = (status.warnings || []).map(value => `<li>${escapeHtml(value)}</li>`).join('') || '<li class="empty">警告はありません</li>'; }
function renderPlayers(playerResult) { onlinePlayers=playerResult.players; $('players').innerHTML = playerResult.players.map(player => `<li><span>${escapeHtml(player.name)}<small>${player.setupAdministrator ? player.administratorRevocable ? '管理者利用可能 / Orushioから解除可能' : '既存OP / Orushioからは解除不可' : '管理者権限なし'}</small></span><span class="actions inline"><button class="secondary" data-copy-name="${escapeHtml(player.name)}">名前をコピー</button>${player.setupAdministrator ? player.administratorRevocable ? `<button class="danger" data-revoke-administrator="${escapeHtml(player.uuid)}">管理者を解除</button>` : `<button data-adopt-administrator="${escapeHtml(player.uuid)}">Orushio管理として引き継ぐ</button>` : `<button data-setup-administrator="${escapeHtml(player.uuid)}">セットアップ管理者にする</button>`}</span></li>`).join('') || '<li class="empty">現在オンラインのプレイヤーはいません</li>'; $('online-count').textContent = `${playerResult.players.length}人がオンライン`; const administrators=playerResult.players.filter(player=>player.setupAdministrator); $('setup-admin').innerHTML=administrators.map(player=>`<option value="${escapeHtml(player.uuid)}">${escapeHtml(player.name)}（管理者利用可能）</option>`).join('')||'<option value="">オンラインのセットアップ管理者がいません</option>'; }

async function refresh(options = { notifyResult: true, silent: false }) {
  if (loading) return { complete: false, failures: [new Error('更新処理中です')] };
  if (!options.silent) setLoading(true); const failures = []; let statusAvailable = false, whitelistAvailable = false;
  try {
    if (!csrf) csrf = (await api('/auth/session')).csrfToken;
    const [statusResult, playersResult, whitelistResult] = await Promise.allSettled([api('/status'), api('/players'), api('/server/whitelist')]);
    if (statusResult.status === 'fulfilled') { renderStatus(statusResult.value); statusAvailable = true; }
    else { current = null; failures.push(statusResult.reason); $('paper').textContent = '取得失敗'; $('state').textContent = '—'; $('participants').textContent = '—'; $('warnings').innerHTML = '<li class="empty">サーバー状態を取得できませんでした</li>'; }
    if (playersResult.status === 'fulfilled') renderPlayers(playersResult.value);
    else { failures.push(playersResult.reason); $('players').innerHTML = '<li class="empty">オンラインプレイヤーを取得できませんでした</li>'; $('online-count').textContent = '取得失敗'; }
    if (whitelistResult.status === 'fulfilled') { renderWhitelist(whitelistResult.value); whitelistAvailable = true; }
    else { failures.push(whitelistResult.reason); $('whitelist-status').textContent = '取得失敗'; $('whitelist-players').innerHTML = '<li class="empty">ホワイトリスト情報を取得できませんでした</li>'; }
  } catch (error) { failures.push(error); }
  finally { if (!options.silent) setLoading(false); $('whitelist-toggle').disabled = !whitelistAvailable; $('player-name').disabled = !whitelistAvailable; $('whitelist-form').querySelector('button').disabled = !whitelistAvailable; $('start').disabled = !statusAvailable || current.gameState !== 'IDLE' || current.diagnosticMode; $('close').disabled = !statusAvailable || current.gameState !== 'RECRUITING' || current.diagnosticMode; }
  if (options.notifyResult) { if (failures.length) notify('一部の最新情報を取得できませんでした', 'error', failures[0].traceId); else notify(current.diagnosticMode ? '診断モードで動作しています' : '最新の状態です', current.diagnosticMode ? 'error' : 'success'); }
  return { complete: failures.length === 0, failures };
}

function renderWhitelist(whitelist) { $('whitelist-toggle').checked = whitelist.enabled; $('whitelist-toggle').nextElementSibling.textContent = whitelist.enabled ? 'ON' : 'OFF'; $('whitelist-status').textContent = whitelist.enabled ? 'ON' : 'OFF'; $('whitelist-players').innerHTML = whitelist.players.map(player => `<li><span>${escapeHtml(player.name)}</span><button class="danger" data-remove="${escapeHtml(player.name)}">削除</button></li>`).join('') || '<li class="empty">登録されているプレイヤーはいません</li>'; }
async function mutate(path, method, body, successMessage, headers = {}) { setLoading(true); try { await api(path, { method, headers, body: JSON.stringify(body) }); } catch (error) { setLoading(false); await refresh({ notifyResult: false }); notify(error.message, 'error', error.traceId); return; } setLoading(false); const refreshed = await refresh({ notifyResult: false }); if (refreshed.complete) notify(successMessage, 'success'); else notify(`${successMessage}。ただし、最新状態を確認できていません`, 'warning', refreshed.failures[0]?.traceId); }
$('refresh').onclick = () => refresh();
$('whitelist-toggle').onchange = event => mutate('/server/whitelist', 'PUT', { enabled: event.target.checked }, `ホワイトリストを${event.target.checked ? 'ON' : 'OFF'}にしました`);
$('whitelist-form').onsubmit = event => { event.preventDefault(); const name = $('player-name').value.trim(); mutate('/server/whitelist/players', 'POST', { name }, `${name}を追加しました`); $('player-name').value = ''; };
$('whitelist-players').onclick = event => { const name = event.target.dataset.remove; if (name && confirm(`${name}をホワイトリストから削除しますか？`)) mutate('/server/whitelist/players', 'DELETE', { name }, `${name}を削除しました`); };
$('players').onclick = async event => { const uuid = event.target.dataset.setupAdministrator, revoke = event.target.dataset.revokeAdministrator, adopt=event.target.dataset.adoptAdministrator, name=event.target.dataset.copyName; if(name){try{await navigator.clipboard.writeText(name);notify(`${name} をコピーしました`,'success');}catch{notify('ユーザー名をコピーできませんでした','error');}}if (uuid && confirm('このオンラインプレイヤーへセットアップ管理者権限を付与しますか？')) mutate('/players/setup-administrator', 'PUT', { uuid }, 'セットアップ管理者に設定しました');if(adopt&&confirm('この既存OPをOrushio管理として引き継ぎますか？ 引き継ぎ後は管理画面からOPを解除できるようになります。'))mutate('/players/setup-administrator/ownership','POST',{uuid:adopt},'Orushio管理として引き継ぎました');if(revoke&&confirm('Orushioから付与したセットアップ管理者権限を解除しますか？'))mutate('/players/setup-administrator','DELETE',{uuid:revoke},'セットアップ管理者を解除しました'); };
$('start').onclick = () => mutate('/game/recruiting/start', 'POST', {}, '参加受付を開始しました', { 'If-Game-State': current.gameState });
$('close').onclick = () => mutate('/game/recruiting/close', 'POST', {}, '参加受付を終了しました', { 'If-Session-Id': current.sessionId });
async function loadDiagnostics() { try { const d = await api('/system/diagnostics'); const rows = [['Paper状態', d.paperRunning ? '稼働中' : '停止'], ['HTTP bind', d.httpBound ? '正常' : '異常'], ['保存領域', d.storageReady ? '利用可能' : '利用不可'], ['設定読込み', d.configLoaded ? '正常' : '失敗'], ['ゲーム状態', d.gameState], ['診断モード', d.diagnosticMode ? '有効' : '無効'], ['警告', (d.warnings || []).join(' / ') || 'なし'], ['追跡ID', d.traceId]]; $('diagnostics').innerHTML = rows.map(([key, value]) => `<dt>${escapeHtml(key)}</dt><dd>${escapeHtml(value)}</dd>`).join(''); } catch (error) { notify(error.message, 'error', error.traceId); } }
async function loadMaps(){try{const [result,setup]=await Promise.all([api('/maps'),api('/maps/setup')]);$('map-list').innerHTML=result.maps.map(map=>`<article class="map-row"><div><strong>${escapeHtml(map.displayName)}</strong><small>${escapeHtml(map.mapId)} / ${map.setupComplete?'セットアップ完了':'未完了'}${result.fixedNextMapId===map.mapId?' / 次回固定中':''}</small><small>${map.missing.length?'不足: '+map.missing.map(escapeHtml).join(', '):'必須項目は揃っています'}</small></div><div class="actions"><button data-map-action="toggle" data-map="${escapeHtml(map.mapId)}" data-enabled="${!map.enabled}">${map.enabled?'無効化':'有効化'}</button><button data-map-action="fix" data-map="${escapeHtml(map.mapId)}">次回固定</button><button data-map-action="setup" data-map="${escapeHtml(map.mapId)}">セットアップ</button><button class="danger" data-map-action="delete" data-map="${escapeHtml(map.mapId)}">削除</button></div></article>`).join('')||'<p>登録済みマップはありません</p>';renderSetup(setup);}catch(error){notify(error.message,'error',error.traceId);}}
function renderSetup(setup){const selected=(setup.fields||[]).find(field=>field.key===setup.selectedField);$('setup-status').textContent=setup.active?`セットアップ中：${setup.displayName||setup.mapId} / 選択項目：${selected?.label||'未選択'}`:'開始されていません';$('setup-field-status').innerHTML=setup.active?(setup.fields||[]).map(field=>`<li><span>${field.complete?'✅':'⚠'} ${escapeHtml(field.label)}${field.required?'（必須）':'（任意）'}</span><strong>${field.requiredCount>1?`${field.count} / ${field.requiredCount}`:field.count>0?'設定済み':'未設定'}${!field.required&&field.count>0?`（${field.count}件）`:''}</strong></li>`).join(''):'<li class="empty">セットアップ開始後に設定状況を表示します</li>';document.querySelectorAll('#setup-fields button').forEach(button=>button.disabled=!setup.active);$('setup-save').disabled=!setup.active;$('setup-discard').disabled=!setup.active;}
$('maps-refresh').onclick=loadMaps;
$('map-import-form').onsubmit=async event=>{event.preventDefault();const file=$('map-zip').files[0],mapId=$('map-id').value.trim(),displayName=$('map-name').value.trim();setLoading(true);try{await api(`/maps/import?mapId=${encodeURIComponent(mapId)}&displayName=${encodeURIComponent(displayName)}`,{method:'POST',headers:{'Content-Type':'application/zip'},body:file});notify('マップを登録しました','success');await loadMaps();}catch(error){notify(error.message,'error',error.traceId);}finally{setLoading(false);}};
$('map-list').onclick=async event=>{const action=event.target.dataset.mapAction,mapId=event.target.dataset.map;if(!action)return;try{if(action==='toggle')await api('/maps/enabled',{method:'PUT',body:JSON.stringify({mapId,enabled:event.target.dataset.enabled==='true'})});if(action==='fix')await api('/maps/next',{method:'PUT',body:JSON.stringify({mapId})});if(action==='setup'){const administrator=$('setup-admin').value;if(!administrator)throw new Error('オンライン管理者を選択してください');await api('/maps/setup/start',{method:'POST',headers:{'If-Game-State':current.gameState},body:JSON.stringify({mapId,administrator})});await refresh({notifyResult:false});}if(action==='delete'){if(!confirm(`${mapId}を削除しますか？ 原本も削除されます。`))return;await api('/maps',{method:'DELETE',body:JSON.stringify({mapId})});}notify('マップ操作が完了しました','success');await loadMaps();}catch(error){notify(error.message,'error',error.traceId);}};
$('setup-fields').onclick=async event=>{const field=event.target.dataset.field;if(!field)return;try{await api('/maps/setup/field',{method:'PUT',body:JSON.stringify({administrator:$('setup-admin').value,field,area:event.target.dataset.area==='true'})});notify('ゲーム内設定ツールでクリックしてください','success');await loadMaps();}catch(error){notify(error.message,'error',error.traceId);}};
$('setup-save').onclick=async()=>{try{await api('/maps/setup/save',{method:'POST',headers:{'If-Session-Id':current.sessionId}});notify('セットアップを保存しました','success');await refresh({notifyResult:false});await loadMaps();}catch(error){notify(error.message,'error',error.traceId);}};
$('setup-discard').onclick=async()=>{if(!confirm('今回のセットアップ変更を破棄しますか？'))return;try{await api('/maps/setup/discard',{method:'POST',headers:{'If-Session-Id':current.sessionId}});notify('セットアップを破棄しました','success');await refresh({notifyResult:false});await loadMaps();}catch(error){notify(error.message,'error',error.traceId);}};
refresh(); setInterval(() => refresh({ notifyResult: false, silent: true }), 5000);
