package com.ryanjei.orushio.pve.application;
import static org.junit.jupiter.api.Assertions.*;
import com.ryanjei.orushio.pve.core.*;import com.ryanjei.orushio.pve.domain.*;import com.ryanjei.orushio.pve.economy.*;import com.ryanjei.orushio.pve.map.*;import com.ryanjei.orushio.pve.pve.*;import java.time.*;import java.util.*;import org.junit.jupiter.api.Test;
class Phase4GameReadinessValidatorTest{
 private final Cuboid farm=new Cuboid(0,60,0,20,80,20),resource=new Cuboid(2,60,2,5,70,5),enemy=new Cuboid(30,60,30,40,80,40);private final BlockPoint shop=new BlockPoint(10,64,10,0,0);private final UUID shopId=UUID.randomUUID();
 @Test void Resource設定不足をPlayer転送前Readinessで拒否する(){var result=validator(GameplaySettings.empty(),pve()).missing(profile(),GameLaunchSettings.defaults());assertTrue(result.stream().anyMatch(v->v.contains("資源採取エリアのPoint・再生成設定")));}
 @Test void Enemy設定不足は対象Zoneを特定して日本語で返す(){var result=validator(gameplay(),PveSettings.empty()).missing(profile(),GameLaunchSettings.defaults());assertTrue(result.stream().anyMatch(v->v.contains("Enemy Zone 1")&&v.contains("敵・出現間隔設定")));assertFalse(String.join(" ",result).contains("PveSettings"));}
 @Test void 全必須設定が対応すれば開始可能(){assertTrue(validator(gameplay(),pve()).missing(profile(),GameLaunchSettings.defaults()).isEmpty());}
 @Test void ShopMarker型とGameplaySettings型の不一致をReadinessで拒否する(){GameplaySettings normal=gameplay();GameplaySettings.Shop value=normal.shops().getFirst();GameplaySettings mismatch=new GameplaySettings(normal.resourceZones(),List.of(new GameplaySettings.Shop(value.shopId(),value.location(),ShopType.WEAPON,value.category(),value.products())));assertTrue(validator(mismatch,pve()).missing(profile(),GameLaunchSettings.defaults()).stream().anyMatch(v->v.contains("資源・ショップ設定に不整合")));}
 @Test void Core設定欠落と必要候補不足を検出する(){var validator=new Phase4GameReadinessValidator(id->gameplay(),id->pve(),new CoreSettingsRepository(){public CoreSettings load(String id){throw new IllegalStateException("missing");}public void save(String id,CoreSettings value){}},material->true);var result=validator.missing(profile(),new GameLaunchSettings(Optional.empty(),Optional.of(4),Optional.empty()));assertTrue(result.stream().anyMatch(v->v.contains("HP設定")));assertTrue(result.stream().anyMatch(v->v.contains("通常コア候補")));}
 @Test void 初期リスポーンは有効な一件だけ要求する(){MapProfile map=profile();List<SetupMarker>none=map.setupMarkers().stream().filter(m->m.markerType()!=SetupMarkerType.INITIAL_RESPAWN).toList();assertTrue(validator(gameplay(),pve()).missing(copy(map,none),GameLaunchSettings.defaults()).stream().anyMatch(v->v.contains("初期リスポーン地点")));List<SetupMarker>two=new ArrayList<>(map.setupMarkers());two.add(marker(SetupMarkerType.INITIAL_RESPAWN,new BlockPoint(2,64,2,0,0)));assertTrue(validator(gameplay(),pve()).missing(copy(map,two),GameLaunchSettings.defaults()).stream().anyMatch(v->v.contains("1件だけ")));}
 @Test void 最終エリア入口と転送先は要求しない(){assertFalse(profile().missingRequirements().stream().anyMatch(v->v.contains("finalArea")));}
 @Test void FinalRegion部分交差EnemyZoneはReadinessで開始拒否する(){MapProfile source=profile();Cuboid crossing=new Cuboid(80,60,80,100,80,100);Map<String,List<Cuboid>>areas=new HashMap<>(source.areas());areas.put("enemyZones",List.of(crossing));MapProfile map=new MapProfile(source.mapId(),source.displayName(),false,source.templateDirectory(),source.points(),areas,source.createdAt(),source.spawnMarkers(),source.setupMarkers());PveSettings value=new PveSettings(List.of(new PveSettings.EnemyZone(UUID.randomUUID(),crossing,Duration.ofSeconds(5),1,Map.of(EnemyType.ZOMBIE,1),2,30)));assertTrue(validator(gameplay(),value).missing(map,GameLaunchSettings.defaults()).stream().anyMatch(v->v.contains("敵出現設定")));}
 private Phase4GameReadinessValidator validator(GameplaySettings gameplay,PveSettings pve){return new Phase4GameReadinessValidator(id->gameplay,id->pve,new CoreSettingsRepository(){public CoreSettings load(String id){return new CoreSettings(10,20);}public void save(String id,CoreSettings value){}},material->true);}
 private GameplaySettings gameplay(){return new GameplaySettings(List.of(new GameplaySettings.ResourceZone(UUID.randomUUID(),PointCategory.MINING,"STONE",1,Duration.ofSeconds(5),resource)),List.of(new GameplaySettings.Shop(shopId,shop,ShopType.SPECIAL,"TOOL",List.of(new GameplaySettings.Product(0,PointCategory.MINING,1,new ItemSpec("WOODEN_PICKAXE",1,Map.of(),false))))));}
 private PveSettings pve(){return new PveSettings(List.of(new PveSettings.EnemyZone(UUID.randomUUID(),enemy,Duration.ofSeconds(5),1,Map.of(EnemyType.ZOMBIE,1),2,30)));}
 private MapProfile profile(){MapProfile complete=MapProfileTest.complete("map-a");Map<String,List<Cuboid>>areas=new HashMap<>(complete.areas());areas.put("farmRegion",List.of(farm));areas.put("resourceZones",List.of(resource));areas.put("enemyZones",List.of(enemy));List<SetupMarker>markers=new ArrayList<>(complete.setupMarkers());markers.add(new SetupMarker(shopId,SetupMarkerType.SPECIAL_SHOP,shop,true));return new MapProfile(complete.mapId(),complete.displayName(),false,complete.templateDirectory(),complete.points(),areas,complete.createdAt(),complete.spawnMarkers(),markers);}
 private static SetupMarker marker(SetupMarkerType type,BlockPoint point){return new SetupMarker(UUID.randomUUID(),type,point,true);}private static MapProfile copy(MapProfile map,List<SetupMarker>markers){return new MapProfile(map.mapId(),map.displayName(),false,map.templateDirectory(),map.points(),map.areas(),map.createdAt(),map.spawnMarkers(),markers);}
}
