package com.ryanjei.orushio.pve.application;
import static org.junit.jupiter.api.Assertions.*;import com.ryanjei.orushio.pve.core.*;import com.ryanjei.orushio.pve.domain.*;import com.ryanjei.orushio.pve.economy.*;import com.ryanjei.orushio.pve.map.*;import com.ryanjei.orushio.pve.pve.*;import java.time.*;import java.util.*;import org.junit.jupiter.api.Test;
class Phase4GameReadinessValidatorTest{
 private final Cuboid farm=new Cuboid(0,60,0,20,80,20),resource=new Cuboid(2,60,2,5,70,5),enemy=new Cuboid(30,60,30,40,80,40);private final BlockPoint shop=new BlockPoint(10,64,10,0,0);private final UUID shopId=UUID.randomUUID();
 @Test void Resource設定不足をPlayer転送前Readinessで拒否する(){var result=validator(GameplaySettings.empty(),pve()).missing(profile(),GameLaunchSettings.defaults());assertTrue(result.stream().anyMatch(v->v.contains("資源採取エリアのPoint・再生成設定")));}
 @Test void Enemy設定不足と複数不足をまとめて日本語で返す(){var result=validator(GameplaySettings.empty(),PveSettings.empty()).missing(profile(),GameLaunchSettings.defaults());assertTrue(result.stream().anyMatch(v->v.contains("資源採取")));assertTrue(result.stream().anyMatch(v->v.contains("敵出現エリア")));assertFalse(String.join(" ",result).contains("GameplaySettings"));}
 @Test void 全必須設定が対応すれば開始可能(){assertTrue(validator(gameplay(),pve()).missing(profile(),GameLaunchSettings.defaults()).isEmpty());}
 @Test void ShopMarker型とGameplaySettings型の不一致をReadinessで拒否する(){GameplaySettings normal=gameplay();GameplaySettings.Shop shop=normal.shops().getFirst();GameplaySettings mismatch=new GameplaySettings(normal.resourceZones(),List.of(new GameplaySettings.Shop(shop.shopId(),shop.location(),ShopType.WEAPON,shop.category(),shop.products())));var result=validator(mismatch,pve()).missing(profile(),GameLaunchSettings.defaults());assertTrue(result.stream().anyMatch(v->v.contains("資源・ショップ設定に不整合")));}
 @Test void Core設定欠落と必要候補不足を検出する(){MapProfile map=profile();var validator=new Phase4GameReadinessValidator(id->gameplay(),id->pve(),new CoreSettingsRepository(){public CoreSettings load(String id){throw new IllegalStateException("missing");}public void save(String id,CoreSettings value){}},material->true);var result=validator.missing(map,new GameLaunchSettings(Optional.empty(),Optional.of(4),Optional.empty()));assertTrue(result.stream().anyMatch(v->v.contains("HP設定")));assertTrue(result.stream().anyMatch(v->v.contains("通常コア候補")));}
 @Test void FinalArea入口と転送先はそれぞれ有効な1件を要求する(){MapProfile map=profile();List<SetupMarker>withoutEntry=map.setupMarkers().stream().map(m->m.markerType()==SetupMarkerType.FINAL_AREA_ENTRY?m.withEnabled(false):m).toList();MapProfile missingEntry=copy(map,withoutEntry);assertTrue(validator(gameplay(),pve()).missing(missingEntry,GameLaunchSettings.defaults()).stream().anyMatch(v->v.contains("最終エリア入口")));List<SetupMarker>withoutDestination=new ArrayList<>(map.setupMarkers());withoutDestination.removeIf(m->m.markerType()==SetupMarkerType.FINAL_AREA_DESTINATION);assertTrue(validator(gameplay(),pve()).missing(copy(map,withoutDestination),GameLaunchSettings.defaults()).stream().anyMatch(v->v.contains("最終エリア転送先")));}
 private Phase4GameReadinessValidator validator(GameplaySettings gameplay,PveSettings pve){return new Phase4GameReadinessValidator(id->gameplay,id->pve,new CoreSettingsRepository(){public CoreSettings load(String id){return new CoreSettings(10,20);}public void save(String id,CoreSettings value){}},material->true);}
 private GameplaySettings gameplay(){return new GameplaySettings(List.of(new GameplaySettings.ResourceZone(UUID.randomUUID(),PointCategory.MINING,"STONE",1,Duration.ofSeconds(5),resource)),List.of(new GameplaySettings.Shop(shopId,shop,ShopType.SPECIAL,"TOOL",List.of(new GameplaySettings.Product(0,PointCategory.MINING,1,new ItemSpec("WOODEN_PICKAXE",1,Map.of(),false))))));}
 private PveSettings pve(){return new PveSettings(List.of(new PveSettings.EnemyZone(UUID.randomUUID(),enemy,Duration.ofSeconds(5),1,Map.of(EnemyType.ZOMBIE,1),2,30)));}
 private MapProfile profile(){BlockPoint p=new BlockPoint(1,64,1,0,0);Map<String,List<BlockPoint>>points=new HashMap<>();for(String key:MapProfile.REQUIRED_SINGLE_POINTS)points.put(key,List.of(p));points.put("normalCoreCandidates",List.of(p,new BlockPoint(2,64,1,0,0),new BlockPoint(3,64,1,0,0)));Map<String,List<Cuboid>>areas=new HashMap<>();for(String key:MapProfile.REQUIRED_AREA_COUNTS.keySet())areas.put(key,List.of(new Cuboid(50,60,50,60,80,60)));areas.put("farmRegion",List.of(farm));areas.put("resourceZones",List.of(resource));areas.put("enemyZones",List.of(enemy));MapProfile base=new MapProfile(new MapProfileId("map-a"),"Map A",false,"template",points,areas,Instant.now(),List.of(),List.of(new SetupMarker(shopId,SetupMarkerType.SPECIAL_SHOP,shop,true)));List<SetupMarker>markers=new ArrayList<>(base.setupMarkers());markers.add(new SetupMarker(UUID.randomUUID(),SetupMarkerType.FINAL_AREA_DESTINATION,new BlockPoint(55,64,55,0,0),true));return copy(base,markers);}
 private static MapProfile copy(MapProfile map,List<SetupMarker>markers){return new MapProfile(map.mapId(),map.displayName(),false,map.templateDirectory(),map.points(),map.areas(),map.createdAt(),map.spawnMarkers(),markers);}
}
