package com.ryanjei.orushio.pve.application;

import static org.junit.jupiter.api.Assertions.*;
import com.ryanjei.orushio.pve.domain.*;import com.ryanjei.orushio.pve.logging.AuditSink;import com.ryanjei.orushio.pve.persistence.PendingPlayerCleanupRepository;
import java.time.*;import java.util.*;import org.junit.jupiter.api.*;

class PlayerInventoryLifecycleStepTest {
    UUID online=UUID.randomUUID(),offline=UUID.randomUUID(),outsider=UUID.randomUUID();FakeGateway gateway;MemoryPending pending;List<String> audits;PlayerInventoryLifecycleStep step;
    @BeforeEach void setup(){gateway=new FakeGateway();pending=new MemoryPending();audits=new ArrayList<>();step=new PlayerInventoryLifecycleStep(gateway,pending,new AuditSink(){public void record(String a,String b,String code,String d){audits.add(code);}public boolean healthy(){return true;}});}
    @Test void prepareはonlineParticipantだけ初期化し再試行で二重処理しない(){gateway.online.add(online);GameSession session=preparing(UUID.randomUUID(),online,offline);step.prepare(session);step.prepare(session);assertEquals(List.of(online),gateway.initialized);assertFalse(gateway.initialized.contains(outsider));assertEquals(1,audits.stream().filter("PLAYER_GAME_INVENTORY_INITIALIZED"::equals).count());}
    @Test void prepare途中失敗は今回変更分だけrollbackし別Sessionを拒否する(){gateway.online.addAll(List.of(online,offline));gateway.failInitialize=offline;GameSession session=preparing(UUID.randomUUID(),online,offline);assertThrows(RuntimeException.class,()->step.prepare(session));assertThrows(IllegalStateException.class,()->step.rollbackPreparation(preparing(UUID.randomUUID(),online)));step.rollbackPreparation(session);assertEquals(List.of(online),gateway.rolledBack);assertFalse(gateway.rolledBack.contains(offline));assertTrue(audits.contains("PLAYER_GAME_INVENTORY_ROLLED_BACK"));}
    @Test void ACTIVE再接続は未初期化時だけ初期化する(){gateway.online.add(online);GameSession active=active(UUID.randomUUID(),online);step.participantConnected(active,online);step.participantConnected(active,online);assertEquals(List.of(online),gateway.initialized);}
    @Test void cleanupはonlineを削除しofflineをsessionId付きで冪等登録する(){gateway.online.add(online);UUID sessionId=UUID.randomUUID();GameSession session=active(sessionId,online,offline);step.cleanup(session);step.cleanup(session);assertEquals(2,gateway.cleaned.stream().filter(online::equals).count());assertEquals(Set.of(new PendingPlayerCleanupRepository.Entry(offline,sessionId)),pending.entries);assertEquals(Set.of(offline),step.pendingCleanupPlayers(session));assertEquals(Set.of(online),step.completedCleanupPlayers(session));}
    @Test void pendingJoinはownership証跡がある非Participantだけ処理する(){UUID oldSession=UUID.randomUUID();pending.add(new PendingPlayerCleanupRepository.Entry(online,oldSession));gateway.online.add(online);GameSession idle=GameSession.idleWithPending(Set.of(online));assertTrue(step.pendingCleanupConnected(idle,online));assertTrue(pending.entries.isEmpty());assertTrue(audits.contains("PLAYER_PENDING_CLEANUP_COMPLETED"));pending.add(new PendingPlayerCleanupRepository.Entry(online,oldSession));GameSession current=active(UUID.randomUUID(),online);assertFalse(step.pendingCleanupConnected(current,online));assertFalse(pending.entries.isEmpty());}
    @Test void UUIDだけの旧pendingは削除せずcleanup失敗時に成功auditを残さない(){gateway.online.add(online);assertFalse(step.pendingCleanupConnected(GameSession.idleWithPending(Set.of(online)),online));assertTrue(gateway.cleaned.isEmpty());gateway.failCleanup=online;GameSession session=active(UUID.randomUUID(),online);assertThrows(RuntimeException.class,()->step.cleanup(session));assertFalse(audits.contains("PLAYER_GAME_INVENTORY_CLEANED"));}
    @Test void rollback失敗Recoveryは再接続復元後にInventoryを削除しない(){gateway.online.add(online);GameSession preparing=preparing(UUID.randomUUID(),online);step.prepare(preparing);gateway.failRollback=online;assertThrows(RuntimeException.class,()->step.rollbackPreparation(preparing));GameSession recovering=preparing.transitionedTo(GameState.ABORTING).transitionedTo(GameState.RECOVERING);gateway.failRollback=null;step.participantConnected(recovering,online);step.cleanup(recovering);assertEquals(List.of(online),gateway.rolledBack);assertTrue(gateway.cleaned.isEmpty());assertEquals(Set.of(online),step.completedCleanupPlayers(recovering));}
    private static GameSession preparing(UUID session,UUID...players){return new GameSession(session,GameState.PREPARING,Arrays.stream(players).map(id->new Participant(id,"P",true)).toList(),Instant.now(),"map-a",players.length,60,2,1,null,null,Set.of());}
    private static GameSession active(UUID session,UUID...players){Instant now=Instant.now();return new GameSession(session,GameState.ACTIVE,Arrays.stream(players).map(id->new Participant(id,"P",true)).toList(),now,"map-a",players.length,60,2,1,now,now.plusSeconds(60),Set.of());}
    private static final class Token implements PlayerInventoryGateway.RollbackState{final UUID player;Token(UUID player){this.player=player;}}
    private static final class FakeGateway implements PlayerInventoryGateway{final Set<UUID>online=new HashSet<>();final List<UUID>initialized=new ArrayList<>(),rolledBack=new ArrayList<>(),cleaned=new ArrayList<>();UUID failInitialize,failRollback,failCleanup;public Optional<RollbackState>initializeIfOnline(UUID id){if(id.equals(failInitialize))throw new IllegalStateException("init");if(!online.contains(id))return Optional.empty();initialized.add(id);return Optional.of(new Token(id));}public void rollback(UUID id,RollbackState state){if(id.equals(failRollback))throw new IllegalStateException("rollback");assertEquals(id,((Token)state).player);rolledBack.add(id);}public CleanupResult returnToLobbyAndCleanup(UUID id){if(id.equals(failCleanup))throw new IllegalStateException("cleanup");if(!online.contains(id))return CleanupResult.OFFLINE;cleaned.add(id);return CleanupResult.CLEANED;}}
    private static final class MemoryPending implements PendingPlayerCleanupRepository{final Set<Entry>entries=new LinkedHashSet<>();public Set<Entry>findAll(){return Set.copyOf(entries);}public void add(Entry entry){entries.add(entry);}public void remove(Entry entry){entries.remove(entry);}}
}
