package com.ryanjei.orushio.pve.progression;

import static org.junit.jupiter.api.Assertions.*;
import com.ryanjei.orushio.pve.domain.*;
import com.ryanjei.orushio.pve.logging.AuditSink;
import com.ryanjei.orushio.pve.map.*;
import java.time.Instant;
import java.util.*;
import org.junit.jupiter.api.*;

class FinalAreaProgressionStepTest{
 UUID sessionId=UUID.randomUUID(),alice=UUID.randomUUID(),bob=UUID.randomUUID();BlockPoint entry=new BlockPoint(10,64,10,0,0),destination=new BlockPoint(100,64,100,90,0),checkpointA=new BlockPoint(110,64,110,0,0),checkpointB=new BlockPoint(120,64,120,0,0);FakeGateway gateway;List<String>audits;FinalAreaProgressionStep step;GameSession preparing,active;
 @BeforeEach void setup(){List<SetupMarker>markers=new ArrayList<>(MapProfileTest.complete("map-a").setupMarkers());markers.add(marker(SetupMarkerType.FINAL_AREA_DESTINATION,destination,true));markers.add(marker(SetupMarkerType.CHECKPOINT,checkpointA,true));markers.add(marker(SetupMarkerType.CHECKPOINT,checkpointB,true));MapProfile base=MapProfileTest.complete("map-a");MapProfile profile=new MapProfile(base.mapId(),base.displayName(),true,base.templateDirectory(),base.points(),base.areas(),base.createdAt(),base.spawnMarkers(),replace(markers,SetupMarkerType.FINAL_AREA_ENTRY,entry));GameRuntimeContext context=new GameRuntimeContext(sessionId,"run-a",RuntimeMap.resolve(profile));gateway=new FakeGateway();audits=new ArrayList<>();AuditSink audit=new AuditSink(){public void record(String t,String c,String code,String o){audits.add(code);}public boolean healthy(){return true;}};step=new FinalAreaProgressionStep(id->id.equals(sessionId)?Optional.of(context):Optional.empty(),gateway,audit);Instant now=Instant.now();preparing=new GameSession(sessionId,GameState.PREPARING,List.of(new Participant(alice,"Alice",true),new Participant(bob,"Bob",true)),now,"map-a",2,60,2,1,null,null,Set.of());active=new GameSession(sessionId,GameState.ACTIVE,preparing.participants(),now,"map-a",2,60,2,1,now,now.plusSeconds(60),Set.of());step.prepare(preparing);}
 @Test void required未達は通知だけでWarpせず到達時に一度だけ解禁する(){assertEquals(FinalAreaProgressionStep.ContactResult.LOCKED,contact(alice,entry));assertTrue(gateway.teleports.isEmpty());assertEquals(1,gateway.locked);step.normalCoreDestroyed(sessionId,1);assertFalse(step.progressionView().finalAreaUnlocked());step.normalCoreDestroyed(sessionId,2);step.normalCoreDestroyed(sessionId,2);assertTrue(step.progressionView().finalAreaUnlocked());assertEquals(1,audits.stream().filter("FINAL_AREA_UNLOCKED"::equals).count());}
 @Test void 解禁後Participantだけ転送し同一Block滞在と再接触で二重Warpしない(){step.normalCoreDestroyed(sessionId,2);assertEquals(FinalAreaProgressionStep.ContactResult.ENTERED,contact(alice,entry));assertEquals(FinalAreaProgressionStep.ContactResult.IGNORED,contact(alice,entry));contact(alice,new BlockPoint(11,64,10,0,0));assertEquals(FinalAreaProgressionStep.ContactResult.IGNORED,contact(alice,entry));assertEquals(1,gateway.teleports.size());assertEquals(destination,gateway.teleports.getFirst().destination);assertEquals(FinalAreaProgressionStep.ContactResult.IGNORED,step.contact(active,UUID.randomUUID(),"run-a",entry.x(),entry.y(),entry.z()));assertEquals(FinalAreaProgressionStep.ContactResult.IGNORED,step.contact(active,alice,"other",entry.x(),entry.y(),entry.z()));}
 @Test void CheckpointはPlayer単位で最後に触れた地点へ更新しRespawnへ使用する(){step.normalCoreDestroyed(sessionId,2);contact(alice,entry);assertEquals(FinalAreaProgressionStep.ContactResult.CHECKPOINT_ACTIVATED,contact(alice,checkpointA));assertEquals(FinalAreaProgressionStep.ContactResult.IGNORED,contact(alice,checkpointA));assertEquals(FinalAreaProgressionStep.ContactResult.CHECKPOINT_ACTIVATED,contact(alice,checkpointB));assertTrue(step.participantRespawnedHandled(active,alice));assertEquals(checkpointB,gateway.teleports.getLast().destination);assertFalse(step.participantRespawnedHandled(active,bob));assertTrue(step.progressionView().participants().stream().filter(p->p.playerId().equals(alice)).findFirst().orElseThrow().checkpointActive());assertFalse(step.progressionView().participants().stream().filter(p->p.playerId().equals(bob)).findFirst().orElseThrow().checkpointActive());}
 @Test void 未進入Participantと別SessionはCheckpointを取得せずcleanupで状態を破棄する(){assertEquals(FinalAreaProgressionStep.ContactResult.IGNORED,contact(bob,checkpointA));GameSession other=new GameSession(UUID.randomUUID(),GameState.ACTIVE,active.participants(),active.createdAt(),active.mapId(),2,60,2,1,active.activeAt().orElseThrow(),active.endsAt().orElseThrow(),Set.of());assertEquals(FinalAreaProgressionStep.ContactResult.IGNORED,step.contact(other,alice,"run-a",checkpointA.x(),checkpointA.y(),checkpointA.z()));step.cleanup(active);assertEquals(FinalAreaProgressionView.idle(),step.progressionView());assertFalse(step.participantRespawnedHandled(active,alice));}
 @Test void FinalCore状態は同一Sessionで一度だけ確定する(){step.finalCoreDestroyed(sessionId);step.finalCoreDestroyed(sessionId);assertTrue(step.progressionView().finalCoreDestroyed());assertThrows(IllegalStateException.class,()->step.finalCoreDestroyed(UUID.randomUUID()));}
 private FinalAreaProgressionStep.ContactResult contact(UUID player,BlockPoint p){return step.contact(active,player,"run-a",p.x(),p.y(),p.z());}
 private static SetupMarker marker(SetupMarkerType type,BlockPoint p,boolean enabled){return new SetupMarker(UUID.randomUUID(),type,p,enabled);}
 private static List<SetupMarker>replace(List<SetupMarker>source,SetupMarkerType type,BlockPoint point){List<SetupMarker>result=new ArrayList<>(source);result.removeIf(m->m.markerType()==type);result.add(marker(type,point,true));return result;}
 private static final class FakeGateway implements FinalAreaGateway{record Teleport(UUID session,String world,UUID player,BlockPoint destination){}final List<Teleport>teleports=new ArrayList<>();int locked;public void teleport(UUID s,String w,UUID p,BlockPoint d){teleports.add(new Teleport(s,w,p,d));}public void notifyLocked(UUID s,String w,UUID p){locked++;}}
}
