package com.ryanjei.orushio.pve.progression;
import static org.junit.jupiter.api.Assertions.*;import com.ryanjei.orushio.pve.domain.*;import com.ryanjei.orushio.pve.logging.AuditSink;import com.ryanjei.orushio.pve.map.*;import java.time.Instant;import java.util.*;import org.junit.jupiter.api.*;
class FinalAreaProgressionStepTest{
 UUID sessionId=UUID.randomUUID(),alice=UUID.randomUUID(),bob=UUID.randomUUID();BlockPoint initial=new BlockPoint(0,64,0,0,0),warp=new BlockPoint(5,64,5,0,0),saveA=new BlockPoint(20,64,20,0,0),saveB=new BlockPoint(30,64,30,0,0),finalPoint=new BlockPoint(100,64,100,0,0);FakeGateway gateway;List<String>audits;FinalAreaProgressionStep step;GameSession preparing,active;
 @BeforeEach void setup(){MapProfile base=MapProfileTest.complete("map-a");List<SetupMarker>markers=new ArrayList<>(base.setupMarkers());markers.removeIf(m->Set.of(SetupMarkerType.INITIAL_RESPAWN,SetupMarkerType.WARP,SetupMarkerType.SAVE_POINT).contains(m.markerType()));markers.add(marker(SetupMarkerType.INITIAL_RESPAWN,initial));markers.add(marker(SetupMarkerType.WARP,warp));markers.add(marker(SetupMarkerType.WARP,new BlockPoint(6,64,6,0,0)));markers.add(marker(SetupMarkerType.SAVE_POINT,saveA));markers.add(marker(SetupMarkerType.SAVE_POINT,saveB));MapProfile profile=new MapProfile(base.mapId(),base.displayName(),true,base.templateDirectory(),base.points(),base.areas(),base.createdAt(),base.spawnMarkers(),markers);GameRuntimeContext context=new GameRuntimeContext(sessionId,"run-a",RuntimeMap.resolve(profile));gateway=new FakeGateway();audits=new ArrayList<>();AuditSink audit=new AuditSink(){public void record(String t,String c,String code,String o){audits.add(code);}public boolean healthy(){return true;}};step=new FinalAreaProgressionStep(id->id.equals(sessionId)?Optional.of(context):Optional.empty(),gateway,audit);Instant now=Instant.now();preparing=new GameSession(sessionId,GameState.PREPARING,List.of(new Participant(alice,"Alice",true),new Participant(bob,"Bob",true)),now,"map-a",2,60,2,1,null,null,Set.of());active=new GameSession(sessionId,GameState.ACTIVE,preparing.participants(),now,"map-a",2,60,2,1,now,now.plusSeconds(60),Set.of());step.prepare(preparing);}
 @Test void 未取得PlayerのWarpは初期地点_死亡RespawnはRuntimeLifecycleへ委譲(){assertEquals(FinalAreaProgressionStep.ContactResult.WARPED,contact(alice,warp));assertEquals(initial,gateway.last());assertFalse(step.participantRespawnedHandled(active,bob));}
 @Test void SavePoint取得済みでも死亡Respawnを横取りしない(){assertEquals(FinalAreaProgressionStep.ContactResult.SAVE_POINT_ACTIVATED,contact(alice,saveA));assertFalse(step.participantRespawnedHandled(active,alice));moveOff(alice);assertEquals(FinalAreaProgressionStep.ContactResult.WARPED,contact(alice,warp));assertEquals(saveA,gateway.last());}
 @Test void SavePointはPlayer単位で最新地点へ更新しWarpする(){assertEquals(FinalAreaProgressionStep.ContactResult.SAVE_POINT_ACTIVATED,contact(alice,saveA));moveOff(alice);assertEquals(FinalAreaProgressionStep.ContactResult.SAVE_POINT_ACTIVATED,contact(alice,saveB));moveOff(alice);assertEquals(FinalAreaProgressionStep.ContactResult.WARPED,contact(alice,warp));assertEquals(saveB,gateway.last());moveOff(bob);contact(bob,warp);assertEquals(initial,gateway.last());assertTrue(step.progressionView().participants().stream().filter(p->p.playerId().equals(alice)).findFirst().orElseThrow().savePointActive());}
 @Test void 同一Block連続発火なし_別Session無視_cleanupで次Gameへ漏れない(){assertEquals(FinalAreaProgressionStep.ContactResult.SAVE_POINT_ACTIVATED,contact(alice,saveA));assertEquals(FinalAreaProgressionStep.ContactResult.IGNORED,contact(alice,saveA));GameSession other=new GameSession(UUID.randomUUID(),GameState.ACTIVE,active.participants(),active.createdAt(),active.mapId(),2,60,2,1,active.activeAt().orElseThrow(),active.endsAt().orElseThrow(),Set.of());assertEquals(FinalAreaProgressionStep.ContactResult.IGNORED,step.contact(other,alice,"run-a",saveB.x(),saveB.y(),saveB.z()));step.cleanup(active);assertFalse(step.participantRespawnedHandled(active,alice));}
 @Test void Gate解禁後のfinalRegion実進入だけを一度記録する(){assertEquals(FinalAreaProgressionStep.ContactResult.IGNORED,contact(alice,finalPoint));step.normalCoreDestroyed(sessionId,2);moveOff(alice);assertEquals(FinalAreaProgressionStep.ContactResult.ENTERED,contact(alice,finalPoint));assertEquals(FinalAreaProgressionStep.ContactResult.IGNORED,contact(alice,finalPoint));assertEquals(1,audits.stream().filter("FINAL_AREA_ENTERED"::equals).count());}
 @Test void FinalCore状態とAuditは同一Sessionで一度だけ確定する(){step.finalCoreDestroyed(sessionId);step.finalCoreDestroyed(sessionId);assertEquals(1,audits.stream().filter("FINAL_CORE_DESTROYED"::equals).count());assertThrows(IllegalStateException.class,()->step.finalCoreDestroyed(UUID.randomUUID()));}
 private void moveOff(UUID player){step.contact(active,player,"run-a",70,64,70);}private FinalAreaProgressionStep.ContactResult contact(UUID player,BlockPoint p){return step.contact(active,player,"run-a",p.x(),p.y(),p.z());}private static SetupMarker marker(SetupMarkerType type,BlockPoint p){return new SetupMarker(UUID.randomUUID(),type,p,true);}
 private static final class FakeGateway implements FinalAreaGateway{record Teleport(BlockPoint destination){}final List<Teleport>teleports=new ArrayList<>();public void teleport(UUID s,String w,UUID p,BlockPoint d){teleports.add(new Teleport(d));}public void notifyLocked(UUID s,String w,UUID p){}BlockPoint last(){return teleports.getLast().destination();}}
}
