package com.ryanjei.orushio.pve;

import com.ryanjei.orushio.pve.application.*;
import com.ryanjei.orushio.pve.bootstrap.RuntimeConfiguration;
import com.ryanjei.orushio.pve.bootstrap.StartupState;
import com.ryanjei.orushio.pve.bootstrap.BootstrapHandoff;
import com.ryanjei.orushio.pve.bootstrap.LauncherShutdownHandoff;
import com.ryanjei.orushio.pve.domain.GameSession;
import com.ryanjei.orushio.pve.http.AdminHttpServer;
import com.ryanjei.orushio.pve.logging.AuditLog;
import com.ryanjei.orushio.pve.map.*;
import com.ryanjei.orushio.pve.paper.*;
import com.ryanjei.orushio.pve.persistence.*;
import com.ryanjei.orushio.pve.security.AuthService;
import com.ryanjei.orushio.pve.security.LauncherShutdownToken;
import org.bukkit.plugin.java.JavaPlugin;
import java.net.InetAddress;
import java.nio.file.*;
import java.security.SecureRandom;
import java.util.*;

public final class OrushioPvePlugin extends JavaPlugin {
    private AdminHttpServer http; private PaperGameThreadExecutor gameThread; private BootstrapHandoff bootstrapHandoff;private LauncherShutdownHandoff shutdownHandoff;
    @Override public void onEnable(){Path data=getDataFolder().toPath();try{Files.createDirectories(data);bootstrapHandoff=new BootstrapHandoff(data.resolve("admin-bootstrap.url"));bootstrapHandoff.clear();shutdownHandoff=new LauncherShutdownHandoff(data.resolve("launcher-shutdown.token"));shutdownHandoff.clear();StartupState startup=StartupState.load(data);RuntimeConfiguration config=startup.configuration();AuditLog audit=new AuditLog(data.resolve("logs"));DefaultGameApplicationService games=createGames(data,startup);gameThread=new PaperGameThreadExecutor(this);ServerAdministrationService serverAdministration=new DefaultServerAdministrationService(new PaperServerAdministrationGateway(gameThread));Path mapsRoot=data.resolve("maps");TemporaryWorldManager temporaryWorlds=new TemporaryWorldManager(mapsRoot,getServer().getWorldContainer().toPath());temporaryWorlds.prepareStartupRecovery();java.util.concurrent.CompletableFuture.runAsync(temporaryWorlds::recoverPreparedWorlds).exceptionally(error->{getLogger().severe("起動時の一時ワールド回収に失敗しました。管理画面の診断情報を確認してください。");return null;});PaperMapWorldGateway mapWorlds=new PaperMapWorldGateway(this,gameThread);MapAdministrationService maps=new DefaultMapAdministrationService(mapsRoot,new YamlMapProfileRepository(mapsRoot),new SafeWorldZipImporter(mapsRoot,SafeWorldZipImporter.Limits.defaults()),temporaryWorlds,mapWorlds,games,new MapSelectionService(new Random()));getServer().getPluginManager().registerEvents(new MapSetupListener(maps,mapWorlds),this);ensureSecrets(data,config);final boolean[] bound={false};LauncherShutdownToken shutdownToken=new LauncherShutdownToken();PaperShutdownController shutdownController=new PaperShutdownController(gameThread,()->getServer().shutdown());http=new AdminHttpServer(InetAddress.getByName("127.0.0.1"),config.port(),games,serverAdministration,maps,new AuthService(),()->diagnostics(startup,audit,bound[0],data,games,temporaryWorlds),audit,startup.diagnosticMode(),shutdownToken,shutdownController::request);http.start();bound[0]=true;bootstrapHandoff.publish(config.port(),http.issueBootstrapToken());shutdownHandoff.publish(shutdownToken.issue());audit.record(config.traceId(),"SYSTEM",startup.diagnosticMode()?"DIAGNOSTIC_START":"NORMAL_START","PLUGIN_ENABLE");getLogger().info(startup.diagnosticMode()?"OPBPを診断モードで起動しました。":"OPBP基盤を起動しました。管理画面: http://127.0.0.1:"+config.port()+"/");}catch(Exception e){getLogger().severe("管理HTTPを安全に起動できないためプラグインを停止します。追跡ID: "+UUID.randomUUID());getServer().getPluginManager().disablePlugin(this);}}
    private DefaultGameApplicationService createGames(Path data,StartupState startup){GameSession initial=startup.session().orElseGet(GameSession::idle);if(!startup.diagnosticMode())return new DefaultGameApplicationService(new YamlActiveSessionRepository(data.resolve("sessions/active.yml")),initial);return new DefaultGameApplicationService(new ActiveSessionRepository(){public Optional<GameSession> load(){return Optional.of(initial);}public void save(GameSession ignored){throw new RepositoryException("診断モードではゲーム状態を保存できません。");}},initial);}
    private Map<String,Object> diagnostics(StartupState startup,AuditLog audit,boolean bound,Path data,DefaultGameApplicationService games,TemporaryWorldManager temporaryWorlds){RuntimeConfiguration c=startup.configuration();List<String>w=new ArrayList<>(startup.warnings());if(!audit.healthy())w.add("監査ログへ書き込めません。");temporaryWorlds.startupRecoveryWarning().ifPresent(w::add);Map<String,Object> m=new LinkedHashMap<>();m.put("paperRunning",true);m.put("pluginVersion",getPluginMeta().getVersion());m.put("httpBound",bound);m.put("storageReady",Files.isDirectory(data)&&Files.isWritable(data));m.put("configLoaded",c.configLoaded());m.put("sessionLoaded",startup.sessionLoaded());m.put("recoveryRequired",startup.recoveryRequired()||temporaryWorlds.startupRecoveryWarning().isPresent());m.put("temporaryWorldRecoveryComplete",temporaryWorlds.startupRecoveryComplete());m.put("diagnosticMode",startup.diagnosticMode());m.put("gameState",games.current().state().name());m.put("warnings",w);m.put("traceId",c.traceId());return m;}
    private void ensureSecrets(Path data,RuntimeConfiguration config){if(config.diagnosticMode())return;byte[] secret=new byte[32];new SecureRandom().nextBytes(secret);new YamlConfigRepository(data.resolve("secrets.yml")).loadOrCreate(Map.of("schemaVersion","1","installationSecret",Base64.getEncoder().encodeToString(secret)));}
    @Override public void onDisable(){if(bootstrapHandoff!=null){try{bootstrapHandoff.clear();}catch(Exception ignored){}bootstrapHandoff=null;}if(shutdownHandoff!=null){try{shutdownHandoff.clear();}catch(Exception ignored){}shutdownHandoff=null;}if(http!=null){http.close();http=null;}if(gameThread!=null){gameThread.close();gameThread=null;}getLogger().info("OPBP基盤を安全に停止しました。");}
}
