package com.ryanjei.orushio.pve.paper;
import com.ryanjei.orushio.pve.application.GameThreadExecutor;import com.ryanjei.orushio.pve.domain.Participant;import com.ryanjei.orushio.pve.map.*;import org.bukkit.*;import java.time.Duration;import java.util.*;
public final class PaperGameRuntimeGateway implements GameRuntimeGateway{
 private final GameThreadExecutor executor;public PaperGameRuntimeGateway(GameThreadExecutor executor){this.executor=executor;}
 public void prepare(TemporaryWorldManager.OwnedWorld owned,RuntimeMap map,List<Participant> participants){execute(()->{World world=Bukkit.createWorld(new WorldCreator(owned.worldName()));if(world==null)throw new IllegalStateException("ゲームワールドを読み込めません。");world.setGameRule(GameRule.DO_MOB_SPAWNING,false);BlockPoint start=start(map.profile());validate(world,start);for(SpawnMarker marker:map.enabledMarkers())validate(world,marker.position());for(Participant participant:participants){var player=Bukkit.getPlayer(participant.playerUuid());if(player!=null&&!player.teleport(location(world,start)))throw new IllegalStateException("ゲーム参加者を転送できません。");}return null;});}
 public void returnParticipantsAndUnload(TemporaryWorldManager.OwnedWorld owned,List<Participant> participants){execute(()->{World world=Bukkit.getWorld(owned.worldName());if(world==null)return null;World lobby=lobby(world);for(var player:new ArrayList<>(world.getPlayers()))if(!player.teleport(lobby.getSpawnLocation()))throw new IllegalStateException("参加者をロビーへ戻せません。");if(!world.getPlayers().isEmpty())throw new IllegalStateException("ゲームワールドにPlayerが残っています。");if(!Bukkit.unloadWorld(world,false))throw new IllegalStateException("ゲームワールドをアンロードできません。");return null;});}
 public void reconnectParticipant(TemporaryWorldManager.OwnedWorld owned,RuntimeMap map,UUID playerId){execute(()->{World world=Bukkit.getWorld(owned.worldName());var player=Bukkit.getPlayer(playerId);if(world==null)throw new IllegalStateException("ゲームワールドが利用できません。");if(player!=null&&!player.teleport(location(world,start(map.profile()))))throw new IllegalStateException("参加者をゲームワールドへ復帰できません。");return null;});}
 public void returnPendingToLobby(UUID playerId){execute(()->{var player=Bukkit.getPlayer(playerId);if(player!=null&&!player.teleport(lobby(null).getSpawnLocation()))throw new IllegalStateException("ロビーへ復帰できません。");return null;});}
 private static BlockPoint start(MapProfile profile){return profile.points().getOrDefault("combatEntry",List.of()).stream().findFirst().orElseThrow(()->new IllegalArgumentException("ゲーム開始地点がありません。"));}
 private static void validate(World world,BlockPoint point){Location value=location(world,point);if(point.y()<world.getMinHeight()||point.y()>=world.getMaxHeight())throw new IllegalArgumentException("地点がワールド高さの範囲外です。");if(!world.getWorldBorder().isInside(value))throw new IllegalArgumentException("地点がワールド境界の範囲外です。");}
 private static Location location(World world,BlockPoint p){return new Location(world,p.x()+0.5,p.y(),p.z()+0.5,p.yaw(),p.pitch());}
 private static World lobby(World excluded){return Bukkit.getWorlds().stream().filter(world->excluded==null||!world.equals(excluded)).findFirst().orElseThrow(()->new IllegalStateException("ロビーworldがありません。"));}
 private<T>T execute(java.util.concurrent.Callable<T> task){try{return executor.execute(task,Duration.ofSeconds(10));}catch(Exception e){throw new MapIoException("PAPER_RUNTIME","Paperゲームワールド操作に失敗しました。",e);}}
}
