package com.ryanjei.orushio.pve.paper;

import com.ryanjei.orushio.pve.application.GameThreadExecutor;
import com.ryanjei.orushio.pve.core.*;
import com.ryanjei.orushio.pve.domain.*;
import com.ryanjei.orushio.pve.map.*;
import net.kyori.adventure.text.Component;
import org.bukkit.*;import org.bukkit.boss.*;import org.bukkit.entity.*;import org.bukkit.persistence.PersistentDataType;import org.bukkit.plugin.Plugin;
import java.time.Duration;import java.util.*;import java.util.function.Supplier;

public final class PaperCoreGateway implements CoreGateway{
 private final GameThreadExecutor executor;private final Supplier<GameSession>sessions;private final GameRuntimeContextResolver runtimes;private final NamespacedKey markerKey,sessionKey,coreKey,typeKey,roleKey;private final Map<UUID,Map<UUID,BossBar>>bars=new HashMap<>();
 public PaperCoreGateway(Plugin plugin,GameThreadExecutor executor,Supplier<GameSession>sessions,GameRuntimeContextResolver runtimes){this.executor=executor;this.sessions=sessions;this.runtimes=runtimes;markerKey=new NamespacedKey(plugin,"core_owned");sessionKey=new NamespacedKey(plugin,"core_session");coreKey=new NamespacedKey(plugin,"core_id");typeKey=new NamespacedKey(plugin,"core_type");roleKey=new NamespacedKey(plugin,"core_role");}
 public void spawn(CoreSpawnRequest request){execute(()->{require(request.ownership().sessionId(),request.ownership().runtimeWorld());World world=requireWorld(request.ownership().runtimeWorld());Location location=location(world,request.position());Entity entity;if(request.ownership().role()==CoreEntityRole.DISPLAY){TextDisplay display=(TextDisplay)world.spawnEntity(location.clone().add(0,1.2,0),EntityType.TEXT_DISPLAY);display.text(Component.text(request.ownership().type()==CoreType.FINAL?"FINAL CORE":"CORE"));display.setBillboard(Display.Billboard.CENTER);entity=display;}else{ArmorStand hitbox=(ArmorStand)world.spawnEntity(location,EntityType.ARMOR_STAND);hitbox.setVisible(false);hitbox.setGravity(false);hitbox.setBasePlate(false);hitbox.setArms(false);entity=hitbox;}write(entity,request.ownership());return null;});}
 public Optional<CoreOwnership>ownership(UUID entityId){return execute(()->{Entity entity=Bukkit.getEntity(entityId);return entity==null?Optional.empty():read(entity);});}
 public void removeCore(UUID sessionId,UUID coreId,String world){execute(()->{require(sessionId,world);for(Entity entity:new ArrayList<>(requireWorld(world).getEntities()))read(entity).filter(o->o.sessionId().equals(sessionId)&&o.coreId().equals(coreId)).ifPresent(o->entity.remove());return null;});}
 public void openGates(UUID sessionId,String world,List<Cuboid>gates){execute(()->{require(sessionId,world);World value=requireWorld(world);for(Cuboid gate:gates){long volume=(long)(gate.maxX()-gate.minX()+1)*(gate.maxY()-gate.minY()+1)*(gate.maxZ()-gate.minZ()+1);if(volume>1_000_000)throw new IllegalArgumentException("Gate範囲が防御上限を超えます。");for(int x=gate.minX();x<=gate.maxX();x++)for(int y=gate.minY();y<=gate.maxY();y++)for(int z=gate.minZ();z<=gate.maxZ();z++)value.getBlockAt(x,y,z).setType(Material.AIR,false);}return null;});}
 public void updateUi(UUID sessionId,String world,List<Participant>participants,CoreProgressView progress){execute(()->{require(sessionId,world);World runtime=requireWorld(world);Map<UUID,BossBar>sessionBars=bars.computeIfAbsent(sessionId,id->new HashMap<>());Set<UUID>participantIds=new HashSet<>();for(Participant participant:participants){participantIds.add(participant.playerUuid());Player player=Bukkit.getPlayer(participant.playerUuid());if(player==null||!player.isOnline()||!player.getWorld().equals(runtime))continue;CoreProgressView.CoreHealth target=nearest(player,progress);String title=target==null?"Core攻略完了":(target.type()==CoreType.FINAL?"最終Core ":"通常Core ")+format(target.hp())+" / "+format(target.maxHp());BossBar bar=sessionBars.computeIfAbsent(player.getUniqueId(),id->{BossBar created=Bukkit.createBossBar(title,BarColor.RED,BarStyle.SOLID);created.addPlayer(player);return created;});bar.setTitle(title);bar.setProgress(target==null?0:Math.max(0,Math.min(1,target.hp()/target.maxHp())));bar.setVisible(target!=null);player.sendActionBar(Component.text("Core進行: "+progress.destroyedNormal()+" / "+progress.requiredNormal()));}Iterator<Map.Entry<UUID,BossBar>>iterator=sessionBars.entrySet().iterator();while(iterator.hasNext()){var entry=iterator.next();if(!participantIds.contains(entry.getKey())){entry.getValue().removeAll();iterator.remove();}}return null;});}
 public void removeUi(UUID sessionId,UUID playerId){execute(()->{Map<UUID,BossBar>sessionBars=bars.get(sessionId);if(sessionBars==null)return null;BossBar removed=sessionBars.remove(playerId);if(removed!=null)removed.removeAll();if(sessionBars.isEmpty())bars.remove(sessionId);return null;});}
 public void cleanupOwned(UUID sessionId,String world){execute(()->{require(sessionId,world);World value=Bukkit.getWorld(world);if(value!=null)for(Entity entity:new ArrayList<>(value.getEntities()))read(entity).filter(o->o.sessionId().equals(sessionId)).ifPresent(o->entity.remove());return null;});}
 public void clearUi(UUID sessionId){execute(()->{Map<UUID,BossBar>removed=bars.remove(sessionId);if(removed!=null)removed.values().forEach(BossBar::removeAll);return null;});}
 private CoreProgressView.CoreHealth nearest(Player player,CoreProgressView progress){return progress.cores().stream().filter(c->!c.destroyed()&&(c.type()==CoreType.NORMAL||progress.gateOpen())).min(Comparator.comparingDouble(c->distance(player,c.position()))).orElse(null);}
 private static double distance(Player player,BlockPoint p){Location l=player.getLocation();double x=l.getX()-(p.x()+.5),y=l.getY()-p.y(),z=l.getZ()-(p.z()+.5);return x*x+y*y+z*z;}
 private void require(UUID sessionId,String world){GameSession session=sessions.get();if(!session.sessionId().equals(sessionId))throw new IllegalStateException("Core Session ownershipが一致しません。");GameRuntimeContext context=runtimes.resolve(sessionId).orElseThrow(()->new IllegalStateException("Core Runtime ownershipがありません。"));if(!context.worldName().equals(world))throw new IllegalStateException("Core Runtime Worldが一致しません。");}
 private World requireWorld(String name){World world=Bukkit.getWorld(name);if(world==null)throw new IllegalStateException("Core Runtime Worldがありません。");return world;}
 private void write(Entity entity,CoreOwnership owner){var pdc=entity.getPersistentDataContainer();pdc.set(markerKey,PersistentDataType.BYTE,(byte)1);pdc.set(sessionKey,PersistentDataType.STRING,owner.sessionId().toString());pdc.set(coreKey,PersistentDataType.STRING,owner.coreId().toString());pdc.set(typeKey,PersistentDataType.STRING,owner.type().name());pdc.set(roleKey,PersistentDataType.STRING,owner.role().name());}
 private Optional<CoreOwnership>read(Entity entity){var pdc=entity.getPersistentDataContainer();return CoreOwnershipData.decode(pdc.get(markerKey,PersistentDataType.BYTE),pdc.get(sessionKey,PersistentDataType.STRING),pdc.get(coreKey,PersistentDataType.STRING),pdc.get(typeKey,PersistentDataType.STRING),pdc.get(roleKey,PersistentDataType.STRING),entity.getWorld().getName());}
 private static Location location(World world,BlockPoint p){return new Location(world,p.x()+.5,p.y(),p.z()+.5,p.yaw(),p.pitch());}private static String format(double value){return String.format(Locale.ROOT,"%.1f",value);}
 private<T>T execute(java.util.concurrent.Callable<T>task){try{return executor.execute(task,Duration.ofSeconds(10));}catch(Exception e){throw new IllegalStateException("Paper Core操作に失敗しました。",e);}}
}
