package com.ryanjei.orushio.pve.paper;

import com.ryanjei.orushio.pve.application.GameThreadExecutor;
import com.ryanjei.orushio.pve.domain.*;
import com.ryanjei.orushio.pve.map.*;
import com.ryanjei.orushio.pve.pve.*;
import org.bukkit.*;
import org.bukkit.entity.*;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.plugin.Plugin;
import org.bukkit.util.BoundingBox;
import java.time.Duration;
import java.util.*;
import java.util.function.Supplier;

public final class PaperPveEnemyGateway implements PveEnemyGateway {
    private final GameThreadExecutor executor;private final Supplier<GameSession>sessions;private final GameRuntimeContextResolver runtimes;private final RandomSource random;private final NamespacedKey ownedKey,sessionKey,zoneKey;
    public PaperPveEnemyGateway(Plugin plugin,GameThreadExecutor executor,Supplier<GameSession>sessions,GameRuntimeContextResolver runtimes,RandomSource random){this(executor,sessions,runtimes,random,new NamespacedKey(plugin,"pve_enemy_owned"),new NamespacedKey(plugin,"pve_enemy_session"),new NamespacedKey(plugin,"pve_enemy_zone"));}
    PaperPveEnemyGateway(GameThreadExecutor executor,Supplier<GameSession>sessions,GameRuntimeContextResolver runtimes,RandomSource random){this(executor,sessions,runtimes,random,null,null,null);}
    PaperPveEnemyGateway(GameThreadExecutor executor,Supplier<GameSession>sessions,GameRuntimeContextResolver runtimes,RandomSource random,NamespacedKey ownedKey,NamespacedKey sessionKey,NamespacedKey zoneKey){this.executor=executor;this.sessions=sessions;this.runtimes=runtimes;this.random=random;this.ownedKey=ownedKey;this.sessionKey=sessionKey;this.zoneKey=zoneKey;}
    public Optional<UUID> spawn(EnemySpawnRequest request,int maxAttempts){return execute(()->{GameSession session=requireSession(request.sessionId(),request.runtimeWorld());World world=Bukkit.getWorld(request.runtimeWorld());if(world==null)return Optional.empty();List<Player>players=session.participants().stream().map(p->Bukkit.getPlayer(p.playerUuid())).filter(Objects::nonNull).filter(Player::isOnline).filter(p->p.getWorld().equals(world)).toList();if(players.isEmpty())return Optional.empty();for(int attempt=0;attempt<maxAttempts;attempt++){Location location=candidate(world,request.region());if(!safe(world,location,request,players))continue;LivingEntity entity=(LivingEntity)world.spawnEntity(location,entityType(request.type()));try{entity.getPersistentDataContainer().set(ownedKey,PersistentDataType.BYTE,(byte)1);entity.getPersistentDataContainer().set(sessionKey,PersistentDataType.STRING,request.sessionId().toString());entity.getPersistentDataContainer().set(zoneKey,PersistentDataType.STRING,request.enemyZoneId().toString());return Optional.of(entity.getUniqueId());}catch(RuntimeException failure){entity.remove();throw failure;}}return Optional.empty();});}
    public Set<UUID> cleanupOwned(UUID sessionId,String runtimeWorld){return execute(()->{requireSessionOrRecovery(sessionId,runtimeWorld);World world=Bukkit.getWorld(runtimeWorld);if(world==null)return Set.of();Set<UUID>removed=new HashSet<>();for(Entity entity:new ArrayList<>(world.getEntities())){Optional<EnemyOwnership>ownership=read(entity);if(ownership.isPresent()&&ownership.get().sessionId().equals(sessionId)){removed.add(entity.getUniqueId());entity.remove();}}return removed;});}
    public Set<UUID> removeOwnedInside(UUID sessionId,String runtimeWorld,Cuboid region){return execute(()->{requireSession(sessionId,runtimeWorld);World world=Bukkit.getWorld(runtimeWorld);if(world==null)return Set.of();Set<UUID>removed=new HashSet<>();for(Entity entity:new ArrayList<>(world.getEntities())){Optional<EnemyOwnership>ownership=read(entity);Location l=entity.getLocation();if(ownership.isPresent()&&ownership.get().sessionId().equals(sessionId)&&in(region,l)){removed.add(entity.getUniqueId());entity.remove();}}return removed;});}
    public Optional<EnemyOwnership> ownership(UUID entityId){return execute(()->{Entity entity=Bukkit.getEntity(entityId);return entity==null?Optional.empty():read(entity);});}
    private GameSession requireSession(UUID sessionId,String world){GameSession session=sessions.get();if(session.state()!=GameState.ACTIVE||!session.sessionId().equals(sessionId))throw new IllegalStateException("PvE Session ownershipが一致しません。");GameRuntimeContext context=runtimes.resolve(sessionId).orElseThrow(()->new IllegalStateException("PvE Runtime ownershipがありません。"));if(!context.worldName().equals(world))throw new IllegalStateException("PvE Runtime Worldが一致しません。");return session;}
    private void requireSessionOrRecovery(UUID sessionId,String world){GameSession session=sessions.get();if(!session.sessionId().equals(sessionId)||session.state()!=GameState.RECOVERING)throw new IllegalStateException("PvE cleanup Sessionが一致しません。");GameRuntimeContext context=runtimes.resolve(sessionId).orElseThrow(()->new IllegalStateException("PvE cleanup Runtimeがありません。"));if(!context.worldName().equals(world))throw new IllegalStateException("PvE cleanup Worldが一致しません。");}
    private Optional<EnemyOwnership> read(Entity entity){var pdc=entity.getPersistentDataContainer();if(!pdc.has(ownedKey,PersistentDataType.BYTE))return Optional.empty();String session=pdc.get(sessionKey,PersistentDataType.STRING),zone=pdc.get(zoneKey,PersistentDataType.STRING);if(session==null||zone==null)return Optional.empty();try{return Optional.of(new EnemyOwnership(UUID.fromString(session),UUID.fromString(zone),entity.getWorld().getName()));}catch(IllegalArgumentException invalid){return Optional.empty();}}
    private Location candidate(World world,Cuboid r){int x=r.minX()+random.nextInt(r.maxX()-r.minX()+1),y=r.minY()+random.nextInt(r.maxY()-r.minY()+1),z=r.minZ()+random.nextInt(r.maxZ()-r.minZ()+1);return new Location(world,x+0.5,y,z+0.5);}
    private static boolean safe(World world,Location l,EnemySpawnRequest request,List<Player>players){boolean height=l.getBlockY()>world.getMinHeight()&&l.getBlockY()+1<world.getMaxHeight()&&world.getWorldBorder().isInside(l);if(!height)return false;var floor=world.getBlockAt(l.getBlockX(),l.getBlockY()-1,l.getBlockZ());var feet=world.getBlockAt(l.getBlockX(),l.getBlockY(),l.getBlockZ());var head=world.getBlockAt(l.getBlockX(),l.getBlockY()+1,l.getBlockZ());boolean safeFloor=floor.getType().isSolid()&&!floor.isLiquid(),liquidFree=!feet.isLiquid()&&!head.isLiquid(),space=feet.isPassable()&&head.isPassable(),collision=world.getNearbyEntities(BoundingBox.of(l,0.4,0.9,0.4)).isEmpty();double nearest=Math.sqrt(players.stream().mapToDouble(p->p.getLocation().distanceSquared(l)).min().orElse(Double.POSITIVE_INFINITY));return SpawnCandidatePolicy.accepts(true,in(request.region(),l),in(request.farmRegion(),l),safeFloor,space&&collision,liquidFree,nearest,request.minParticipantDistance(),request.maxParticipantDistance());}
    private static boolean in(Cuboid r,Location l){return l.getBlockX()>=r.minX()&&l.getBlockX()<=r.maxX()&&l.getBlockY()>=r.minY()&&l.getBlockY()<=r.maxY()&&l.getBlockZ()>=r.minZ()&&l.getBlockZ()<=r.maxZ();}
    private static EntityType entityType(EnemyType type){return switch(type){case ZOMBIE->EntityType.ZOMBIE;case SKELETON->EntityType.SKELETON;case CREEPER->EntityType.CREEPER;};}
    private<T>T execute(java.util.concurrent.Callable<T>task){try{return executor.execute(task,Duration.ofSeconds(10));}catch(Exception e){throw new IllegalStateException("Paper PvE操作に失敗しました。",e);}}
}
