package com.ryanjei.orushio.pve.paper;
import com.ryanjei.orushio.pve.application.GameThreadExecutor;import com.ryanjei.orushio.pve.domain.*;import com.ryanjei.orushio.pve.economy.*;import com.ryanjei.orushio.pve.map.*;import org.bukkit.*;import org.bukkit.enchantments.Enchantment;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import java.time.Duration;import java.util.*;import java.util.function.Supplier;
public final class PaperFarmEconomyGateway implements FarmEconomyGateway{
 private final GameThreadExecutor executor;private final Supplier<GameSession>sessions;private final GameRuntimeContextResolver runtimes;public PaperFarmEconomyGateway(GameThreadExecutor executor,Supplier<GameSession>sessions,GameRuntimeContextResolver runtimes){this.executor=executor;this.sessions=sessions;this.runtimes=runtimes;}
 public boolean respawn(UUID sessionId,String worldName,BlockPoint position,String materialName){return execute(()->{GameSession session=requireSession(sessionId);GameRuntimeContext context=runtimes.resolve(sessionId).orElseThrow(()->new IllegalStateException("Runtime ownershipを確認できません。"));if(!context.worldName().equals(worldName))throw new IllegalStateException("Runtime World ownershipが一致しません。");World world=Bukkit.getWorld(worldName);if(world==null)return false;Material material=material(materialName);var block=world.getBlockAt(position.x(),position.y(),position.z());if(block.getType()==material)return true;if(block.getType()!=Material.AIR)return false;block.setType(material,false);return true;});}
 public boolean giveItem(UUID sessionId,UUID playerId,ItemSpec spec){return execute(()->{GameSession session=requireSession(sessionId);if(!session.isParticipant(playerId))throw new IllegalStateException("Participantではありません。");var player=Bukkit.getPlayer(playerId);if(player==null||!player.isOnline())return false;ItemStack item=item(spec);PlayerInventory inventory=player.getInventory();if(capacity(inventory,item)<item.getAmount())return false;Map<Integer,ItemStack>left=inventory.addItem(item);if(!left.isEmpty())throw new IllegalStateException("商品付与を完了できませんでした。");return true;});}
 private GameSession requireSession(UUID id){GameSession session=sessions.get();if(session.state()!=GameState.ACTIVE||!session.sessionId().equals(id))throw new IllegalStateException("GameSession ownershipが一致しません。");return session;}
 private static int capacity(PlayerInventory inventory,ItemStack item){int capacity=0;for(ItemStack current:inventory.getStorageContents()){if(current==null||current.getType()==Material.AIR)capacity+=item.getMaxStackSize();else if(current.isSimilar(item))capacity+=Math.max(0,current.getMaxStackSize()-current.getAmount());}return capacity;}
 private static ItemStack item(ItemSpec spec){ItemStack item=new ItemStack(material(spec.material()),spec.amount());ItemMeta meta=item.getItemMeta();meta.setUnbreakable(spec.unbreakable());for(var entry:spec.enchantments().entrySet()){NamespacedKey key=NamespacedKey.fromString(entry.getKey());Enchantment enchantment=key==null?null:Registry.ENCHANTMENT.get(key);if(enchantment==null)throw new IllegalArgumentException("Enchantが見つかりません: "+entry.getKey());meta.addEnchant(enchantment,entry.getValue(),false);}item.setItemMeta(meta);return item;}
 private static Material material(String name){Material material=Material.matchMaterial(name);if(material==null)throw new IllegalArgumentException("Materialが見つかりません: "+name);return material;}
 private<T>T execute(java.util.concurrent.Callable<T>task){try{return executor.execute(task,Duration.ofSeconds(10));}catch(Exception e){throw new IllegalStateException("Paper Farm Economy操作に失敗しました。",e);}}
}
