package com.ryanjei.orushio.pve.paper;

import com.ryanjei.orushio.pve.application.GameThreadExecutor;
import com.ryanjei.orushio.pve.map.*;
import java.time.Duration;
import java.util.*;
import org.bukkit.*;
import org.bukkit.inventory.*;
import org.bukkit.persistence.PersistentDataType;
import org.bukkit.plugin.Plugin;

public final class PaperMapWorldGateway implements MapWorldGateway {
    public static final String TOOL_KEY="setup_tool";
    private final GameThreadExecutor executor;private final NamespacedKey key,markerKey,markerIdKey,markerTypeKey,sessionKey,mapKey,administratorKey;
    public PaperMapWorldGateway(Plugin plugin,GameThreadExecutor executor){this.executor=executor;key=new NamespacedKey(plugin,TOOL_KEY);markerKey=new NamespacedKey(plugin,"setup_marker");markerIdKey=new NamespacedKey(plugin,"setup_marker_id");markerTypeKey=new NamespacedKey(plugin,"setup_marker_type");sessionKey=new NamespacedKey(plugin,"setup_marker_session");mapKey=new NamespacedKey(plugin,"setup_marker_map");administratorKey=new NamespacedKey(plugin,"setup_marker_administrator");}
    @Override public void loadForSetup(TemporaryWorldManager.OwnedWorld owned,UUID administrator){execute(()->{var player=Bukkit.getPlayer(administrator);validateAdministrator(player!=null,player!=null&&player.isOp(),player!=null&&player.hasPermission("orushio.pve.admin"));World world=null;try{world=Bukkit.createWorld(new WorldCreator(owned.worldName()));if(world==null)throw new IllegalStateException("セットアップワールドをロードできません。");ItemStack tool=new ItemStack(Material.BLAZE_ROD);var meta=tool.getItemMeta();meta.setDisplayName("マップ設定ツール");meta.getPersistentDataContainer().set(key,PersistentDataType.BYTE,(byte)1);tool.setItemMeta(meta);player.getInventory().addItem(tool);if(!player.teleport(world.getSpawnLocation()))throw new IllegalStateException("管理者をセットアップワールドへ転送できません。");return null;}catch(RuntimeException failure){if(world!=null)try{rollbackLoadedWorld(world);}catch(RuntimeException rollback){failure.addSuppressed(rollback);}throw failure;}});}
    @Override public void unload(TemporaryWorldManager.OwnedWorld owned){execute(()->{World world=Bukkit.getWorld(owned.worldName());if(world!=null)rollbackLoadedWorld(world);return null;});}
    @Override public void teleportSetupAdministrator(TemporaryWorldManager.OwnedWorld owned,UUID administrator,BlockPoint target){execute(()->{World world=Bukkit.getWorld(owned.worldName());var player=Bukkit.getPlayer(administrator);validateTeleport(player!=null,world!=null,player!=null&&world!=null&&player.getWorld().equals(world));if(!player.isOp()||!player.hasPermission("orushio.pve.admin"))throw new SecurityException("セットアップ管理者権限が必要です。");int safeY=target.y()+1;Location location=new Location(world,target.x()+0.5,safeY,target.z()+0.5,target.yaw(),target.pitch());if(safeY<world.getMinHeight()||safeY+1>=world.getMaxHeight()||!world.getWorldBorder().isInside(location))throw new IllegalArgumentException("セットアップワールド範囲外の座標へは移動できません。");if(!world.getBlockAt(target.x(),safeY,target.z()).isPassable()||!world.getBlockAt(target.x(),safeY+1,target.z()).isPassable())throw new IllegalArgumentException("登録地点の上に安全な立ち位置がありません。");if(!player.teleport(location))throw new IllegalStateException("セットアップ管理者を登録座標へ転送できません。");return null;});}
    @Override public void completeSetup(TemporaryWorldManager.OwnedWorld owned,UUID administrator,String message){execute(()->{World world=Bukkit.getWorld(owned.worldName());var player=Bukkit.getPlayer(administrator);if(player!=null){removeOwnedTools(player.getInventory());player.sendMessage(message);}if(world!=null)rollbackLoadedWorld(world);return null;});}
    @Override public void notifySetupAdministrator(UUID administrator,String message){execute(()->{var player=Bukkit.getPlayer(administrator);if(player!=null&&player.isOnline())player.sendMessage(message);return null;});}
    @Override public void giveSetupMarkerBlock(TemporaryWorldManager.OwnedWorld owned,UUID administrator,SetupMarkerToken token){execute(()->{var player=Bukkit.getPlayer(administrator);World world=Bukkit.getWorld(owned.worldName());validateTeleport(player!=null,world!=null,player!=null&&world!=null&&player.getWorld().equals(world));Map<Integer,ItemStack>overflow=player.getInventory().addItem(markerItem(token));if(!overflow.isEmpty())throw new IllegalStateException("Inventoryに設定ブロックを追加できません。");return null;});}
    static void removeOwnedTools(PlayerInventory inventory,NamespacedKey key){SetupToolCleanup.ownedSlots(Arrays.asList(inventory.getContents()),item->isOwnedTool(item,key)).forEach(slot->inventory.setItem(slot,null));}
    private void removeOwnedTools(PlayerInventory inventory){removeOwnedTools(inventory,key);SetupToolCleanup.ownedSlots(Arrays.asList(inventory.getContents()),item->item!=null&&item.hasItemMeta()&&item.getItemMeta().getPersistentDataContainer().has(markerKey,PersistentDataType.BYTE)).forEach(slot->inventory.setItem(slot,null));}
    static boolean isOwnedTool(ItemStack item,NamespacedKey key){return item!=null&&item.hasItemMeta()&&item.getItemMeta().getPersistentDataContainer().has(key,PersistentDataType.BYTE);}
    static void validateAdministrator(boolean online,boolean op,boolean permitted){if(!online||!op||!permitted)throw new SecurityException("オンラインの許可済み管理者が必要です。");}
    static void validateTeleport(boolean online,boolean worldLoaded,boolean inSetupWorld){if(!online)throw new IllegalStateException("セットアップ管理者がオンラインではありません。");if(!worldLoaded)throw new IllegalStateException("セットアップワールドが読み込まれていません。");if(!inSetupWorld)throw new SecurityException("セットアップ管理者が対象のセットアップワールド内にいません。");}
    private static void rollbackLoadedWorld(World world){World fallback=Bukkit.getWorlds().stream().filter(w->!w.equals(world)).findFirst().orElseThrow(()->new IllegalStateException("帰還先ワールドがありません。"));for(var player:world.getPlayers())player.teleport(fallback.getSpawnLocation());if(!Bukkit.unloadWorld(world,false))throw new IllegalStateException("一時ワールドをアンロードできません。");}
    public boolean isTool(ItemStack item){return isOwnedTool(item,key);}
    public Optional<SetupMarkerToken> setupMarkerToken(ItemStack item){if(item==null||!item.hasItemMeta())return Optional.empty();var pdc=item.getItemMeta().getPersistentDataContainer();if(!pdc.has(markerKey,PersistentDataType.BYTE))return Optional.empty();try{return Optional.of(new SetupMarkerToken(SetupMarkerType.valueOf(pdc.get(markerTypeKey,PersistentDataType.STRING)),pdc.get(sessionKey,PersistentDataType.STRING),pdc.get(mapKey,PersistentDataType.STRING),UUID.fromString(pdc.get(administratorKey,PersistentDataType.STRING))));}catch(Exception invalid){return Optional.empty();}}
    ItemStack markerItem(SetupMarkerToken token){ItemStack item=new ItemStack(material(token.markerType()));var meta=item.getItemMeta();meta.setDisplayName("[OPBP] "+token.markerType().label()+" 設定ブロック");var values=markerMetadata(token);var pdc=meta.getPersistentDataContainer();pdc.set(markerKey,PersistentDataType.BYTE,(byte)1);pdc.remove(markerIdKey);pdc.set(markerTypeKey,PersistentDataType.STRING,values.get("markerType"));pdc.set(sessionKey,PersistentDataType.STRING,values.get("sessionId"));pdc.set(mapKey,PersistentDataType.STRING,values.get("mapId"));pdc.set(administratorKey,PersistentDataType.STRING,values.get("administrator"));item.setItemMeta(meta);return item;}
    static Map<String,String> markerMetadata(SetupMarkerToken token){return Map.of("markerType",token.markerType().name(),"sessionId",token.sessionId(),"mapId",token.mapId(),"administrator",token.administrator().toString());}
    static Material material(SetupMarkerType type){return Material.valueOf(materialName(type));}
    static String materialName(SetupMarkerType type){return switch(type){case NORMAL_ENEMY_SPAWN->"RED_WOOL";case NORMAL_CORE_ROOM_ENEMY_SPAWN->"ORANGE_WOOL";case FINAL_AREA_ENEMY_SPAWN->"MAGENTA_WOOL";case FINAL_CORE_ROOM_ENEMY_SPAWN->"BLACK_WOOL";case NORMAL_CORE->"YELLOW_CONCRETE";case FINAL_CORE->"GOLD_BLOCK";case ORE_RESOURCE->"LIME_WOOL";case FARM_RESOURCE->"GREEN_WOOL";case WEAPON_SHOP->"PURPLE_WOOL";case ARMOR_SHOP->"BLUE_WOOL";case RECOVERY_SHOP->"PINK_WOOL";case SPECIAL_SHOP->"CYAN_WOOL";case FARM_RESPAWN->"LIGHT_BLUE_CONCRETE";case GAME_START->"WHITE_CONCRETE";case FINAL_AREA_ENTRY->"BLUE_CONCRETE";case FINAL_AREA_DESTINATION->"EMERALD_BLOCK";case CHECKPOINT->"CYAN_CONCRETE";case FINAL_GATE->"GRAY_CONCRETE";};}
    void retainReusableMarkerBlock(org.bukkit.entity.Player player,ItemStack item){if(!replenishesInGameMode(player.getGameMode().name()))return;ItemStack replacement=item.clone();replacement.setAmount(1);player.getInventory().addItem(replacement);}
    static boolean replenishesInGameMode(String gameMode){return !"CREATIVE".equals(gameMode);}
    void cleanupOwnedTools(org.bukkit.entity.Player player){removeOwnedTools(player.getInventory());}
    private<T>T execute(java.util.concurrent.Callable<T> task){try{return executor.execute(task,Duration.ofSeconds(5));}catch(Exception e){throw new MapIoException("PAPER_WORLD","Paperワールド操作に失敗しました。",e);}}
}
