package com.ryanjei.orushio.pve.economy;
import static org.junit.jupiter.api.Assertions.*;import com.ryanjei.orushio.pve.domain.*;import com.ryanjei.orushio.pve.logging.AuditSink;import com.ryanjei.orushio.pve.map.*;import java.time.*;import java.util.*;import org.junit.jupiter.api.*;
class FarmEconomyLifecycleStepTest{
 UUID alice=UUID.randomUUID(),bob=UUID.randomUUID(),sessionId=UUID.randomUUID(),zoneMining=UUID.randomUUID(),zoneFarm=UUID.randomUUID(),shopSword=UUID.randomUUID(),shopTool=UUID.randomUUID();BlockPoint ore=new BlockPoint(1,64,1,0,0),crop=new BlockPoint(2,64,2,0,0),shopA=new BlockPoint(5,64,5,0,0),shopB=new BlockPoint(6,64,6,0,0);MapProfile profile;GameplaySettings config;FakeGateway gateway;FarmEconomyLifecycleStep economy;GameSession preparing,active;List<String>audits;
 @BeforeEach void setup(){Cuboid farm=new Cuboid(0,60,0,10,70,10),resources=new Cuboid(1,60,1,3,70,3);Map<String,List<BlockPoint>>points=new HashMap<>();points.put("farmSpawn",List.of(new BlockPoint(0,64,0,0,0)));Map<String,List<Cuboid>>areas=Map.of("farmRegion",List.of(farm),"resourceZones",List.of(resources));List<SetupMarker>markers=List.of(new SetupMarker(shopSword,SetupMarkerType.WEAPON_SHOP,shopA,true),new SetupMarker(shopTool,SetupMarkerType.SPECIAL_SHOP,shopB,true));profile=new MapProfile(new MapProfileId("map-a"),"A",false,"template",points,areas,Instant.now(),List.of(),markers);config=new GameplaySettings(List.of(new GameplaySettings.ResourceZone(zoneMining,PointCategory.MINING,"STONE",10,Duration.ofSeconds(10),resources),new GameplaySettings.ResourceZone(zoneFarm,PointCategory.FARMING,"WHEAT",3,Duration.ofSeconds(5),resources)),List.of(new GameplaySettings.Shop(shopSword,shopA,"SWORD",List.of(product(0,PointCategory.MINING,5,"WOODEN_SWORD"),product(1,PointCategory.MINING,8,"STONE_SWORD"))),new GameplaySettings.Shop(shopTool,shopB,"TOOL",List.of(product(0,PointCategory.FARMING,3,"WOODEN_HOE")))));gateway=new FakeGateway();audits=new ArrayList<>();GameRuntimeContext context=new GameRuntimeContext(sessionId,"run-a",RuntimeMap.resolve(profile));economy=step(profile,config,gateway);Instant now=Instant.now();preparing=new GameSession(sessionId,GameState.PREPARING,List.of(new Participant(alice,"A",true),new Participant(bob,"B",true)),now,"map-a",2,60,2,1,null,null,Set.of());active=new GameSession(sessionId,GameState.ACTIVE,preparing.participants(),now,"map-a",2,60,2,1,now,now.plusSeconds(3600),Set.of());economy.prepare(preparing);}
 @Test void ACTIVE本人だけがRuntime内登録資源からカテゴリ別Pointを得る(){Instant now=Instant.now();assertTrue(economy.collect(active,alice,"run-a",ore,"STONE",now));assertEquals(10,economy.balance(sessionId,alice,PointCategory.MINING));assertEquals(0,economy.balance(sessionId,alice,PointCategory.FARMING));assertEquals(0,economy.balance(sessionId,bob,PointCategory.MINING));assertTrue(economy.collect(active,bob,"run-a",crop,"WHEAT",now));assertEquals(3,economy.balance(sessionId,bob,PointCategory.FARMING));GameSession nonActive=new GameSession(sessionId,GameState.PREPARING,active.participants(),now,"map-a",2,60,2,1,null,null,Set.of());assertFalse(economy.collect(nonActive,alice,"run-a",new BlockPoint(3,64,3,0,0),"STONE",now));assertFalse(economy.collect(active,UUID.randomUUID(),"run-a",new BlockPoint(3,64,3,0,0),"STONE",now));}
 @Test void 別World_Zone外_未登録Material_Map原本は対象外(){Instant now=Instant.now();assertFalse(economy.collect(active,alice,"other",ore,"STONE",now));assertFalse(economy.collect(active,alice,"map-a-template",ore,"STONE",now));assertFalse(economy.collect(active,alice,"run-a",new BlockPoint(9,64,9,0,0),"STONE",now));assertFalse(economy.collect(active,alice,"run-a",ore,"DIAMOND_ORE",now));assertEquals(0,economy.balance(sessionId,alice,PointCategory.MINING));}
 @Test void Respawnは重複せずdueだけ一括処理しcleanup後と別Sessionでは動かない(){Instant now=Instant.now();assertTrue(economy.collect(active,alice,"run-a",ore,"STONE",now));assertFalse(economy.collect(active,alice,"run-a",ore,"STONE",now));assertEquals(1,economy.pendingRespawns(sessionId));assertEquals(0,economy.tick(active,now.plusSeconds(9)));assertEquals(1,economy.tick(active,now.plusSeconds(10)));assertEquals(List.of(ore),gateway.respawned);assertEquals(0,economy.pendingRespawns(sessionId));assertTrue(economy.collect(active,alice,"run-a",ore,"STONE",now.plusSeconds(11)));GameSession other=activeOther();assertEquals(0,economy.tick(other,now.plusSeconds(30)));economy.cleanup(active);assertEquals(0,economy.tick(active,now.plusSeconds(30)));assertEquals(0,economy.pendingRespawns(sessionId));}
 @Test void Shop正常購入は本人だけ消費して商品付与しカテゴリは独立する(){Instant now=Instant.now();economy.collect(active,alice,"run-a",ore,"STONE",now);economy.collect(active,alice,"run-a",crop,"WHEAT",now);assertEquals(FarmEconomyLifecycleStep.PurchaseResult.COMPLETED,economy.purchase(active,alice,"run-a",shopA));assertEquals(5,economy.balance(sessionId,alice,PointCategory.MINING));assertEquals(3,economy.balance(sessionId,alice,PointCategory.FARMING));assertEquals(0,economy.balance(sessionId,bob,PointCategory.MINING));assertEquals(List.of(alice),gateway.recipients);assertEquals(FarmEconomyLifecycleStep.PurchaseResult.COMPLETED,economy.purchase(active,alice,"run-a",shopB));assertEquals(0,economy.balance(sessionId,alice,PointCategory.FARMING));}
 @Test void Point不足_非Participant_別Session_Shop外を拒否する(){assertEquals(FarmEconomyLifecycleStep.PurchaseResult.INSUFFICIENT_POINTS,economy.purchase(active,alice,"run-a",shopA));assertEquals(FarmEconomyLifecycleStep.PurchaseResult.NOT_PARTICIPANT,economy.purchase(active,UUID.randomUUID(),"run-a",shopA));assertEquals(FarmEconomyLifecycleStep.PurchaseResult.WRONG_SESSION,economy.purchase(activeOther(),alice,"run-a",shopA));assertEquals(FarmEconomyLifecycleStep.PurchaseResult.IGNORED,economy.purchase(active,alice,"run-a",new BlockPoint(9,64,9,0,0)));assertTrue(gateway.recipients.isEmpty());}
 @Test void Inventory満杯または付与例外でもPointをrollbackする(){economy.collect(active,alice,"run-a",ore,"STONE",Instant.now());gateway.deliver=false;assertEquals(FarmEconomyLifecycleStep.PurchaseResult.INVENTORY_FULL,economy.purchase(active,alice,"run-a",shopA));assertEquals(10,economy.balance(sessionId,alice,PointCategory.MINING));gateway.deliver=true;gateway.fail=true;assertThrows(RuntimeException.class,()->economy.purchase(active,alice,"run-a",shopA));assertEquals(10,economy.balance(sessionId,alice,PointCategory.MINING));assertFalse(audits.contains("SHOP_PURCHASE_COMPLETED"));}
 @Test void 上位Tier解禁後は下位商品を買わず異なるカテゴリに影響しない(){economy.collect(active,alice,"run-a",ore,"STONE",Instant.now());economy.collect(active,alice,"run-a",crop,"WHEAT",Instant.now());economy.unlockTier(sessionId,"SWORD",1);assertEquals(FarmEconomyLifecycleStep.PurchaseResult.COMPLETED,economy.purchase(active,alice,"run-a",shopA));assertEquals("STONE_SWORD",gateway.items.getFirst().material());assertEquals(FarmEconomyLifecycleStep.PurchaseResult.COMPLETED,economy.purchase(active,alice,"run-a",shopB));assertThrows(IllegalStateException.class,()->economy.unlockTier(UUID.randomUUID(),"SWORD",1));}
 @Test void Core進行はカテゴリ別の設定済み最高Tierへ冪等に接続する(){economy.collect(active,alice,"run-a",ore,"STONE",Instant.now());economy.unlockTiersForCoreProgress(sessionId,1);economy.unlockTiersForCoreProgress(sessionId,1);assertEquals(FarmEconomyLifecycleStep.PurchaseResult.COMPLETED,economy.purchase(active,alice,"run-a",shopA));assertEquals("STONE_SWORD",gateway.items.getFirst().material());assertThrows(IllegalStateException.class,()->economy.unlockTiersForCoreProgress(UUID.randomUUID(),1));}
 @Test void ResourceとShopが複数でも完全対応すればprepareできる(){assertDoesNotThrow(()->step(profile,config,gateway).prepare(preparing));}
 @Test void MapSetup側のResourceまたはShop設定不足を拒否する(){GameplaySettings missingResource=new GameplaySettings(List.of(),config.shops());GameplaySettings missingShop=new GameplaySettings(config.resourceZones(),List.of(config.shops().getFirst()));assertThrows(IllegalArgumentException.class,()->step(profile,missingResource,gateway).prepare(preparing));assertThrows(IllegalArgumentException.class,()->step(profile,missingShop,gateway).prepare(preparing));}
 @Test void GameplaySettings側の余剰ResourceとShopを拒否する(){GameplaySettings extraResource=new GameplaySettings(List.of(new GameplaySettings.ResourceZone(UUID.randomUUID(),PointCategory.MINING,"STONE",1,Duration.ofSeconds(1),new Cuboid(20,60,20,21,61,21))),config.shops());GameplaySettings extraShop=new GameplaySettings(config.resourceZones(),List.of(new GameplaySettings.Shop(UUID.randomUUID(),new BlockPoint(9,64,9,0,0),"OTHER",List.of())));assertThrows(IllegalArgumentException.class,()->step(profile,extraResource,gateway).prepare(preparing));assertThrows(IllegalArgumentException.class,()->step(profile,extraShop,gateway).prepare(preparing));}
 @Test void MapSetup対象ありのempty設定を拒否し対象なしなら許容する(){assertThrows(IllegalArgumentException.class,()->step(profile,GameplaySettings.empty(),gateway).prepare(preparing));Map<String,List<BlockPoint>>points=Map.of("farmSpawn",List.of(new BlockPoint(0,64,0,0,0)));MapProfile emptyProfile=new MapProfile(new MapProfileId("map-a"),"A",false,"template",points,Map.of("farmRegion",List.of(new Cuboid(0,60,0,10,70,10))),Instant.now());assertDoesNotThrow(()->step(emptyProfile,GameplaySettings.empty(),gateway).prepare(preparing));}
 @Test void 同一Region複数Materialを許容し同一BlockShop重複を拒否する(){assertDoesNotThrow(()->step(profile,config,gateway).prepare(preparing));GameplaySettings duplicateShop=new GameplaySettings(config.resourceZones(),List.of(config.shops().getFirst(),new GameplaySettings.Shop(UUID.randomUUID(),shopA,"OTHER",List.of())));assertThrows(IllegalArgumentException.class,()->step(profile,duplicateShop,gateway).prepare(preparing));}
 @Test void 存在しないResourceMaterialをprepareで拒否する(){GameplaySettings bad=new GameplaySettings(List.of(new GameplaySettings.ResourceZone(UUID.randomUUID(),PointCategory.MINING,"THIS_IS_NOT_A_MATERIAL",1,Duration.ofSeconds(1),config.resourceZones().getFirst().region())),config.shops());assertThrows(IllegalArgumentException.class,()->step(profile,bad,gateway,material->!material.equals("THIS_IS_NOT_A_MATERIAL")).prepare(preparing));}
 private FarmEconomyLifecycleStep step(MapProfile map,GameplaySettings value,FakeGateway target){return step(map,value,target,material->Set.of("STONE","WHEAT").contains(material));}private FarmEconomyLifecycleStep step(MapProfile map,GameplaySettings value,FakeGateway target,ResourceMaterialValidator validator){return new FarmEconomyLifecycleStep(id->value,id->Optional.of(new GameRuntimeContext(sessionId,"run-a",RuntimeMap.resolve(map))),target,validator,new AuditSink(){public void record(String a,String b,String code,String d){audits.add(code);}public boolean healthy(){return true;}});}private GameplaySettings.Product product(int tier,PointCategory category,int price,String material){return new GameplaySettings.Product(tier,category,price,new ItemSpec(material,1,Map.of(),false));}private GameSession activeOther(){Instant now=Instant.now();return new GameSession(UUID.randomUUID(),GameState.ACTIVE,active.participants(),now,"map-a",2,60,2,1,now,now.plusSeconds(60),Set.of());}
 private static final class FakeGateway implements FarmEconomyGateway{boolean deliver=true,fail;final List<BlockPoint>respawned=new ArrayList<>();final List<UUID>recipients=new ArrayList<>();final List<ItemSpec>items=new ArrayList<>();public boolean respawn(UUID s,String w,BlockPoint p,String m){respawned.add(p);return true;}public boolean giveItem(UUID s,UUID p,ItemSpec i){if(fail)throw new IllegalStateException("delivery");if(!deliver)return false;recipients.add(p);items.add(i);return true;}}
 private static final class NoAudit implements AuditSink{public void record(String a,String b,String c,String d){}public boolean healthy(){return true;}}
}
