package com.ryanjei.orushio.pve.economy;
import static org.junit.jupiter.api.Assertions.*;import com.ryanjei.orushio.pve.core.*;import com.ryanjei.orushio.pve.domain.*;import com.ryanjei.orushio.pve.map.*;import java.nio.file.Path;import java.time.Instant;import java.util.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;
class MapEconomySettingsAdministrationServiceTest{
 @TempDir Path temp;MapEconomySettingsAdministrationService service;YamlCoreSettingsRepository cores;YamlGameplaySettingsRepository gameplay;MapProfile profile;
 @BeforeEach void setup(){MapProfile base=MapProfileTest.complete("map-a");Map<String,List<Cuboid>>areas=new HashMap<>(base.areas());areas.put("resourceZones",List.of(new Cuboid(0,60,0,5,70,5),new Cuboid(10,60,10,15,70,15)));profile=new MapProfile(base.mapId(),base.displayName(),base.enabled(),base.templateDirectory(),base.points(),areas,base.createdAt(),base.spawnMarkers(),base.setupMarkers());cores=new YamlCoreSettingsRepository(temp);gameplay=new YamlGameplaySettingsRepository(temp);service=new MapEconomySettingsAdministrationService(cores,gameplay,new Profiles(profile),m->Set.of("IRON_ORE","WHEAT").contains(m),GameSession::idle);}
 @Test void CoreHpを保存再読込し不正値を拒否する(){var saved=service.updateCore("map-a",100,300);assertEquals(100,saved.normalCoreHp());assertEquals(300,service.loadCore("map-a").finalCoreHp());assertThrows(IllegalArgumentException.class,()->service.updateCore("map-a",0,300));assertThrows(IllegalArgumentException.class,()->service.updateCore("map-a",Double.NaN,300));}
 @Test void 複数ResourceZoneを混同せずPointと再生成を保存する(){var initial=service.loadResources("map-a");assertEquals(2,initial.resourceZones().size());var first=initial.resourceZones().get(0);var afterFirst=service.updateResource("map-a",new MapEconomySettingsAdministrationService.ResourceUpdate(initial.revision(),first.resourceZoneId(),PointCategory.MINING,"IRON_ORE",3,15));var second=afterFirst.resourceZones().stream().filter(z->!z.configured()).findFirst().orElseThrow();var completed=service.updateResource("map-a",new MapEconomySettingsAdministrationService.ResourceUpdate(afterFirst.revision(),second.resourceZoneId(),PointCategory.FARMING,"WHEAT",7,30));assertEquals(2,completed.resourceZones().stream().filter(MapEconomySettingsAdministrationService.ResourceZoneView::configured).count());assertEquals(Set.of(3,7),completed.resourceZones().stream().map(MapEconomySettingsAdministrationService.ResourceZoneView::pointValue).collect(java.util.stream.Collectors.toSet()));assertEquals(Set.of(15L,30L),new YamlGameplaySettingsRepository(temp).load("map-a").resourceZones().stream().map(z->z.respawnDelay().toSeconds()).collect(java.util.stream.Collectors.toSet()));}
 @Test void 不正Materialと古いRevisionを拒否して元設定を維持する(){var view=service.loadResources("map-a");var zone=view.resourceZones().getFirst();assertThrows(IllegalArgumentException.class,()->service.updateResource("map-a",new MapEconomySettingsAdministrationService.ResourceUpdate(view.revision(),zone.resourceZoneId(),PointCategory.MINING,"stone",1,10)));assertTrue(gameplay.load("map-a").resourceZones().isEmpty());assertThrows(IllegalStateException.class,()->service.updateResource("map-a",new MapEconomySettingsAdministrationService.ResourceUpdate("old",zone.resourceZoneId(),PointCategory.MINING,"IRON_ORE",1,10)));}
 private record Profiles(MapProfile value)implements MapProfileRepository{public List<MapProfile>findAll(){return List.of(value);}public Optional<MapProfile>find(MapProfileId id){return value.mapId().equals(id)?Optional.of(value):Optional.empty();}public void save(MapProfile ignored){}public void delete(MapProfileId ignored){}}
}
