package com.ryanjei.orushio.pve.core;

import com.ryanjei.orushio.pve.application.GameLifecycleStep;
import com.ryanjei.orushio.pve.domain.*;
import com.ryanjei.orushio.pve.logging.AuditSink;
import com.ryanjei.orushio.pve.map.*;
import com.ryanjei.orushio.pve.pve.RandomSource;
import java.nio.charset.StandardCharsets;
import java.util.*;

public final class CoreLifecycleStep implements GameLifecycleStep{
 public enum DamageResult{IGNORED,DAMAGED,DESTROYED,FINAL_DESTROYED}
 private final CoreSettingsRepository settings;private final GameRuntimeContextResolver runtimes;private final CoreGateway gateway;private final RandomSource random;private final CoreProgressListener progress;private final AuditSink audit;private RuntimeState runtime;
 public CoreLifecycleStep(CoreSettingsRepository settings,GameRuntimeContextResolver runtimes,CoreGateway gateway,RandomSource random,CoreProgressListener progress,AuditSink audit){this.settings=settings;this.runtimes=runtimes;this.gateway=gateway;this.random=random;this.progress=progress;this.audit=audit;}
 public synchronized void prepare(GameSession session){if(runtime!=null){require(session);return;}GameRuntimeContext context=runtimes.resolve(session.sessionId()).orElseThrow(()->new IllegalStateException("Core用Runtimeがありません。"));MapProfile profile=context.map().profile();List<BlockPoint>candidates=profile.enabledSetupMarkers(SetupMarkerType.NORMAL_CORE).stream().map(SetupMarker::position).toList();if(session.requiredNormalCores()>candidates.size())throw new IllegalArgumentException("攻略必要Core数に対して有効な候補が不足しています。");BlockPoint finalPoint=profile.requireSingleEnabledMarker(SetupMarkerType.FINAL_CORE);List<BlockPoint>selected=select(candidates,session.requiredNormalCores());List<Cuboid>gates=profile.enabledSetupMarkers(SetupMarkerType.FINAL_GATE).stream().map(marker->{BlockPoint p=marker.position();return new Cuboid(p.x(),p.y(),p.z(),p.x(),p.y(),p.z());}).toList();CoreSettings config=settings.load(session.mapId());runtime=new RuntimeState(session.sessionId(),context.worldName(),session.requiredNormalCores(),gates,session.participants());for(BlockPoint point:selected)runtime.add(new CoreState(coreId(session.mapId(),CoreType.NORMAL,point),CoreType.NORMAL,point,config.normalCoreHp()));runtime.add(new CoreState(coreId(session.mapId(),CoreType.FINAL,finalPoint),CoreType.FINAL,finalPoint,config.finalCoreHp()));for(CoreState core:runtime.cores.values()){gateway.spawn(new CoreSpawnRequest(new CoreOwnership(runtime.sessionId,core.id,core.type,CoreEntityRole.DISPLAY,runtime.world),core.position,core.maxHp));gateway.spawn(new CoreSpawnRequest(new CoreOwnership(runtime.sessionId,core.id,core.type,CoreEntityRole.HITBOX,runtime.world),core.position,core.maxHp));}audit("CORE_RUNTIME_PREPARED");}
 public synchronized void preparationCommitted(GameSession session){require(session);refreshUi();}
 public synchronized void rollbackPreparation(GameSession session){clear(session);}public synchronized void cleanup(GameSession session){clear(session);}public int cleanupOrder(){return 10;}
 public synchronized void participantConnected(GameSession session,UUID playerId){if(runtime!=null&&runtime.sessionId.equals(session.sessionId())&&session.state()==GameState.ACTIVE)refreshUi();}
 public synchronized void participantDisconnected(GameSession session,UUID playerId){if(runtime!=null&&runtime.sessionId.equals(session.sessionId()))gateway.removeUi(session.sessionId(),playerId);}
 public synchronized DamageResult damage(GameSession current,UUID playerId,String world,CoreOwnership ownership,double attackDamage,boolean cooldownReady){if(runtime==null||current.state()!=GameState.ACTIVE||!runtime.sessionId.equals(current.sessionId())||!runtime.sessionId.equals(ownership.sessionId())||!runtime.world.equals(world)||!runtime.world.equals(ownership.runtimeWorld())||ownership.role()!=CoreEntityRole.HITBOX||!current.isParticipant(playerId)||!cooldownReady||!Double.isFinite(attackDamage)||attackDamage<=0)return DamageResult.IGNORED;CoreState core=runtime.cores.get(ownership.coreId());if(core==null||core.type!=ownership.type()||core.destroyed||runtime.pendingCoreId!=null&&!runtime.pendingCoreId.equals(core.id)||core.type==CoreType.FINAL&&!runtime.gateOpen)return DamageResult.IGNORED;if(core.hp>0)core.hp=Math.max(0,core.hp-attackDamage);if(core.hp>0){refreshUi();return DamageResult.DAMAGED;}runtime.pendingCoreId=core.id;return completeDestruction(core);}
 public synchronized Set<UUID>selectedNormalCoreIds(UUID sessionId){if(runtime==null||!runtime.sessionId.equals(sessionId))return Set.of();Set<UUID>ids=new LinkedHashSet<>();runtime.cores.values().stream().filter(c->c.type==CoreType.NORMAL).forEach(c->ids.add(c.id));return Set.copyOf(ids);}public synchronized boolean gateOpen(UUID sessionId){return runtime!=null&&runtime.sessionId.equals(sessionId)&&runtime.gateOpen;}
 private void clear(GameSession session){if(runtime==null)return;require(session);gateway.cleanupOwned(runtime.sessionId,runtime.world);gateway.clearUi(runtime.sessionId);runtime=null;}
 private void refreshUi(){gateway.updateUi(runtime.sessionId,runtime.world,runtime.participants,view());}
 private DamageResult completeDestruction(CoreState core){if(core.type==CoreType.NORMAL){if(!core.countApplied){runtime.destroyedNormal++;core.countApplied=true;}if(runtime.destroyedNormal==runtime.required&&!runtime.gateOpen){gateway.openGates(runtime.sessionId,runtime.world,runtime.gates);runtime.gateOpen=true;auditGateOnce();}if(!core.progressNotified){progress.normalCoreDestroyed(runtime.sessionId,runtime.destroyedNormal,runtime.required);core.progressNotified=true;}}else if(!core.progressNotified){progress.finalCoreDestroyed(runtime.sessionId);core.progressNotified=true;}if(!core.entityRemoved){gateway.removeCore(runtime.sessionId,core.id,runtime.world);core.entityRemoved=true;}core.destroyed=true;runtime.pendingCoreId=null;RuntimeException failure=null;try{refreshUi();}catch(RuntimeException current){failure=current;}try{auditCoreOnce(core,core.type==CoreType.FINAL?"FINAL_CORE_DESTROYED":"NORMAL_CORE_DESTROYED");}catch(RuntimeException current){if(failure==null)failure=current;else failure.addSuppressed(current);}if(failure!=null)throw failure;return core.type==CoreType.FINAL?DamageResult.FINAL_DESTROYED:DamageResult.DESTROYED;}
 private void auditGateOnce(){if(runtime.gateAuditAttempted)return;runtime.gateAuditAttempted=true;audit("FINAL_GATE_OPENED");}
 private void auditCoreOnce(CoreState core,String code){if(core.auditAttempted)return;core.auditAttempted=true;audit(code);}
 private CoreProgressView view(){return new CoreProgressView(runtime.destroyedNormal,runtime.required,runtime.gateOpen,runtime.cores.values().stream().map(c->new CoreProgressView.CoreHealth(c.id,c.type,c.position,c.hp,c.maxHp,c.destroyed)).toList());}
 private void require(GameSession session){if(runtime==null||!runtime.sessionId.equals(session.sessionId()))throw new IllegalStateException("別SessionのCore状態は操作できません。");}
 private List<BlockPoint>select(List<BlockPoint>source,int count){List<BlockPoint>pool=new ArrayList<>(source),result=new ArrayList<>();for(int i=0;i<count;i++)result.add(pool.remove(random.nextInt(pool.size())));return List.copyOf(result);}
 static UUID coreId(String mapId,CoreType type,BlockPoint p){return UUID.nameUUIDFromBytes((mapId+"|"+type+"|"+p.x()+","+p.y()+","+p.z()).getBytes(StandardCharsets.UTF_8));}
 private void audit(String code){audit.record(UUID.randomUUID().toString(),"SYSTEM",code,"CORE_PROGRESSION");}
 private static final class RuntimeState{final UUID sessionId;final String world;final int required;final List<Cuboid>gates;final List<Participant>participants;final Map<UUID,CoreState>cores=new LinkedHashMap<>();int destroyedNormal;boolean gateOpen,gateAuditAttempted;UUID pendingCoreId;RuntimeState(UUID id,String world,int required,List<Cuboid>gates,List<Participant>participants){sessionId=id;this.world=world;this.required=required;this.gates=List.copyOf(gates);this.participants=List.copyOf(participants);}void add(CoreState core){if(cores.put(core.id,core)!=null)throw new IllegalArgumentException("coreIdが重複しています。");}}
 private static final class CoreState{final UUID id;final CoreType type;final BlockPoint position;final double maxHp;double hp;boolean countApplied,progressNotified,entityRemoved,destroyed,auditAttempted;CoreState(UUID id,CoreType type,BlockPoint position,double hp){this.id=id;this.type=type;this.position=position;this.maxHp=hp;this.hp=hp;}}
}
