package com.ryanjei.orushio.pve.pve;

import com.ryanjei.orushio.pve.application.GameLifecycleStep;
import com.ryanjei.orushio.pve.domain.*;
import com.ryanjei.orushio.pve.logging.AuditSink;
import com.ryanjei.orushio.pve.map.*;
import java.time.Instant;
import java.util.*;
import java.util.function.Predicate;

public final class PveLifecycleStep implements GameLifecycleStep {
    static final int MAX_CANDIDATE_ATTEMPTS=16,MAX_SPAWNS_PER_TICK=256;
    private final PveSettingsRepository settings;private final GameRuntimeContextResolver runtimes;private final PveEnemyGateway gateway;private final RandomSource random;private final AuditSink audit;private final Predicate<UUID>finalAreaUnlocked;private RuntimeState runtime;
    public PveLifecycleStep(PveSettingsRepository settings,GameRuntimeContextResolver runtimes,PveEnemyGateway gateway,RandomSource random,AuditSink audit){this(settings,runtimes,gateway,random,audit,id->true);}
    public PveLifecycleStep(PveSettingsRepository settings,GameRuntimeContextResolver runtimes,PveEnemyGateway gateway,RandomSource random,AuditSink audit,Predicate<UUID>finalAreaUnlocked){this.settings=settings;this.runtimes=runtimes;this.gateway=gateway;this.random=random;this.audit=audit;this.finalAreaUnlocked=finalAreaUnlocked;}
    public synchronized void prepare(GameSession session){GameRuntimeContext context=runtimes.resolve(session.sessionId()).orElseThrow(()->new IllegalStateException("PvE用Runtimeがありません。"));PveSettings config=settings.load(session.mapId());validateConfiguration(context.map().profile(),config);if(session.participantCountAtStart()<1||session.enemyMultiplier()<=0)throw new IllegalArgumentException("PvE人数補正が不正です。");for(var zone:config.enemyZones())spawnCount(zone.baseSpawnCount(),session.enemyMultiplier(),session.participantCountAtStart());runtime=new RuntimeState(session.sessionId(),context.worldName(),session.participantCountAtStart(),session.enemyMultiplier(),config,FarmSafetyBoundary.resolve(context.map().profile(),context.worldName()),context.map().profile().areas().getOrDefault("finalRegion",List.of()).stream().findFirst().orElse(null),Instant.now());audit("PVE_RUNTIME_PREPARED");}
    public synchronized void preparationCommitted(GameSession session){require(session);if(!runtime.started){runtime.started=true;audit("PVE_RUNTIME_STARTED");}}
    public synchronized void rollbackPreparation(GameSession session){clear(session,false);}public synchronized void cleanup(GameSession session){clear(session,true);}
    public int cleanupOrder(){return 20;}
    private void clear(GameSession session,boolean entities){if(runtime==null)return;require(session);try{if(entities)gateway.cleanupOwned(runtime.sessionId,runtime.world);boolean stopped=runtime.started;runtime=null;if(stopped)audit("PVE_RUNTIME_STOPPED");}catch(RuntimeException failure){audit("PVE_CLEANUP_FAILED");throw failure;}}
    public synchronized int tick(GameSession current,Instant now){RuntimeState state=owned(current);if(state==null)return 0;state.tracked.removeAll(gateway.removeOwnedInside(state.sessionId,state.world,state.farm.region()));boolean unlocked=finalAreaUnlocked.test(state.sessionId);int available=Math.max(0,state.enemyLimit-state.tracked.size());if(available==0)return 0;List<ZoneState>zones=new ArrayList<>(state.zones.values());if(!zones.isEmpty())Collections.rotate(zones,-(state.zoneCursor++%zones.size()));int spawned=0;for(ZoneState zone:zones){if(now.isBefore(zone.nextSpawnAt))continue;zone.nextSpawnAt=now.plus(zone.config.spawnInterval());if(zone.finalArea&&!unlocked)continue;int count=Math.min(available-spawned,spawnCount(zone.config.baseSpawnCount(),state.multiplier,state.participants));for(int i=0;i<count&&spawned<MAX_SPAWNS_PER_TICK;i++){EnemyType type=select(zone.config.mobWeights());var request=new EnemySpawnRequest(state.sessionId,state.world,zone.config.enemyZoneId(),zone.config.region(),state.farm.region(),zone.finalArea?state.finalRegion:null,type,zone.config.minParticipantDistance(),zone.config.maxParticipantDistance());try{Optional<UUID> entity=gateway.spawn(request,MAX_CANDIDATE_ATTEMPTS);if(entity.isPresent()){state.tracked.add(entity.get());spawned++;}else{audit("PVE_ENEMY_SPAWN_FAILED");break;}}catch(RuntimeException failure){audit("PVE_ENEMY_SPAWN_FAILED");break;}}if(spawned>=available)break;}return spawned;}
    public synchronized void entityRemoved(UUID entityId,EnemyOwnership ownership){if(runtime==null||!runtime.sessionId.equals(ownership.sessionId())||!runtime.world.equals(ownership.runtimeWorld())||!runtime.zones.containsKey(ownership.enemyZoneId()))return;runtime.tracked.remove(entityId);}
    public synchronized boolean isCurrent(EnemyOwnership ownership){return runtime!=null&&runtime.sessionId.equals(ownership.sessionId())&&runtime.world.equals(ownership.runtimeWorld())&&runtime.zones.containsKey(ownership.enemyZoneId());}
    public synchronized boolean protectsParticipant(GameSession current,UUID playerId,String world,BlockPoint position,EnemyOwnership enemy){return current.isParticipant(playerId)&&isCurrent(enemy)&&runtime.sessionId.equals(current.sessionId())&&runtime.farm.contains(world,position);}
    public synchronized int trackedEnemies(UUID sessionId){return runtime!=null&&runtime.sessionId.equals(sessionId)?runtime.tracked.size():0;}
    public synchronized PveRuntimeView pveRuntimeView(){if(runtime==null)return PveRuntimeView.idle();return new PveRuntimeView(runtime.started,runtime.tracked.size(),runtime.enemyLimit,runtime.participants,runtime.multiplier,finalAreaUnlocked.test(runtime.sessionId));}
    static int spawnCount(int base,double multiplier,int participants){if(base<1||multiplier<=0||participants<1)throw new IllegalArgumentException("Spawn人数補正が不正です。");double value=base*multiplier*participants;if(!Double.isFinite(value)||value>MAX_SPAWNS_PER_TICK)throw new IllegalArgumentException("1 tickのSpawn数が防御上限を超えます。");return Math.max(1,(int)Math.ceil(value));}
    EnemyType select(Map<EnemyType,Integer> weights){int target=random.nextInt(weights.values().stream().mapToInt(Integer::intValue).sum());for(EnemyType type:EnemyType.values()){int weight=weights.getOrDefault(type,0);if(target<weight)return type;target-=weight;}throw new IllegalStateException("Mob Weight抽選に失敗しました。");}
    private RuntimeState owned(GameSession current){return current.state()==GameState.ACTIVE&&runtime!=null&&runtime.sessionId.equals(current.sessionId())?runtime:null;}
    private void require(GameSession session){if(runtime==null||!runtime.sessionId.equals(session.sessionId()))throw new IllegalStateException("別SessionのPvEは操作できません。");}
    public static void validateConfiguration(MapProfile profile,PveSettings config){List<Cuboid>setup=profile.areas().getOrDefault("enemyZones",List.of());for(var zone:config.enemyZones()){if(!setup.contains(zone.region()))throw new IllegalArgumentException("PvE Enemy ZoneがMap Setupと一致しません。");}for(Cuboid region:setup)if(config.enemyZones().stream().noneMatch(zone->zone.region().equals(region)))throw new IllegalArgumentException("Map Setup Enemy ZoneのPvE設定がありません。");Cuboid farm=FarmSafetyBoundary.resolve(profile,"validation").region();for(var zone:config.enemyZones())if(contains(zone.region(),farm)||contains(farm,zone.region()))throw new IllegalArgumentException("Enemy ZoneとFarmが内包関係です。");}
    private static boolean contains(Cuboid a,Cuboid b){return b.minX()>=a.minX()&&b.maxX()<=a.maxX()&&b.minY()>=a.minY()&&b.maxY()<=a.maxY()&&b.minZ()>=a.minZ()&&b.maxZ()<=a.maxZ();}
    private void audit(String code){audit.record(UUID.randomUUID().toString(),"SYSTEM",code,"PVE_RUNTIME");}
    private static final class RuntimeState{final UUID sessionId;final String world;final int participants;final double multiplier;final int enemyLimit;final FarmSafetyBoundary farm;final Cuboid finalRegion;final Map<UUID,ZoneState>zones=new LinkedHashMap<>();final Set<UUID>tracked=new HashSet<>();int zoneCursor;boolean started;RuntimeState(UUID id,String world,int participants,double multiplier,PveSettings config,FarmSafetyBoundary farm,Cuboid finalRegion,Instant now){sessionId=id;this.world=world;this.participants=participants;this.multiplier=multiplier;this.farm=farm;this.finalRegion=finalRegion;int limit=0;for(var zone:config.enemyZones()){limit=Math.addExact(limit,spawnCount(zone.baseSpawnCount(),multiplier,participants));zones.put(zone.enemyZoneId(),new ZoneState(zone,finalRegion!=null&&overlaps(zone.region(),finalRegion),now.plus(zone.spawnInterval())));}enemyLimit=Math.min(MAX_SPAWNS_PER_TICK,limit);}}
    private static boolean overlaps(Cuboid a,Cuboid b){return a.minX()<=b.maxX()&&a.maxX()>=b.minX()&&a.minY()<=b.maxY()&&a.maxY()>=b.minY()&&a.minZ()<=b.maxZ()&&a.maxZ()>=b.minZ();}
    private static final class ZoneState{final PveSettings.EnemyZone config;final boolean finalArea;Instant nextSpawnAt;ZoneState(PveSettings.EnemyZone config,boolean finalArea,Instant next){this.config=config;this.finalArea=finalArea;nextSpawnAt=next;}}
}
