package com.ryanjei.orushio.pve.pve;

import com.ryanjei.orushio.pve.application.GameLifecycleStep;
import com.ryanjei.orushio.pve.domain.*;
import com.ryanjei.orushio.pve.logging.AuditSink;
import com.ryanjei.orushio.pve.map.*;
import java.time.Instant;
import java.util.*;

public final class PveLifecycleStep implements GameLifecycleStep {
    static final int MAX_CANDIDATE_ATTEMPTS=16,MAX_SPAWNS_PER_TICK=256;
    private final PveSettingsRepository settings;private final GameRuntimeContextResolver runtimes;private final PveEnemyGateway gateway;private final RandomSource random;private final AuditSink audit;private RuntimeState runtime;
    public PveLifecycleStep(PveSettingsRepository settings,GameRuntimeContextResolver runtimes,PveEnemyGateway gateway,RandomSource random,AuditSink audit){this.settings=settings;this.runtimes=runtimes;this.gateway=gateway;this.random=random;this.audit=audit;}
    public synchronized void prepare(GameSession session){GameRuntimeContext context=runtimes.resolve(session.sessionId()).orElseThrow(()->new IllegalStateException("PvE用Runtimeがありません。"));PveSettings config=settings.load(session.mapId());validate(context.map().profile(),config);if(session.participantCountAtStart()<1||session.enemyMultiplier()<=0)throw new IllegalArgumentException("PvE人数補正が不正です。");for(var zone:config.enemyZones())spawnCount(zone.baseSpawnCount(),session.enemyMultiplier(),session.participantCountAtStart());runtime=new RuntimeState(session.sessionId(),context.worldName(),session.participantCountAtStart(),session.enemyMultiplier(),config,FarmSafetyBoundary.resolve(context.map().profile(),context.worldName()),Instant.now());audit("PVE_RUNTIME_PREPARED");}
    public synchronized void rollbackPreparation(GameSession session){clear(session,false);}public synchronized void cleanup(GameSession session){clear(session,true);}
    public int cleanupOrder(){return 20;}
    private void clear(GameSession session,boolean entities){if(runtime==null)return;if(!runtime.sessionId.equals(session.sessionId()))throw new IllegalStateException("別SessionのPvEはcleanupできません。");try{if(entities)gateway.cleanupOwned(runtime.sessionId,runtime.world);runtime=null;}catch(RuntimeException failure){audit("PVE_CLEANUP_FAILED");throw failure;}}
    public synchronized int tick(GameSession current,Instant now){RuntimeState state=owned(current);if(state==null)return 0;state.tracked.removeAll(gateway.removeOwnedInside(state.sessionId,state.world,state.farm.region()));int spawned=0;for(ZoneState zone:state.zones.values()){if(now.isBefore(zone.nextSpawnAt))continue;zone.nextSpawnAt=now.plus(zone.config.spawnInterval());int count=spawnCount(zone.config.baseSpawnCount(),state.multiplier,state.participants);for(int i=0;i<count&&spawned<MAX_SPAWNS_PER_TICK;i++){EnemyType type=select(zone.config.mobWeights());var request=new EnemySpawnRequest(state.sessionId,state.world,zone.config.enemyZoneId(),zone.config.region(),state.farm.region(),type,zone.config.minParticipantDistance(),zone.config.maxParticipantDistance());try{Optional<UUID> entity=gateway.spawn(request,MAX_CANDIDATE_ATTEMPTS);if(entity.isPresent()){state.tracked.add(entity.get());spawned++;}else{audit("PVE_ENEMY_SPAWN_FAILED");break;}}catch(RuntimeException failure){audit("PVE_ENEMY_SPAWN_FAILED");break;}}}return spawned;}
    public synchronized void entityRemoved(UUID entityId,EnemyOwnership ownership){if(runtime==null||!runtime.sessionId.equals(ownership.sessionId())||!runtime.world.equals(ownership.runtimeWorld())||!runtime.zones.containsKey(ownership.enemyZoneId()))return;runtime.tracked.remove(entityId);}
    public synchronized boolean isCurrent(EnemyOwnership ownership){return runtime!=null&&runtime.sessionId.equals(ownership.sessionId())&&runtime.world.equals(ownership.runtimeWorld())&&runtime.zones.containsKey(ownership.enemyZoneId());}
    public synchronized boolean protectsParticipant(GameSession current,UUID playerId,String world,BlockPoint position,EnemyOwnership enemy){return current.isParticipant(playerId)&&isCurrent(enemy)&&runtime.sessionId.equals(current.sessionId())&&runtime.farm.contains(world,position);}
    public synchronized int trackedEnemies(UUID sessionId){return runtime!=null&&runtime.sessionId.equals(sessionId)?runtime.tracked.size():0;}
    static int spawnCount(int base,double multiplier,int participants){if(base<1||multiplier<=0||participants<1)throw new IllegalArgumentException("Spawn人数補正が不正です。");double value=base*multiplier*participants;if(!Double.isFinite(value)||value>MAX_SPAWNS_PER_TICK)throw new IllegalArgumentException("1 tickのSpawn数が防御上限を超えます。");return Math.max(1,(int)Math.ceil(value));}
    EnemyType select(Map<EnemyType,Integer> weights){int target=random.nextInt(weights.values().stream().mapToInt(Integer::intValue).sum());for(EnemyType type:EnemyType.values()){int weight=weights.getOrDefault(type,0);if(target<weight)return type;target-=weight;}throw new IllegalStateException("Mob Weight抽選に失敗しました。");}
    private RuntimeState owned(GameSession current){return current.state()==GameState.ACTIVE&&runtime!=null&&runtime.sessionId.equals(current.sessionId())?runtime:null;}
    private static void validate(MapProfile profile,PveSettings config){List<Cuboid>setup=profile.areas().getOrDefault("enemyZones",List.of());for(var zone:config.enemyZones()){if(!setup.contains(zone.region()))throw new IllegalArgumentException("PvE Enemy ZoneがMap Setupと一致しません。");}for(Cuboid region:setup)if(config.enemyZones().stream().noneMatch(zone->zone.region().equals(region)))throw new IllegalArgumentException("Map Setup Enemy ZoneのPvE設定がありません。");Cuboid farm=FarmSafetyBoundary.resolve(profile,"validation").region();for(var zone:config.enemyZones())if(contains(zone.region(),farm)||contains(farm,zone.region()))throw new IllegalArgumentException("Enemy ZoneとFarmが内包関係です。");}
    private static boolean contains(Cuboid a,Cuboid b){return b.minX()>=a.minX()&&b.maxX()<=a.maxX()&&b.minY()>=a.minY()&&b.maxY()<=a.maxY()&&b.minZ()>=a.minZ()&&b.maxZ()<=a.maxZ();}
    private void audit(String code){audit.record(UUID.randomUUID().toString(),"SYSTEM",code,"PVE_RUNTIME");}
    private static final class RuntimeState{final UUID sessionId;final String world;final int participants;final double multiplier;final FarmSafetyBoundary farm;final Map<UUID,ZoneState>zones=new LinkedHashMap<>();final Set<UUID>tracked=new HashSet<>();RuntimeState(UUID id,String world,int participants,double multiplier,PveSettings config,FarmSafetyBoundary farm,Instant now){sessionId=id;this.world=world;this.participants=participants;this.multiplier=multiplier;this.farm=farm;for(var zone:config.enemyZones())zones.put(zone.enemyZoneId(),new ZoneState(zone,now.plus(zone.spawnInterval())));}}
    private static final class ZoneState{final PveSettings.EnemyZone config;Instant nextSpawnAt;ZoneState(PveSettings.EnemyZone config,Instant next){this.config=config;nextSpawnAt=next;}}
}
