package com.ryanjei.orushio.pve.pve;

import com.ryanjei.orushio.pve.application.ParticipantPolicy;
import com.ryanjei.orushio.pve.domain.*;
import com.ryanjei.orushio.pve.map.*;
import com.ryanjei.orushio.pve.persistence.GameLaunchSettingsRepository;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Duration;
import java.util.*;
import java.util.function.Supplier;

public final class PveSettingsAdministrationService {
    private final PveSettingsRepository settings;private final MapProfileRepository profiles;private final GameLaunchSettingsRepository launches;private final Supplier<GameSession>games;
    public PveSettingsAdministrationService(PveSettingsRepository settings,MapProfileRepository profiles,GameLaunchSettingsRepository launches,Supplier<GameSession>games){this.settings=settings;this.profiles=profiles;this.launches=launches;this.games=games;}
    public synchronized View load(String mapId){MapProfile profile=profile(mapId);PveSettings value=settings.load(mapId);PveLifecycleStep.validateConfiguration(profile,value);return view(mapId,profile,value);}
    public synchronized View update(String mapId,Update update){GameState state=games.get().state();if(state!=GameState.IDLE&&state!=GameState.RECRUITING)throw new IllegalStateException("PvE設定は待機中だけ変更できます。");MapProfile profile=profile(mapId);PveSettings current=settings.load(mapId);if(!revision(current).equals(update.revision()))throw new IllegalStateException("PvE設定が別画面で更新されています。再読込してください。");List<PveSettings.EnemyZone>zones=new ArrayList<>(current.enemyZones());int index=-1;for(int i=0;i<zones.size();i++)if(zones.get(i).enemyZoneId().equals(update.enemyZoneId())){index=i;break;}if(index<0)throw new IllegalArgumentException("指定されたEnemy Zoneは現在の設定にありません。");PveSettings.EnemyZone old=zones.get(index);EnumMap<EnemyType,Integer>weights=new EnumMap<>(EnemyType.class);weights.put(EnemyType.ZOMBIE,update.zombieWeight());weights.put(EnemyType.SKELETON,update.skeletonWeight());weights.put(EnemyType.CREEPER,update.creeperWeight());zones.set(index,new PveSettings.EnemyZone(old.enemyZoneId(),old.region(),Duration.ofSeconds(update.spawnIntervalSeconds()),update.baseSpawnCount(),weights,update.minParticipantDistance(),update.maxParticipantDistance()));PveSettings candidate=new PveSettings(zones);PveLifecycleStep.validateConfiguration(profile,candidate);double multiplier=launches.load(mapId).resolvedEnemyMultiplier();for(var zone:candidate.enemyZones())PveLifecycleStep.spawnCount(zone.baseSpawnCount(),multiplier,ParticipantPolicy.standard().maxParticipants());settings.save(mapId,candidate);PveSettings saved=settings.load(mapId);if(!saved.equals(candidate))throw new IllegalStateException("PvE設定の保存結果を確認できませんでした。");return view(mapId,profile,saved);}
    private View view(String mapId,MapProfile profile,PveSettings value){Cuboid finalRegion=profile.areas().getOrDefault("finalRegion",List.of()).stream().findFirst().orElse(null);boolean editable=games.get().state()==GameState.IDLE||games.get().state()==GameState.RECRUITING;List<ZoneView>zones=value.enemyZones().stream().map(zone->new ZoneView(zone.enemyZoneId(),zone.region(),finalRegion!=null&&contains(finalRegion,zone.region()),zone.spawnInterval().toSeconds(),zone.baseSpawnCount(),zone.mobWeights().getOrDefault(EnemyType.ZOMBIE,0),zone.mobWeights().getOrDefault(EnemyType.SKELETON,0),zone.mobWeights().getOrDefault(EnemyType.CREEPER,0),zone.minParticipantDistance(),zone.maxParticipantDistance())).toList();return new View(mapId,revision(value),editable,zones);}
    private MapProfile profile(String mapId){return profiles.find(new MapProfileId(mapId)).orElseThrow(()->new IllegalArgumentException("指定されたマップがありません。"));}
    private static boolean contains(Cuboid a,Cuboid b){return b.minX()>=a.minX()&&b.maxX()<=a.maxX()&&b.minY()>=a.minY()&&b.maxY()<=a.maxY()&&b.minZ()>=a.minZ()&&b.maxZ()<=a.maxZ();}
    private static String revision(PveSettings value){try{byte[]hash=MessageDigest.getInstance("SHA-256").digest(value.toString().getBytes(StandardCharsets.UTF_8));return HexFormat.of().formatHex(hash);}catch(Exception impossible){throw new IllegalStateException("PvE設定revisionを作成できません。",impossible);}}
    public record View(String mapId,String revision,boolean editable,List<ZoneView>enemyZones){public View{enemyZones=List.copyOf(enemyZones);}}
    public record ZoneView(UUID enemyZoneId,Cuboid region,boolean finalArea,long spawnIntervalSeconds,int baseSpawnCount,int zombieWeight,int skeletonWeight,int creeperWeight,double minParticipantDistance,double maxParticipantDistance){}
    public record Update(String revision,UUID enemyZoneId,long spawnIntervalSeconds,int baseSpawnCount,int zombieWeight,int skeletonWeight,int creeperWeight,double minParticipantDistance,double maxParticipantDistance){public Update{if(revision==null||revision.isBlank())throw new IllegalArgumentException("PvE設定revisionが必要です。");Objects.requireNonNull(enemyZoneId);if(spawnIntervalSeconds>Integer.MAX_VALUE)throw new IllegalArgumentException("spawn intervalが範囲外です。");}}
}
