package com.ryanjei.orushio.pve.http;

import com.ryanjei.orushio.pve.application.*;
import com.ryanjei.orushio.pve.domain.*;
import com.ryanjei.orushio.pve.security.AuthService;
import org.junit.jupiter.api.*;

import java.net.*;
import java.net.http.*;
import java.time.Instant;
import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

class GameLifecycleHttpServerTest {
    AdminHttpServer server; HttpClient client; String base,cookie,csrf; FakeGames games;
    @BeforeEach void start()throws Exception{games=new FakeGames();server=new AdminHttpServer(InetAddress.getByName("127.0.0.1"),0,games,new EmptyAdmin(),new AuthService(),Map::of);server.start();client=HttpClient.newHttpClient();base="http://127.0.0.1:"+server.port();String token=server.issueBootstrapToken();var response=client.send(HttpRequest.newBuilder(URI.create(base+"/auth/bootstrap")).header("X-Bootstrap-Token",token).POST(HttpRequest.BodyPublishers.noBody()).build(),HttpResponse.BodyHandlers.ofString());cookie=response.headers().firstValue("Set-Cookie").orElseThrow().split(";",2)[0];csrf=extract(response.body(),"csrfToken");}
    @AfterEach void stop(){server.close();}

    @Test void lifecycle取得は日本語状態と残り時間項目を返す()throws Exception{var response=get("/api/v1/game/lifecycle");assertEquals(200,response.statusCode());assertTrue(response.body().contains("待機中"));assertTrue(response.body().contains("remainingSeconds"));}
    @Test void runtime状態APIはJavaViewと同じkeyを返す()throws Exception{String idle=get("/api/v1/game/lifecycle").body();assertTrue(idle.contains("\"worldState\":\"未準備\""));assertTrue(idle.contains("\"mapState\":\"未準備\""));assertTrue(idle.contains("\"transferState\":\"未実行\""));games.runtime=new GameRuntimeView("準備済み","準備済み","転送完了","");String ready=get("/api/v1/game/lifecycle").body();assertTrue(ready.contains("\"worldState\":\"準備済み\""));assertTrue(ready.contains("\"mapState\":\"準備済み\""));assertTrue(ready.contains("\"transferState\":\"転送完了\""));games.runtime=new GameRuntimeView("準備失敗","読み込み失敗","未完了","ゲームワールドの準備に失敗しました。");assertTrue(get("/api/v1/game/lifecycle").body().contains("ゲームワールドの準備に失敗しました。"));}
    @Test void participantLimitはApplicationのPolicyと一致する()throws Exception{assertTrue(get("/api/v1/game/lifecycle").body().contains("\"participantLimit\":4"));games.limit=8;assertTrue(get("/api/v1/game/lifecycle").body().contains("\"participantLimit\":8"));assertTrue(get("/api/v1/status").body().contains("\"participantLimit\":8"));}
    @Test void participantMutationは認証OriginCsrfを必須にする()throws Exception{UUID id=UUID.randomUUID();String body="{\"uuid\":\""+id+"\"}";assertEquals(200,mutate("/api/v1/game/lifecycle/participants","PUT",body,csrf).statusCode());var unauth=HttpRequest.newBuilder(URI.create(base+"/api/v1/game/lifecycle/participants")).header("Origin",base).header("X-CSRF-Token",csrf).PUT(HttpRequest.BodyPublishers.ofString(body)).build();assertEquals(401,client.send(unauth,HttpResponse.BodyHandlers.ofString()).statusCode());assertEquals(403,mutate("/api/v1/game/lifecycle/participants","PUT",body,"bad").statusCode());}
    @Test void 既知endpointの誤methodは405で未知endpointは404()throws Exception{assertEquals(405,mutate("/api/v1/game/lifecycle","POST","{}",csrf).statusCode());assertEquals(404,get("/api/v1/game/lifecycle/not-found").statusCode());}
    @Test void 診断モードはlifecycleMutationを拒否する()throws Exception{try(AdminHttpServer diagnostic=new AdminHttpServer(InetAddress.getByName("127.0.0.1"),0,games,new EmptyAdmin(),new AuthService(),Map::of,new NoAudit(),true)){diagnostic.start();String b="http://127.0.0.1:"+diagnostic.port(),token=diagnostic.issueBootstrapToken();var auth=client.send(HttpRequest.newBuilder(URI.create(b+"/auth/bootstrap")).header("X-Bootstrap-Token",token).POST(HttpRequest.BodyPublishers.noBody()).build(),HttpResponse.BodyHandlers.ofString());String c=auth.headers().firstValue("Set-Cookie").orElseThrow().split(";",2)[0],xs=extract(auth.body(),"csrfToken");var request=HttpRequest.newBuilder(URI.create(b+"/api/v1/game/lifecycle/participants")).header("Cookie",c).header("Origin",b).header("X-CSRF-Token",xs).PUT(HttpRequest.BodyPublishers.ofString("{\"uuid\":\""+UUID.randomUUID()+"\"}")).build();assertEquals(503,client.send(request,HttpResponse.BodyHandlers.ofString()).statusCode());}}
    @Test void recoverable状態は復旧清掃だけ許可しHardDiagnosticは復旧も拒否する()throws Exception{java.util.concurrent.atomic.AtomicBoolean hard=new java.util.concurrent.atomic.AtomicBoolean(false),recoverable=new java.util.concurrent.atomic.AtomicBoolean(true);try(AdminHttpServer recovery=new AdminHttpServer(InetAddress.getByName("127.0.0.1"),0,games,new EmptyAdmin(),null,new AuthService(),Map::of,new NoAudit(),hard::get,recoverable::get,null,null)){recovery.start();String b="http://127.0.0.1:"+recovery.port(),token=recovery.issueBootstrapToken();var auth=client.send(HttpRequest.newBuilder(URI.create(b+"/auth/bootstrap")).header("X-Bootstrap-Token",token).POST(HttpRequest.BodyPublishers.noBody()).build(),HttpResponse.BodyHandlers.ofString());String c=auth.headers().firstValue("Set-Cookie").orElseThrow().split(";",2)[0],xs=extract(auth.body(),"csrfToken");java.util.function.BiFunction<String,String,HttpRequest.Builder> request=(path,method)->HttpRequest.newBuilder(URI.create(b+path)).header("Cookie",c).header("Origin",b).header("X-CSRF-Token",xs).method(method,HttpRequest.BodyPublishers.ofString("{}"));assertEquals(503,client.send(request.apply("/api/v1/maps/setup/start","POST").build(),HttpResponse.BodyHandlers.ofString()).statusCode());assertEquals(503,client.send(request.apply("/api/v1/game/lifecycle/participants","PUT").build(),HttpResponse.BodyHandlers.ofString()).statusCode());assertEquals(200,client.send(request.apply("/api/v1/game/lifecycle/abort","POST").header("If-Session-Id",games.session.sessionId().toString()).build(),HttpResponse.BodyHandlers.ofString()).statusCode());hard.set(true);assertEquals(503,client.send(request.apply("/api/v1/game/lifecycle/abort","POST").header("If-Session-Id",games.session.sessionId().toString()).build(),HttpResponse.BodyHandlers.ofString()).statusCode());}}
    HttpResponse<String> get(String path)throws Exception{return client.send(HttpRequest.newBuilder(URI.create(base+path)).header("Cookie",cookie).GET().build(),HttpResponse.BodyHandlers.ofString());}
    HttpResponse<String> mutate(String path,String method,String body,String csrfValue)throws Exception{return client.send(HttpRequest.newBuilder(URI.create(base+path)).header("Cookie",cookie).header("Origin",base).header("X-CSRF-Token",csrfValue).method(method,HttpRequest.BodyPublishers.ofString(body)).build(),HttpResponse.BodyHandlers.ofString());}
    static String extract(String json,String key){String marker="\""+key+"\":\"";int start=json.indexOf(marker)+marker.length();return json.substring(start,json.indexOf('"',start));}
    static final class FakeGames implements GameApplicationService{GameSession session=GameSession.idle();GameRuntimeView runtime=GameRuntimeView.idle();int limit=4;public GameSession current(){return session;}public GameRuntimeView runtimeView(){return runtime;}public int participantLimit(){return limit;}public OperationResult startRecruiting(String s){throw new UnsupportedOperationException();}public OperationResult closeRecruiting(String s){throw new UnsupportedOperationException();}public OperationResult startMapSetup(String s){throw new UnsupportedOperationException();}public void validateMapSetup(String s){}public OperationResult closeMapSetup(String s){throw new UnsupportedOperationException();}public GameSession addParticipant(UUID id){session=session.withParticipant(id,"Player");return session;}public GameSession removeParticipant(UUID id){session=session.withoutParticipant(id);return session;}public GameStartView startView(String id){return new GameStartView(id,"Map",List.of(),GameLaunchSettings.defaults(),60,2,1.0,false,List.of("参加者が必要です。"));}public GameLaunchSettings saveLaunchSettings(String id,GameLaunchSettings value){return value;}public OperationResult prepareGame(String s,String id){return result();}public OperationResult activateGame(String s,Instant now){return result();}public OperationResult abortGame(String s,String reason){return result();}private OperationResult result(){return new OperationResult("op",session.sessionId().toString(),session.state().name());}}
    static final class EmptyAdmin implements ServerAdministrationService{public List<OnlinePlayerView> onlinePlayers(){return List.of();}public boolean whitelistEnabled(){return false;}public boolean setWhitelistEnabled(boolean value){return value;}public List<WhitelistEntryView> whitelistedPlayers(){return List.of();}public WhitelistEntryView addWhitelistedPlayer(String name){throw new UnsupportedOperationException();}public void removeWhitelistedPlayer(String name){}}
    static final class NoAudit implements com.ryanjei.orushio.pve.logging.AuditSink{public void record(String a,String b,String c,String d){}public boolean healthy(){return true;}}
}
