package com.ryanjei.orushio.pve.http;
import static org.junit.jupiter.api.Assertions.*;import com.ryanjei.orushio.pve.application.*;import com.ryanjei.orushio.pve.domain.*;import com.ryanjei.orushio.pve.logging.AuditSink;import com.ryanjei.orushio.pve.map.*;import com.ryanjei.orushio.pve.persistence.ActiveSessionRepository;import com.ryanjei.orushio.pve.security.AuthService;import java.net.*;import java.net.http.*;import java.nio.file.*;import java.time.Instant;import java.util.*;import java.util.logging.*;import org.junit.jupiter.api.*;
class MapAdminHttpServerTest{
 private AdminHttpServer server;private HttpClient client;private String base,cookie,csrf;private final List<String>auditCodes=new ArrayList<>();private final List<LogRecord>logs=new ArrayList<>();private final FakeMaps maps=new FakeMaps();
 @BeforeEach void start()throws Exception{ServerAdministrationService admin=new ServerAdministrationService(){public List<OnlinePlayerView>onlinePlayers(){return List.of();}public boolean whitelistEnabled(){return false;}public boolean setWhitelistEnabled(boolean value){return value;}public List<WhitelistEntryView>whitelistedPlayers(){return List.of();}public WhitelistEntryView addWhitelistedPlayer(String name){throw new UnsupportedOperationException();}public void removeWhitelistedPlayer(String name){}};Logger logger=Logger.getAnonymousLogger();logger.setUseParentHandlers(false);logger.addHandler(new Handler(){public void publish(LogRecord record){logs.add(record);}public void flush(){}public void close(){}});server=new AdminHttpServer(InetAddress.getByName("127.0.0.1"),0,new DefaultGameApplicationService(new MemorySession()),admin,maps,new AuthService(),Map::of,new AuditSink(){public void record(String a,String b,String code,String d){auditCodes.add(code);}public boolean healthy(){return true;}},()->false,()->false,null,null,null,null,null,logger);server.start();client=HttpClient.newHttpClient();base="http://127.0.0.1:"+server.port();String token=server.issueBootstrapToken();var auth=client.send(HttpRequest.newBuilder(URI.create(base+"/auth/bootstrap")).header("X-Bootstrap-Token",token).POST(HttpRequest.BodyPublishers.noBody()).build(),HttpResponse.BodyHandlers.ofString());cookie=auth.headers().firstValue("Set-Cookie").orElseThrow().split(";",2)[0];csrf=extract(auth.body(),"csrfToken");}
 @AfterEach void stop(){server.close();}
 @Test void mapListEnableAndMarkerStyleApisWork()throws Exception{assertEquals(200,get("/api/v1/maps").statusCode());assertEquals(200,get("/setup-marker.css").statusCode());assertEquals(200,mutation("/api/v1/maps/enabled","PUT","{\"mapId\":\"map-a\",\"enabled\":true}").statusCode());assertTrue(maps.profile.enabled());}
 @Test void 廃止済み地点FieldはGenericMutationで拒否する()throws Exception{String request="{\"administrator\":\""+maps.admin+"\",\"field\":\"farmSpawn\",\"area\":false,\"index\":0}";assertEquals(400,mutation("/api/v1/maps/setup/teleport","POST",request).statusCode());assertEquals(400,mutation("/api/v1/maps/setup/entry","DELETE",request).statusCode());assertFalse(maps.teleported);assertFalse(maps.deleted);}
 @Test void markerMutationsUseProtectedApiAndAudit()throws Exception{String id=maps.marker.toString(),admin=maps.admin.toString();assertEquals(200,mutation("/api/v1/maps/setup/marker","PUT","{\"administrator\":\""+admin+"\",\"markerId\":\""+id+"\",\"enabled\":false}").statusCode());assertTrue(auditCodes.contains("SPAWN_MARKER_ENABLED_CHANGED"));assertEquals(200,mutation("/api/v1/maps/setup/marker/teleport","POST","{\"administrator\":\""+admin+"\",\"markerId\":\""+id+"\"}").statusCode());}
 @Test void mapMutationRequiresAuthentication()throws Exception{var request=HttpRequest.newBuilder(URI.create(base+"/api/v1/maps/setup/teleport")).header("Origin",base).header("X-CSRF-Token",csrf).POST(HttpRequest.BodyPublishers.ofString("{}")).build();assertEquals(401,client.send(request,HttpResponse.BodyHandlers.ofString()).statusCode());}
 @Test void zipUploadPassesExactBodyToMapService()throws Exception{byte[] zip={0x50,0x4b,3,4,1,2,3};var response=zipMutation("/api/v1/maps/import?mapId=map-a&displayName=%E3%83%9E%E3%83%83%E3%83%97A",zip);assertEquals(200,response.statusCode());assertArrayEquals(zip,maps.importedZip);}
 @Test void internalErrorLogsTraceOperationExceptionAndStackTrace()throws Exception{maps.importFailure=new RuntimeException("boom");var response=zipMutation("/api/v1/maps/import?mapId=map-a&displayName=A",new byte[]{1});assertEquals(500,response.statusCode());String trace=extract(response.body(),"traceId");assertEquals(1,logs.size());LogRecord record=logs.getFirst();assertTrue(record.getMessage().contains("traceId="+trace));assertTrue(record.getMessage().contains("operation=POST /api/v1/maps/import"));assertSame(maps.importFailure,record.getThrown());assertTrue(auditCodes.contains("INTERNAL_ERROR"));}
 private HttpResponse<String>get(String path)throws Exception{return client.send(HttpRequest.newBuilder(URI.create(base+path)).header("Cookie",cookie).GET().build(),HttpResponse.BodyHandlers.ofString());}private HttpResponse<String>mutation(String path,String method,String body)throws Exception{return client.send(HttpRequest.newBuilder(URI.create(base+path)).header("Cookie",cookie).header("Origin",base).header("X-CSRF-Token",csrf).method(method,HttpRequest.BodyPublishers.ofString(body)).build(),HttpResponse.BodyHandlers.ofString());}private HttpResponse<String>zipMutation(String path,byte[] body)throws Exception{return client.send(HttpRequest.newBuilder(URI.create(base+path)).header("Cookie",cookie).header("Origin",base).header("X-CSRF-Token",csrf).header("Content-Type","application/zip").POST(HttpRequest.BodyPublishers.ofByteArray(body)).build(),HttpResponse.BodyHandlers.ofString());}private static String extract(String json,String key){String marker="\""+key+"\":\"";int start=json.indexOf(marker)+marker.length();return json.substring(start,json.indexOf('"',start));}
 private static final class MemorySession implements ActiveSessionRepository{GameSession value;public Optional<GameSession>load(){return Optional.ofNullable(value);}public void save(GameSession value){this.value=value;}}
 private static final class FakeMaps implements MapAdministrationService{MapProfile profile=complete();final UUID admin=UUID.randomUUID(),marker=UUID.randomUUID();boolean deleted,teleported;byte[]importedZip;RuntimeException importFailure;public List<MapProfile>list(){return List.of(profile);}public Optional<String>fixedNextMapId(){return Optional.empty();}public MapProfile importZip(Path p,String i,String d){if(importFailure!=null)throw importFailure;try{importedZip=Files.readAllBytes(p);}catch(Exception e){throw new RuntimeException(e);}return profile;}public MapProfile setEnabled(String i,boolean e){profile=profile.withEnabled(e);return profile;}public void fixNext(String i){}public void delete(String i){}public SetupView startSetup(String i,UUID a,String s){return setup();}public SetupView setup(){return new SetupView(true,"map-a","A",admin.toString(),"",false,List.of(),Map.of(),Map.of());}public void selectField(UUID a,String f,boolean r){}public void recordClick(UUID a,BlockPoint p,boolean c){}public void removeSetupEntry(UUID a,String f,boolean r,int i){deleted=true;}public void teleportSetupEntry(UUID a,String f,boolean r,int i){teleported=true;}public void setSpawnMarkerEnabled(UUID a,UUID m,boolean e){}public void removeSpawnMarker(UUID a,UUID m){}public void teleportSpawnMarker(UUID a,UUID m){teleported=true;}public MapProfile saveSetup(String s){return profile;}public void discardSetup(String s){}private static MapProfile complete(){return com.ryanjei.orushio.pve.map.MapProfileTest.complete("map-a");}}
}
