package com.ryanjei.orushio.pve.http;
import static org.junit.jupiter.api.Assertions.*;import java.nio.charset.StandardCharsets;import org.junit.jupiter.api.Test;
class WebAssetsTest{
    @Test void システム画面は診断APIとescapeを使う()throws Exception{String js=resource("/web/app.js");assertTrue(js.contains("/system/diagnostics"));assertTrue(js.contains("escapeHtml"));assertTrue(js.contains("loadDiagnostics"));}
    @Test void マップ管理画面と後続画面表示を持つ()throws Exception{String html=resource("/web/index.html"),js=resource("/web/app.js");assertTrue(html.contains("data-page=\"maps-page\""));assertTrue(html.contains("ワールドZIP登録"));assertTrue(html.contains("セットアップ"));assertTrue(html.contains("後続Phase"));assertTrue(js.contains("/maps/import"));assertTrue(js.contains("/maps/setup/start"));}
    @Test void ホーム画面はOPBP名で安全な管理者解除と明示引継ぎを提供する()throws Exception{String html=resource("/web/index.html"),js=resource("/web/app.js");assertTrue(html.contains("<title>OPBP 管理</title>"));assertTrue(html.contains("ゲーム参加者"));assertTrue(html.contains("現在の参加者"));assertTrue(js.contains("data-copy-name"));assertTrue(js.contains("navigator.clipboard.writeText"));assertTrue(js.contains("administratorRevocable"));assertTrue(js.contains("OPBPから解除可能"));assertTrue(js.contains("既存OP / OPBPからは解除不可"));assertTrue(js.contains("data-adopt-administrator"));assertTrue(js.contains("OPBP管理として引き継ぎますか"));assertTrue(js.contains("data-revoke-administrator"));assertTrue(js.contains("'DELETE'"));}
    @Test void setup画面は日本語名とDraft座標と個別操作を表示する()throws Exception{String js=resource("/web/app.js");assertTrue(js.contains("編集中Draft"));assertTrue(js.contains("X:${entry.x}"));assertTrue(js.contains("① X:${entry.minX}"));assertTrue(js.contains("中央へテレポート"));assertTrue(js.contains("data-setup-entry=\"delete\""));assertTrue(js.contains("/maps/setup/teleport"));assertTrue(js.contains("/maps/setup/entry"));assertTrue(js.contains("field.label"));}
    @Test void status失敗時もplayersとwhitelistを個別処理する()throws Exception{String js=resource("/web/app.js");assertTrue(js.contains("Promise.allSettled"));assertTrue(js.contains("statusResult.status === 'fulfilled'"));assertTrue(js.contains("playersResult.status === 'fulfilled'"));assertTrue(js.contains("whitelistResult.status === 'fulfilled'"));assertTrue(js.contains("renderPlayers(playersResult.value)"));assertTrue(js.contains("renderWhitelist(whitelistResult.value)"));}
    @Test void mutation成功後の再取得失敗を区別する()throws Exception{String js=resource("/web/app.js");assertTrue(js.contains("refresh({ notifyResult: false })"));assertTrue(js.contains("ただし、最新状態を確認できていません"));assertTrue(js.contains("if (refreshed.complete)"));}
    @Test void 定期更新はsilentでglobalLoadingを使わずsetup状態に応じて操作を無効化する()throws Exception{String html=resource("/web/index.html"),js=resource("/web/app.js");assertTrue(js.contains("silent: true"));assertTrue(js.contains("if (!options.silent) setLoading(true)"));assertTrue(js.contains("button.disabled=!setup.active"));assertTrue(js.contains("$('setup-save').disabled=!setup.active"));assertTrue(html.contains("setup-field-status"));assertTrue(js.contains("field.requiredCount"));assertTrue(js.contains("field.label"));}
    private static String resource(String path)throws Exception{return new String(WebAssetsTest.class.getResourceAsStream(path).readAllBytes(),StandardCharsets.UTF_8);}
}
