package com.ryanjei.orushio.pve.application;

import com.ryanjei.orushio.pve.domain.*;
import com.ryanjei.orushio.pve.logging.AuditSink;
import com.ryanjei.orushio.pve.persistence.PendingPlayerCleanupRepository;
import java.util.*;

public final class PlayerInventoryLifecycleStep implements GameLifecycleStep {
    private final PlayerInventoryGateway gateway;private final PendingPlayerCleanupRepository pending;private final AuditSink audit;
    private UUID trackedSession;private boolean rollbackMode;private final Map<UUID,PlayerInventoryGateway.RollbackState> rollback=new LinkedHashMap<>();private final Set<UUID> initialized=new LinkedHashSet<>(),restored=new LinkedHashSet<>(),offlinePending=new LinkedHashSet<>(),cleaned=new LinkedHashSet<>();
    public PlayerInventoryLifecycleStep(PlayerInventoryGateway gateway,PendingPlayerCleanupRepository pending,AuditSink audit){this.gateway=Objects.requireNonNull(gateway);this.pending=Objects.requireNonNull(pending);this.audit=Objects.requireNonNull(audit);}
    public synchronized void prepare(GameSession session){begin(session);for(Participant participant:session.participants()){UUID player=participant.playerUuid();if(initialized.contains(player))continue;try{gateway.initializeIfOnline(player).ifPresent(state->{rollback.put(player,state);initialized.add(player);audit("PLAYER_GAME_INVENTORY_INITIALIZED");});}catch(RuntimeException failure){throw failure;}}}
    public synchronized void preparationCommitted(GameSession session){requireTracked(session);rollback.clear();}
    public synchronized void rollbackPreparation(GameSession session){rollbackMode=true;if(trackedSession==null)return;requireTracked(session);RuntimeException failure=null;List<UUID> players=new ArrayList<>(rollback.keySet());Collections.reverse(players);for(UUID player:players){try{gateway.rollback(player,rollback.get(player));rollback.remove(player);initialized.remove(player);restored.add(player);audit("PLAYER_GAME_INVENTORY_ROLLED_BACK");}catch(RuntimeException current){if(failure==null)failure=current;else failure.addSuppressed(current);}}if(rollback.isEmpty()){trackedSession=null;initialized.clear();}if(failure!=null)throw failure;}
    public synchronized void cleanup(GameSession session){if(trackedSession!=null&&!trackedSession.equals(session.sessionId()))throw new IllegalStateException("別GameSessionのInventory状態はcleanupできません。");offlinePending.clear();cleaned.clear();if(rollbackMode){rollbackPreparation(session);session.participants().stream().map(Participant::playerUuid).forEach(cleaned::add);rollbackMode=false;restored.clear();return;}for(Participant participant:session.participants()){UUID player=participant.playerUuid();PlayerInventoryGateway.CleanupResult result=gateway.returnToLobbyAndCleanup(player);PendingPlayerCleanupRepository.Entry entry=new PendingPlayerCleanupRepository.Entry(player,session.sessionId());if(result==PlayerInventoryGateway.CleanupResult.OFFLINE){pending.add(entry);offlinePending.add(player);}else{pending.remove(entry);cleaned.add(player);audit("PLAYER_GAME_INVENTORY_CLEANED");}}trackedSession=null;rollback.clear();initialized.clear();}
    public synchronized void participantConnected(GameSession session,UUID playerId){if(!session.isParticipant(playerId))return;if(session.state()==GameState.RECOVERING&&rollbackMode&&rollback.containsKey(playerId)){gateway.rollback(playerId,rollback.get(playerId));rollback.remove(playerId);initialized.remove(playerId);restored.add(playerId);audit("PLAYER_GAME_INVENTORY_ROLLED_BACK");if(rollback.isEmpty())trackedSession=null;return;}if(session.state()!=GameState.ACTIVE)return;if(trackedSession==null)trackedSession=session.sessionId();requireTracked(session);if(initialized.contains(playerId))return;gateway.initializeIfOnline(playerId).ifPresent(state->{initialized.add(playerId);audit("PLAYER_GAME_INVENTORY_INITIALIZED");});}
    public synchronized boolean pendingCleanupConnected(GameSession current,UUID playerId){if(current.isParticipant(playerId))return false;List<PendingPlayerCleanupRepository.Entry> entries=pending.findByPlayer(playerId);if(entries.isEmpty())return false;if(entries.size()!=1)throw new IllegalStateException("cleanup ownershipを一意に証明できません。");PendingPlayerCleanupRepository.Entry entry=entries.getFirst();if(gateway.returnToLobbyAndCleanup(playerId)!=PlayerInventoryGateway.CleanupResult.CLEANED)return false;pending.remove(entry);audit("PLAYER_PENDING_CLEANUP_COMPLETED");return true;}
    public synchronized Set<UUID> pendingCleanupPlayers(GameSession session){return Set.copyOf(offlinePending);}
    public synchronized Set<UUID> completedCleanupPlayers(GameSession session){return Set.copyOf(cleaned);}
    public synchronized boolean hasPendingCleanup(UUID playerId){return !pending.findByPlayer(playerId).isEmpty();}
    private void begin(GameSession session){if(trackedSession==null){trackedSession=session.sessionId();rollbackMode=false;restored.clear();}requireTracked(session);}
    private void requireTracked(GameSession session){if(!Objects.equals(trackedSession,session.sessionId()))throw new IllegalStateException("Inventory操作のGameSessionが一致しません。");}
    private void audit(String code){audit.record(UUID.randomUUID().toString(),"SYSTEM",code,"PLAYER_INVENTORY_LIFECYCLE");}
}
