package com.ryanjei.orushio.pve.pve;

import com.ryanjei.orushio.pve.domain.*;
import com.ryanjei.orushio.pve.logging.AuditSink;
import com.ryanjei.orushio.pve.map.*;
import org.junit.jupiter.api.*;
import java.time.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

class PveLifecycleStepTest {
    UUID sessionId=UUID.randomUUID(),zoneA=UUID.randomUUID(),zoneB=UUID.randomUUID(),alice=UUID.randomUUID();Cuboid farm=new Cuboid(0,60,0,10,70,10),a=new Cuboid(20,60,20,25,70,25),b=new Cuboid(30,60,30,35,70,35);MapProfile profile;PveSettings settings;FakeGateway gateway;PveLifecycleStep pve;GameSession preparing,active;
    @BeforeEach void setup(){profile=profile(List.of(a,b));settings=new PveSettings(List.of(zone(zoneA,a,1,Map.of(EnemyType.ZOMBIE,1)),zone(zoneB,b,1,Map.of(EnemyType.SKELETON,1))));gateway=new FakeGateway();preparing=session(GameState.PREPARING,4,1.25,true);active=session(GameState.ACTIVE,4,1.25,true);pve=step(profile,settings,bound->0);pve.prepare(preparing);}
    @Test void MapSetup完全対応成功と不足_余剰_empty境界(){assertDoesNotThrow(()->step(profile,settings,bound->0).prepare(preparing));assertThrows(IllegalArgumentException.class,()->step(profile,new PveSettings(List.of(settings.enemyZones().getFirst())),bound->0).prepare(preparing));var extra=new PveSettings(List.of(zone(UUID.randomUUID(),new Cuboid(40,60,40,45,70,45),1,Map.of(EnemyType.ZOMBIE,1))));assertThrows(IllegalArgumentException.class,()->step(profile,extra,bound->0).prepare(preparing));assertThrows(IllegalArgumentException.class,()->step(profile,PveSettings.empty(),bound->0).prepare(preparing));assertDoesNotThrow(()->step(profile(List.of()),PveSettings.empty(),bound->0).prepare(preparing));}
    @Test void ACTIVEだけがdueZoneをspawnし別Sessionではspawnしない(){Instant due=Instant.now().plusSeconds(10);assertEquals(0,pve.tick(preparing,due));assertEquals(0,pve.tick(sessionOther(),due));assertEquals(10,pve.tick(active,due));assertEquals(10,gateway.requests.size());assertTrue(gateway.requests.stream().allMatch(r->r.runtimeWorld().equals("run-a")&&(r.enemyZoneId().equals(zoneA)||r.enemyZoneId().equals(zoneB))));}
    @Test void spawn数はceilで開始人数を固定し切断で変わらない(){assertEquals(2,PveLifecycleStep.spawnCount(1,1.1,1));assertEquals(5,PveLifecycleStep.spawnCount(2,1.1,2));assertEquals(9,PveLifecycleStep.spawnCount(2,1.1,4));GameSession disconnected=session(GameState.ACTIVE,4,1.25,false);assertEquals(10,pve.tick(disconnected,Instant.now().plusSeconds(10)));}
    @Test void Session敵上限到達で停止し死亡後にZoneを分散して再spawnできる(){assertEquals(10,pve.tick(active,Instant.now().plusSeconds(10)));assertEquals(10,pve.pveRuntimeView().enemyLimit());assertEquals(0,pve.tick(active,Instant.now().plusSeconds(20)));UUID dead=gateway.spawned.getFirst();pve.entityRemoved(dead,new EnemyOwnership(sessionId,zoneA,"run-a"));assertEquals(1,pve.tick(active,Instant.now().plusSeconds(30)));assertEquals(zoneB,gateway.requests.getLast().enemyZoneId());assertEquals(10,pve.trackedEnemies(sessionId));}
    @Test void 人数別上限と難易度表示は開始時値へ固定される(){for(int count=1;count<=4;count++){PveLifecycleStep value=step(profile,settings,bound->0);GameSession start=session(GameState.PREPARING,count,1.0,true);value.prepare(start);value.preparationCommitted(session(GameState.ACTIVE,count,1.0,true));assertEquals(count*2,value.pveRuntimeView().enemyLimit());assertEquals(count,value.pveRuntimeView().participantCount());assertEquals(1.0,value.pveRuntimeView().difficultyMultiplier());}}
    @Test void FinalAreaは解禁前spawnせず解禁後はParticipant範囲をGatewayへ渡す(){Cuboid finalRegion=new Cuboid(30,60,30,40,75,40);MapProfile map=withInitial(new MapProfile(profile.mapId(),profile.displayName(),false,profile.templateDirectory(),profile.points(),Map.of("farmRegion",List.of(farm),"enemyZones",List.of(a,b),"finalRegion",List.of(finalRegion)),profile.createdAt()));boolean[]unlocked={false};PveLifecycleStep value=new PveLifecycleStep(id->settings,id->Optional.of(new GameRuntimeContext(sessionId,"run-a",RuntimeMap.resolve(map))),gateway,bound->0,new NoAudit(),id->unlocked[0]);value.prepare(preparing);assertEquals(5,value.tick(active,Instant.now().plusSeconds(10)));assertTrue(gateway.requests.stream().allMatch(r->r.enemyZoneId().equals(zoneA)&&r.participantRegion()==null));value.cleanup(session(GameState.RECOVERING,4,1.25,false));gateway.requests.clear();value.prepare(preparing);unlocked[0]=true;assertEquals(10,value.tick(active,Instant.now().plusSeconds(10)));assertTrue(gateway.requests.stream().filter(r->r.enemyZoneId().equals(zoneB)).allMatch(r->finalRegion.equals(r.participantRegion())));}
    @Test void FinalRegion部分交差と一Block境界またぎはprepare前Validationで拒否する(){Cuboid finalRegion=new Cuboid(30,60,30,40,75,40);for(Cuboid invalid:List.of(new Cuboid(25,60,25,35,70,35),new Cuboid(20,60,20,30,70,30))){MapProfile map=new MapProfile(profile.mapId(),profile.displayName(),false,profile.templateDirectory(),profile.points(),Map.of("farmRegion",List.of(farm),"enemyZones",List.of(invalid),"finalRegion",List.of(finalRegion)),profile.createdAt());PveSettings value=new PveSettings(List.of(zone(UUID.randomUUID(),invalid,1,Map.of(EnemyType.ZOMBIE,1))));assertThrows(IllegalArgumentException.class,()->PveLifecycleStep.validateConfiguration(map,value));assertThrows(IllegalArgumentException.class,()->step(map,value,bound->0).prepare(preparing));}}
    @Test void Runtime開始終了Auditは各一度だけでcleanupは冪等(){List<String>codes=new ArrayList<>();AuditSink sink=new AuditSink(){public void record(String a,String b,String c,String d){codes.add(c);}public boolean healthy(){return true;}};PveLifecycleStep value=new PveLifecycleStep(id->settings,id->Optional.of(new GameRuntimeContext(sessionId,"run-a",RuntimeMap.resolve(profile))),gateway,bound->0,sink);value.prepare(preparing);value.preparationCommitted(active);value.preparationCommitted(active);GameSession recovering=session(GameState.RECOVERING,4,1.25,false);value.cleanup(recovering);value.cleanup(recovering);assertEquals(1,codes.stream().filter("PVE_RUNTIME_STARTED"::equals).count());assertEquals(1,codes.stream().filter("PVE_RUNTIME_STOPPED"::equals).count());}
    @Test void 一tick防御上限を超える設定組合せはprepareで拒否する(){PveSettings huge=new PveSettings(List.of(zone(zoneA,a,64,Map.of(EnemyType.ZOMBIE,1)),zone(zoneB,b,64,Map.of(EnemyType.ZOMBIE,1))));assertThrows(IllegalArgumentException.class,()->step(profile,huge,bound->0).prepare(session(GameState.PREPARING,4,100,true)));}
    @Test void Weight単独と複数境界で0Weightを選ばない(){assertEquals(EnemyType.ZOMBIE,step(profile,settings,bound->0).select(Map.of(EnemyType.ZOMBIE,1)));assertEquals(EnemyType.SKELETON,step(profile,settings,bound->0).select(Map.of(EnemyType.ZOMBIE,0,EnemyType.SKELETON,1)));assertEquals(EnemyType.CREEPER,step(profile,settings,bound->2).select(Map.of(EnemyType.ZOMBIE,1,EnemyType.SKELETON,1,EnemyType.CREEPER,1)));}
    @Test void candidateなしは周期をskipし探索上限をGatewayへ渡す(){gateway.spawn=false;assertEquals(0,pve.tick(active,Instant.now().plusSeconds(10)));assertEquals(2,gateway.requests.size());assertTrue(gateway.attempts.stream().allMatch(value->value==16));}
    @Test void spawn追跡と死亡解除はownership一致時だけ(){pve.tick(active,Instant.now().plusSeconds(10));assertEquals(10,pve.trackedEnemies(sessionId));UUID entity=gateway.spawned.getFirst();pve.entityRemoved(entity,new EnemyOwnership(sessionId,zoneA,"run-a"));assertEquals(9,pve.trackedEnemies(sessionId));pve.entityRemoved(gateway.spawned.getFirst(),new EnemyOwnership(UUID.randomUUID(),zoneA,"run-a"));assertEquals(9,pve.trackedEnemies(sessionId));}
    @Test void cleanupはCurrentSession所有Gatewayだけを呼びRuntimeを冪等破棄する(){pve.tick(active,Instant.now().plusSeconds(10));GameSession recovering=session(GameState.RECOVERING,4,1.25,false);pve.cleanup(recovering);assertEquals(List.of(sessionId),gateway.cleaned);assertEquals(0,pve.trackedEnemies(sessionId));assertDoesNotThrow(()->pve.cleanup(recovering));}
    @Test void Farm侵入Ownedだけを追跡解除し上限まで補充する(){pve.tick(active,Instant.now().plusSeconds(10));gateway.inside.add(gateway.spawned.getFirst());pve.tick(active,Instant.now().plusSeconds(20));assertTrue(gateway.inside.isEmpty());assertEquals(10,pve.trackedEnemies(sessionId));}
    @Test void Farm内ParticipantだけをCurrentOwnedEnemyから保護する(){EnemyOwnership current=new EnemyOwnership(sessionId,zoneA,"run-a");assertTrue(pve.protectsParticipant(active,alice,"run-a",new BlockPoint(1,64,1,0,0),current));assertFalse(pve.protectsParticipant(active,alice,"run-a",new BlockPoint(21,64,21,0,0),current));assertFalse(pve.protectsParticipant(active,UUID.randomUUID(),"run-a",new BlockPoint(1,64,1,0,0),current));}
    @Test void ownershipはSession_Zone_RuntimeWorld完全一致だけをCurrent扱いする(){assertTrue(pve.isCurrent(new EnemyOwnership(sessionId,zoneA,"run-a")));assertFalse(pve.isCurrent(new EnemyOwnership(UUID.randomUUID(),zoneA,"run-a")));assertFalse(pve.isCurrent(new EnemyOwnership(sessionId,UUID.randomUUID(),"run-a")));assertFalse(pve.isCurrent(new EnemyOwnership(sessionId,zoneA,"other")));}
    private PveLifecycleStep step(MapProfile map,PveSettings value,RandomSource random){MapProfile runtimeMap=withInitial(map);return new PveLifecycleStep(id->value,id->Optional.of(new GameRuntimeContext(sessionId,"run-a",RuntimeMap.resolve(runtimeMap))),gateway==null?new FakeGateway():gateway,random,new NoAudit());}
    private PveSettings.EnemyZone zone(UUID id,Cuboid region,int base,Map<EnemyType,Integer>weights){return new PveSettings.EnemyZone(id,region,Duration.ofSeconds(1),base,weights,2,30);}
    private MapProfile profile(List<Cuboid>zones){return withInitial(new MapProfile(new MapProfileId("map-a"),"A",false,"template",Map.of(),zones.isEmpty()?Map.of("farmRegion",List.of(farm)):Map.of("farmRegion",List.of(farm),"enemyZones",zones),Instant.now()));}
    private static MapProfile withInitial(MapProfile map){if(map.enabledSetupMarkers(SetupMarkerType.INITIAL_RESPAWN).size()==1)return map;SetupMarker marker=new SetupMarker(UUID.randomUUID(),SetupMarkerType.INITIAL_RESPAWN,new BlockPoint(1,64,1,0,0),true);return new MapProfile(map.mapId(),map.displayName(),map.enabled(),map.templateDirectory(),map.points(),map.areas(),map.createdAt(),map.spawnMarkers(),List.of(marker));}
    private GameSession session(GameState state,int count,double multiplier,boolean connected){Instant now=Instant.now();List<Participant>participants=new ArrayList<>();participants.add(new Participant(alice,"A",connected));for(int i=1;i<count;i++)participants.add(new Participant(UUID.randomUUID(),"P"+i,connected));return new GameSession(sessionId,state,participants,now,"map-a",count,60,2,multiplier,state==GameState.ACTIVE?now:null,state==GameState.ACTIVE?now.plusSeconds(3600):null,Set.of());}
    private GameSession sessionOther(){Instant now=Instant.now();return new GameSession(UUID.randomUUID(),GameState.ACTIVE,active.participants(),now,"map-a",4,60,2,1.25,now,now.plusSeconds(60),Set.of());}
    private static final class FakeGateway implements PveEnemyGateway{boolean spawn=true;final List<EnemySpawnRequest>requests=new ArrayList<>();final List<Integer>attempts=new ArrayList<>();final List<UUID>spawned=new ArrayList<>(),inside=new ArrayList<>();final List<UUID>cleaned=new ArrayList<>();public Optional<UUID>spawn(EnemySpawnRequest r,int a){requests.add(r);attempts.add(a);if(!spawn)return Optional.empty();UUID id=UUID.randomUUID();spawned.add(id);return Optional.of(id);}public Set<UUID>cleanupOwned(UUID s,String w){cleaned.add(s);return Set.copyOf(spawned);}public Set<UUID>removeOwnedInside(UUID s,String w,Cuboid r){Set<UUID>result=Set.copyOf(inside);inside.clear();return result;}public Optional<EnemyOwnership>ownership(UUID id){return Optional.empty();}}
    private static final class NoAudit implements AuditSink{public void record(String a,String b,String c,String d){}public boolean healthy(){return true;}}
}
