package com.ryanjei.orushio.pve.economy;
import com.ryanjei.orushio.pve.application.GameLifecycleStep;import com.ryanjei.orushio.pve.domain.*;import com.ryanjei.orushio.pve.logging.AuditSink;import com.ryanjei.orushio.pve.map.*;import java.time.Instant;import java.util.*;
public final class FarmEconomyLifecycleStep implements GameLifecycleStep{
 public enum PurchaseResult{IGNORED,COMPLETED,NOT_PARTICIPANT,WRONG_SESSION,TIER_UNAVAILABLE,INSUFFICIENT_POINTS,INVENTORY_FULL}
 private final GameplaySettingsRepository settings;private final GameRuntimeContextResolver runtimes;private final FarmEconomyGateway gateway;private final ResourceMaterialValidator materials;private final AuditSink audit;private RuntimeState runtime;
 public FarmEconomyLifecycleStep(GameplaySettingsRepository settings,GameRuntimeContextResolver runtimes,FarmEconomyGateway gateway,ResourceMaterialValidator materials,AuditSink audit){this.settings=settings;this.runtimes=runtimes;this.gateway=gateway;this.materials=materials;this.audit=audit;}
 public synchronized void prepare(GameSession session){GameRuntimeContext context=runtimes.resolve(session.sessionId()).orElseThrow(()->new IllegalStateException("Farm Economy用Runtimeがありません。"));GameplaySettings config=settings.load(session.mapId());validateConfiguration(context.map().profile(),config,materials);runtime=new RuntimeState(session.sessionId(),context.worldName(),context.map().profile(),config);}
 public synchronized void rollbackPreparation(GameSession session){cleanup(session);}public synchronized void cleanup(GameSession session){if(runtime==null)return;if(!runtime.sessionId.equals(session.sessionId()))throw new IllegalStateException("別SessionのFarm Economyはcleanupできません。");runtime=null;}
 public synchronized boolean collect(GameSession current,UUID playerId,String world,BlockPoint position,String material,Instant now){RuntimeState state=active(current,playerId,world);if(state==null)return false;GameplaySettings.ResourceZone zone=state.config.resourceZones().stream().filter(z->contains(z.region(),position)&&z.material().equals(material)).findFirst().orElse(null);if(zone==null||!state.farm.contains(world,position))return false;BlockKey key=new BlockKey(world,position.x(),position.y(),position.z());if(state.respawns.containsKey(key))return false;state.add(playerId,zone.category(),zone.pointValue());state.respawns.put(key,new RespawnEntry(state.sessionId,state.world,zone.resourceZoneId(),position,material,now.plus(zone.respawnDelay())));return true;}
 public synchronized int tick(GameSession current,Instant now){if(runtime==null||current.state()!=GameState.ACTIVE||!runtime.sessionId.equals(current.sessionId()))return 0;int count=0;Iterator<Map.Entry<BlockKey,RespawnEntry>>iterator=runtime.respawns.entrySet().iterator();while(iterator.hasNext()){RespawnEntry entry=iterator.next().getValue();if(now.isBefore(entry.respawnAt))continue;if(!entry.sessionId.equals(current.sessionId())||!entry.world.equals(runtime.world)){iterator.remove();continue;}if(gateway.respawn(entry.sessionId,entry.world,entry.position,entry.material)){iterator.remove();count++;}}return count;}
 public synchronized PurchaseResult purchase(GameSession current,UUID playerId,String world,BlockPoint position){RuntimeState state=owned(current,world);if(state==null)return PurchaseResult.WRONG_SESSION;if(!current.isParticipant(playerId))return PurchaseResult.NOT_PARTICIPANT;GameplaySettings.Shop shop=state.config.shops().stream().filter(s->sameBlock(s.location(),position)).findFirst().orElse(null);if(shop==null)return PurchaseResult.IGNORED;int tier=state.tiers.getOrDefault(shop.category(),0);GameplaySettings.Product product=shop.products().stream().filter(p->p.tier()==tier).findFirst().orElse(null);if(product==null){rejected();return PurchaseResult.TIER_UNAVAILABLE;}int balance=state.balance(playerId,product.pointCategory());if(balance<product.price()){rejected();return PurchaseResult.INSUFFICIENT_POINTS;}state.add(playerId,product.pointCategory(),-product.price());boolean delivered;try{delivered=gateway.giveItem(state.sessionId,playerId,product.item());}catch(RuntimeException failure){state.add(playerId,product.pointCategory(),product.price());throw failure;}if(!delivered){state.add(playerId,product.pointCategory(),product.price());rejected();return PurchaseResult.INVENTORY_FULL;}audit("SHOP_PURCHASE_COMPLETED");return PurchaseResult.COMPLETED;}
 public synchronized void unlockTier(UUID sessionId,String category,int tier){if(runtime==null||!runtime.sessionId.equals(sessionId))throw new IllegalStateException("別SessionのTierは変更できません。");if(tier<0)throw new IllegalArgumentException("Tierが範囲外です。");if(runtime.config.shops().stream().noneMatch(s->s.category().equals(category)))throw new IllegalArgumentException("Shopカテゴリがありません。");runtime.tiers.put(category,tier);}
 public synchronized void unlockTiersForCoreProgress(UUID sessionId,int destroyedNormalCores){if(runtime==null||!runtime.sessionId.equals(sessionId))throw new IllegalStateException("別SessionのTierは変更できません。");if(destroyedNormalCores<0)throw new IllegalArgumentException("Core進行が範囲外です。");for(var shop:runtime.config.shops()){int tier=shop.products().stream().mapToInt(GameplaySettings.Product::tier).filter(value->value<=destroyedNormalCores).max().orElse(0);runtime.tiers.merge(shop.category(),tier,Math::max);}}
 public synchronized int balance(UUID sessionId,UUID playerId,PointCategory category){if(runtime==null||!runtime.sessionId.equals(sessionId))return 0;return runtime.balance(playerId,category);}public synchronized int pendingRespawns(UUID sessionId){return runtime!=null&&runtime.sessionId.equals(sessionId)?runtime.respawns.size():0;}
 private RuntimeState active(GameSession current,UUID player,String world){if(!current.isParticipant(player))return null;return owned(current,world);}private RuntimeState owned(GameSession current,String world){return current.state()==GameState.ACTIVE&&runtime!=null&&runtime.sessionId.equals(current.sessionId())&&runtime.world.equals(world)?runtime:null;}
 private void rejected(){audit("SHOP_PURCHASE_REJECTED");}private void audit(String code){audit.record(UUID.randomUUID().toString(),"SYSTEM",code,"FARM_ECONOMY");}
 public static void validateConfiguration(MapProfile profile,GameplaySettings settings,ResourceMaterialValidator materials){List<Cuboid>registeredZones=profile.areas().getOrDefault("resourceZones",List.of());List<SetupMarker>registeredShops=profile.enabledSetupMarkers().stream().filter(marker->marker.markerType().category()==SetupMarkerType.Category.SHOP).toList();FarmSafetyBoundary farm=FarmSafetyBoundary.resolve(profile,"validation");for(var zone:settings.resourceZones()){if(!registeredZones.contains(zone.region()))throw new IllegalArgumentException("Resource ZoneがMap Setupと一致しません。");if(!contains(farm.region(),zone.region()))throw new IllegalArgumentException("Resource ZoneがFarm外です。");if(!materials.isValidBlockMaterial(zone.material()))throw new IllegalArgumentException("Resource Materialが存在しないBlockです: "+zone.material());}for(Cuboid registered:registeredZones)if(settings.resourceZones().stream().noneMatch(zone->zone.region().equals(registered)))throw new IllegalArgumentException("Map Setup Resource ZoneのGameplaySettingsがありません。");Set<String>shopBlocks=new HashSet<>();for(var shop:settings.shops()){SetupMarker marker=registeredShops.stream().filter(value->value.markerId().equals(shop.shopId())&&sameBlock(value.position(),shop.location())).findFirst().orElseThrow(()->new IllegalArgumentException("Shop markerIdまたは地点がMap Setupと一致しません。"));if(!shopBlocks.add(blockKey(marker.position())))throw new IllegalArgumentException("同一BlockにShopが重複しています。");if(!contains(farm.region(),shop.location()))throw new IllegalArgumentException("Shop地点がFarm外です。");}for(SetupMarker registered:registeredShops)if(settings.shops().stream().noneMatch(shop->shop.shopId().equals(registered.markerId())&&sameBlock(shop.location(),registered.position())))throw new IllegalArgumentException("Map Setup Shop MarkerのGameplaySettingsがありません。");}
 private static boolean contains(Cuboid outer,Cuboid inner){return inner.minX()>=outer.minX()&&inner.maxX()<=outer.maxX()&&inner.minY()>=outer.minY()&&inner.maxY()<=outer.maxY()&&inner.minZ()>=outer.minZ()&&inner.maxZ()<=outer.maxZ();}private static boolean contains(Cuboid area,BlockPoint p){return p.x()>=area.minX()&&p.x()<=area.maxX()&&p.y()>=area.minY()&&p.y()<=area.maxY()&&p.z()>=area.minZ()&&p.z()<=area.maxZ();}private static boolean sameBlock(BlockPoint a,BlockPoint b){return a.x()==b.x()&&a.y()==b.y()&&a.z()==b.z();}private static String blockKey(BlockPoint p){return p.x()+":"+p.y()+":"+p.z();}
 private record BlockKey(String world,int x,int y,int z){}private record RespawnEntry(UUID sessionId,String world,UUID zoneId,BlockPoint position,String material,Instant respawnAt){}
 private static final class RuntimeState{final UUID sessionId;final String world;final GameplaySettings config;final FarmSafetyBoundary farm;final Map<UUID,EnumMap<PointCategory,Integer>>points=new HashMap<>();final Map<BlockKey,RespawnEntry>respawns=new LinkedHashMap<>();final Map<String,Integer>tiers=new HashMap<>();RuntimeState(UUID id,String world,MapProfile profile,GameplaySettings config){sessionId=id;this.world=world;this.config=config;farm=FarmSafetyBoundary.resolve(profile,world);for(var shop:config.shops())tiers.putIfAbsent(shop.category(),0);}int balance(UUID player,PointCategory category){return points.getOrDefault(player,new EnumMap<>(PointCategory.class)).getOrDefault(category,0);}void add(UUID player,PointCategory category,int amount){EnumMap<PointCategory,Integer>balances=points.computeIfAbsent(player,key->new EnumMap<>(PointCategory.class));int next=Math.addExact(balances.getOrDefault(category,0),amount);if(next<0)throw new IllegalStateException("Point残高が不足しています。");balances.put(category,next);}}
}
