package com.ryanjei.orushio.pve.economy;
import com.ryanjei.orushio.pve.map.*;import java.time.Duration;import java.util.*;
public record GameplaySettings(List<ResourceZone> resourceZones,List<Shop> shops){
 public GameplaySettings{resourceZones=List.copyOf(resourceZones==null?List.of():resourceZones);shops=List.copyOf(shops==null?List.of():shops);unique(resourceZones.stream().map(ResourceZone::resourceZoneId).toList(),"resourceZoneId");unique(shops.stream().map(Shop::shopId).toList(),"shopId");}
 public static GameplaySettings empty(){return new GameplaySettings(List.of(),List.of());}
 private static void unique(List<UUID>ids,String label){if(new HashSet<>(ids).size()!=ids.size())throw new IllegalArgumentException(label+"が重複しています。");}
 public record ResourceZone(UUID resourceZoneId,PointCategory category,String material,int pointValue,Duration respawnDelay,Cuboid region){public ResourceZone{Objects.requireNonNull(resourceZoneId);Objects.requireNonNull(category);if(material==null||material.isBlank())throw new IllegalArgumentException("資源Materialが必要です。");if(pointValue<1)throw new IllegalArgumentException("Point値が範囲外です。");if(respawnDelay==null||respawnDelay.isNegative()||respawnDelay.isZero())throw new IllegalArgumentException("再生成時間が範囲外です。");Objects.requireNonNull(region);}}
 public record Shop(UUID shopId,BlockPoint location,String category,List<Product>products){public Shop{Objects.requireNonNull(shopId);Objects.requireNonNull(location);if(category==null||category.isBlank())throw new IllegalArgumentException("Shopカテゴリが必要です。");products=List.copyOf(products);Set<Integer>tiers=new HashSet<>();for(Product product:products)if(!tiers.add(product.tier()))throw new IllegalArgumentException("同一Shop Tierの商品が重複しています。");}}
 public record Product(int tier,PointCategory pointCategory,int price,ItemSpec item){public Product{if(tier<0)throw new IllegalArgumentException("Tierが範囲外です。");Objects.requireNonNull(pointCategory);if(price<0)throw new IllegalArgumentException("価格が範囲外です。");Objects.requireNonNull(item);}}
}
