package com.ryanjei.orushio.pve.economy;
import com.ryanjei.orushio.pve.map.*;import com.ryanjei.orushio.pve.persistence.*;import java.nio.file.Path;import java.time.Duration;import java.util.*;
public final class YamlGameplaySettingsRepository implements GameplaySettingsRepository{
 private final Path mapsRoot;public YamlGameplaySettingsRepository(Path mapsRoot){this.mapsRoot=mapsRoot;}
 public GameplaySettings load(String mapId){return new AtomicYamlStore(path(mapId)).read().map(this::decode).orElseGet(GameplaySettings::empty);}
 public void save(String mapId,GameplaySettings settings){new AtomicYamlStore(path(mapId)).write(encode(settings));}
 private Path path(String mapId){if(mapId==null||!mapId.matches("[a-z0-9][a-z0-9_-]{0,63}"))throw new IllegalArgumentException("mapIdが不正です。");Path path=mapsRoot.resolve(mapId).resolve("gameplay-settings.yml").normalize();if(!path.startsWith(mapsRoot.normalize()))throw new IllegalArgumentException("設定Pathが不正です。");return path;}
 private Map<String,String>encode(GameplaySettings s){Map<String,String>v=new LinkedHashMap<>();v.put("schemaVersion","1");v.put("resourceCount",Integer.toString(s.resourceZones().size()));for(int i=0;i<s.resourceZones().size();i++){var z=s.resourceZones().get(i);String p="resource."+i+".";v.put(p+"id",z.resourceZoneId().toString());v.put(p+"category",z.category().name());v.put(p+"material",z.material());v.put(p+"pointValue",Integer.toString(z.pointValue()));v.put(p+"respawnSeconds",Long.toString(z.respawnDelay().toSeconds()));v.put(p+"region",region(z.region()));}v.put("shopCount",Integer.toString(s.shops().size()));for(int i=0;i<s.shops().size();i++){var shop=s.shops().get(i);String p="shop."+i+".";v.put(p+"id",shop.shopId().toString());v.put(p+"location",point(shop.location()));v.put(p+"category",shop.category());v.put(p+"productCount",Integer.toString(shop.products().size()));for(int j=0;j<shop.products().size();j++){var product=shop.products().get(j);String q=p+"product."+j+".";v.put(q+"tier",Integer.toString(product.tier()));v.put(q+"pointCategory",product.pointCategory().name());v.put(q+"price",Integer.toString(product.price()));v.put(q+"material",product.item().material());v.put(q+"amount",Integer.toString(product.item().amount()));v.put(q+"unbreakable",Boolean.toString(product.item().unbreakable()));v.put(q+"enchantments",enchantments(product.item().enchantments()));}}return v;}
 private GameplaySettings decode(Map<String,String>v){try{if(!"1".equals(req(v,"schemaVersion")))throw new RepositoryException("未対応のgameplay-settings schemaVersionです。");Set<String>used=new HashSet<>(Set.of("schemaVersion","resourceCount","shopCount"));List<GameplaySettings.ResourceZone>zones=new ArrayList<>();int rc=count(v,"resourceCount");for(int i=0;i<rc;i++){String p="resource."+i+".";Collections.addAll(used,p+"id",p+"category",p+"material",p+"pointValue",p+"respawnSeconds",p+"region");String material=req(v,p+"material");if(!material.matches("[A-Z][A-Z0-9_]*"))throw new RepositoryException("Resource MaterialはBukkit enum name形式で指定してください。");zones.add(new GameplaySettings.ResourceZone(UUID.fromString(req(v,p+"id")),PointCategory.valueOf(req(v,p+"category")),material,positive(v,p+"pointValue"),Duration.ofSeconds(positive(v,p+"respawnSeconds")),region(req(v,p+"region"))));}List<GameplaySettings.Shop>shops=new ArrayList<>();int sc=count(v,"shopCount");for(int i=0;i<sc;i++){String p="shop."+i+".";Collections.addAll(used,p+"id",p+"location",p+"category",p+"productCount");List<GameplaySettings.Product>products=new ArrayList<>();int pc=count(v,p+"productCount");for(int j=0;j<pc;j++){String q=p+"product."+j+".";Collections.addAll(used,q+"tier",q+"pointCategory",q+"price",q+"material",q+"amount",q+"unbreakable",q+"enchantments");products.add(new GameplaySettings.Product(nonNegative(v,q+"tier"),PointCategory.valueOf(req(v,q+"pointCategory")),nonNegative(v,q+"price"),new ItemSpec(req(v,q+"material"),positive(v,q+"amount"),enchantments(req(v,q+"enchantments")),strictBoolean(req(v,q+"unbreakable")))));}shops.add(new GameplaySettings.Shop(UUID.fromString(req(v,p+"id")),point(req(v,p+"location")),req(v,p+"category"),products));}if(!used.equals(v.keySet()))throw new RepositoryException("gameplay-settingsに未知の項目があります。");return new GameplaySettings(zones,shops);}catch(RepositoryException e){throw e;}catch(Exception e){throw new RepositoryException("gameplay-settingsの値が不正です。",e);}}
 private static int count(Map<String,String>v,String k){int n=nonNegative(v,k);if(n>10000)throw new RepositoryException("設定件数が範囲外です。");return n;}private static int positive(Map<String,String>v,String k){int n=Integer.parseInt(req(v,k));if(n<1)throw new RepositoryException(k+"が範囲外です。");return n;}private static int nonNegative(Map<String,String>v,String k){int n=Integer.parseInt(req(v,k));if(n<0)throw new RepositoryException(k+"が範囲外です。");return n;}private static String req(Map<String,String>v,String k){String x=v.get(k);if(x==null)throw new RepositoryException(k+"がありません。");return x;}private static boolean strictBoolean(String v){if(!v.equals("true")&&!v.equals("false"))throw new RepositoryException("booleanが不正です。");return Boolean.parseBoolean(v);}
 private static String point(BlockPoint p){return p.x()+","+p.y()+","+p.z()+","+p.yaw()+","+p.pitch();}private static BlockPoint point(String x){String[]p=x.split(",");if(p.length!=5)throw new RepositoryException("地点が不正です。");return new BlockPoint(Integer.parseInt(p[0]),Integer.parseInt(p[1]),Integer.parseInt(p[2]),Float.parseFloat(p[3]),Float.parseFloat(p[4]));}private static String region(Cuboid c){return c.minX()+","+c.minY()+","+c.minZ()+","+c.maxX()+","+c.maxY()+","+c.maxZ();}private static Cuboid region(String x){String[]p=x.split(",");if(p.length!=6)throw new RepositoryException("範囲が不正です。");return new Cuboid(Integer.parseInt(p[0]),Integer.parseInt(p[1]),Integer.parseInt(p[2]),Integer.parseInt(p[3]),Integer.parseInt(p[4]),Integer.parseInt(p[5]));}private static String enchantments(Map<String,Integer>m){return m.entrySet().stream().sorted(Map.Entry.comparingByKey()).map(e->e.getKey()+"="+e.getValue()).reduce((a,b)->a+","+b).orElse("");}private static Map<String,Integer>enchantments(String x){if(x.isBlank())return Map.of();Map<String,Integer>m=new LinkedHashMap<>();for(String part:x.split(",")){String[]p=part.split("=",2);if(p.length!=2||m.put(p[0],Integer.parseInt(p[1]))!=null)throw new RepositoryException("Enchant設定が不正です。");}return m;}
}
