package com.ryanjei.orushio.pve.core;
import com.ryanjei.orushio.pve.domain.*;import com.ryanjei.orushio.pve.logging.AuditSink;import com.ryanjei.orushio.pve.map.*;import org.junit.jupiter.api.*;import java.time.*;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class CoreLifecycleStepTest{
 UUID sessionId=UUID.randomUUID(),alice=UUID.randomUUID();BlockPoint a=new BlockPoint(10,64,10,0,0),b=new BlockPoint(20,64,20,0,0),c=new BlockPoint(30,64,30,0,0),finalPoint=new BlockPoint(50,64,50,0,0);Cuboid gateA=new Cuboid(40,60,40,41,65,41),gateB=new Cuboid(45,60,45,46,65,46);FakeGateway gateway=new FakeGateway();FakeProgress progress=new FakeProgress();CoreLifecycleStep step;GameSession preparing,active;
 @BeforeEach void setup(){Map<String,List<BlockPoint>>points=Map.of("normalCoreCandidates",List.of(a,b,c),"finalCore",List.of(finalPoint));Map<String,List<Cuboid>>areas=Map.of("gateRegions",List.of(gateA,gateB));MapProfile profile=new MapProfile(new MapProfileId("map-a"),"A",false,"template",points,areas,Instant.now());GameRuntimeContext context=new GameRuntimeContext(sessionId,"run-a",RuntimeMap.resolve(profile));preparing=new GameSession(sessionId,GameState.PREPARING,List.of(new Participant(alice,"A",true)),Instant.now(),"map-a",1,60,2,1,null,null,Set.of());Instant activeAt=Instant.now();active=new GameSession(sessionId,GameState.ACTIVE,preparing.participants(),preparing.createdAt(),"map-a",1,60,2,1,activeAt,activeAt.plusSeconds(3600),Set.of());AuditSink audit=new AuditSink(){public void record(String a,String b,String c,String d){}public boolean healthy(){return true;}};CoreSettingsRepository settings=new CoreSettingsRepository(){public CoreSettings load(String id){return new CoreSettings(10,20);}public void save(String id,CoreSettings value){}};step=new CoreLifecycleStep(settings,id->id.equals(sessionId)?Optional.of(context):Optional.empty(),gateway,bound->0,progress,audit);}
 @Test void 必要数を重複なく選びSession中再抽選しない(){step.prepare(preparing);Set<UUID>first=step.selectedNormalCoreIds(sessionId);assertEquals(2,first.size());assertEquals(6,gateway.spawned.size());step.prepare(preparing);assertEquals(first,step.selectedNormalCoreIds(sessionId));assertEquals(6,gateway.spawned.size());}
 @Test void 候補不足を拒否する(){GameSession tooMany=new GameSession(sessionId,GameState.PREPARING,preparing.participants(),preparing.createdAt(),"map-a",1,60,4,1,null,null,Set.of());assertThrows(IllegalArgumentException.class,()->step.prepare(tooMany));}
 @Test void ParticipantとSessionとWorldとCooldown境界を守り武器damageを反映する(){step.prepare(preparing);CoreOwnership core=normalHitbox();assertEquals(CoreLifecycleStep.DamageResult.IGNORED,step.damage(active,UUID.randomUUID(),"run-a",core,10,true));assertEquals(CoreLifecycleStep.DamageResult.IGNORED,step.damage(active,alice,"other",core,10,true));assertEquals(CoreLifecycleStep.DamageResult.IGNORED,step.damage(active,alice,"run-a",core,10,false));assertEquals(CoreLifecycleStep.DamageResult.DAMAGED,step.damage(active,alice,"run-a",core,6,true));assertEquals(CoreLifecycleStep.DamageResult.DESTROYED,step.damage(active,alice,"run-a",core,4,true));assertEquals(CoreLifecycleStep.DamageResult.IGNORED,step.damage(active,alice,"run-a",core,10,true));assertEquals(1,progress.normalCalls);}
 @Test void 必要数達成時だけ複数Gateを一度開く(){step.prepare(preparing);List<CoreOwnership>cores=normalHitboxes();step.damage(active,alice,"run-a",cores.get(0),10,true);assertFalse(step.gateOpen(sessionId));assertTrue(gateway.opened.isEmpty());step.damage(active,alice,"run-a",cores.get(1),10,true);assertTrue(step.gateOpen(sessionId));assertEquals(List.of(gateA,gateB),gateway.opened);assertEquals(CoreLifecycleStep.DamageResult.IGNORED,step.damage(active,alice,"run-a",cores.get(1),10,true));assertEquals(2,gateway.opened.size());}
 @Test void FinalCoreはGate前無効で解放後一度だけ通知する(){step.prepare(preparing);CoreOwnership finalCore=finalHitbox();assertEquals(CoreLifecycleStep.DamageResult.IGNORED,step.damage(active,alice,"run-a",finalCore,20,true));for(CoreOwnership core:normalHitboxes())step.damage(active,alice,"run-a",core,10,true);assertEquals(CoreLifecycleStep.DamageResult.FINAL_DESTROYED,step.damage(active,alice,"run-a",finalCore,20,true));assertEquals(CoreLifecycleStep.DamageResult.IGNORED,step.damage(active,alice,"run-a",finalCore,20,true));assertEquals(1,progress.finalCalls);}
 @Test void cleanupはCurrentSession所有物とUIを冪等に回収する(){step.prepare(preparing);step.cleanup(active);step.cleanup(active);assertEquals(List.of(sessionId),gateway.cleaned);assertEquals(List.of(sessionId),gateway.clearedUi);}
 @Test void 別Sessionからcleanupできない(){step.prepare(preparing);GameSession other=new GameSession(UUID.randomUUID(),GameState.RECOVERING,preparing.participants(),Instant.now(),"map-a",1,60,2,1,null,null,Set.of());assertThrows(IllegalStateException.class,()->step.cleanup(other));assertTrue(gateway.cleaned.isEmpty());}
 private CoreOwnership normalHitbox(){return normalHitboxes().getFirst();}private List<CoreOwnership>normalHitboxes(){return gateway.spawned.stream().map(CoreSpawnRequest::ownership).filter(o->o.type()==CoreType.NORMAL&&o.role()==CoreEntityRole.HITBOX).toList();}private CoreOwnership finalHitbox(){return gateway.spawned.stream().map(CoreSpawnRequest::ownership).filter(o->o.type()==CoreType.FINAL&&o.role()==CoreEntityRole.HITBOX).findFirst().orElseThrow();}
 private static final class FakeGateway implements CoreGateway{final List<CoreSpawnRequest>spawned=new ArrayList<>();final List<Cuboid>opened=new ArrayList<>();final List<UUID>cleaned=new ArrayList<>(),clearedUi=new ArrayList<>();public void spawn(CoreSpawnRequest r){spawned.add(r);}public Optional<CoreOwnership>ownership(UUID id){return Optional.empty();}public void removeCore(UUID s,UUID c,String w){}public void openGates(UUID s,String w,List<Cuboid>g){opened.addAll(g);}public void updateUi(UUID s,String w,List<Participant>p,CoreProgressView v){}public void removeUi(UUID s,UUID p){}public void cleanupOwned(UUID s,String w){cleaned.add(s);}public void clearUi(UUID s){clearedUi.add(s);}}
 private static final class FakeProgress implements CoreProgressListener{int normalCalls,finalCalls;public void normalCoreDestroyed(UUID s,int d,int r){normalCalls++;}public void finalCoreDestroyed(UUID s){finalCalls++;}}
}
