package com.ryanjei.orushio.pve.core;
import static org.junit.jupiter.api.Assertions.*;
import com.ryanjei.orushio.pve.application.*;import com.ryanjei.orushio.pve.domain.GameSession;import java.util.*;import org.junit.jupiter.api.Test;
class GameCoreProgressListenerTest{
 @Test void FinalCoreはCLEAR確定後だけRecoveryをdispatchする(){FakeGames games=new FakeGames();List<Runnable>queued=new ArrayList<>();GameCoreProgressListener listener=new GameCoreProgressListener((id,count)->{},()->games,queued::add);UUID session=UUID.randomUUID();listener.finalCoreDestroyed(session);assertEquals(List.of("clear:"+session),games.events);assertEquals(1,queued.size());queued.getFirst().run();assertEquals(List.of("clear:"+session,"recover:"+session),games.events);}
 @Test void completeGame失敗はdispatchせず呼出元へ返し再試行できる(){FakeGames games=new FakeGames();games.failClear=true;List<Runnable>queued=new ArrayList<>();GameCoreProgressListener listener=new GameCoreProgressListener((id,count)->{},()->games,queued::add);UUID session=UUID.randomUUID();assertThrows(RuntimeException.class,()->listener.finalCoreDestroyed(session));assertTrue(queued.isEmpty());games.failClear=false;listener.finalCoreDestroyed(session);assertEquals(1,queued.size());assertEquals(1,games.clearSuccesses);}
 @Test void dispatcher受付失敗は通知失敗として返りCLEAR確定済みから再試行できる(){FakeGames games=new FakeGames();List<Runnable>queued=new ArrayList<>();boolean[]fail={true};GameCoreProgressListener listener=new GameCoreProgressListener((id,count)->{},()->games,task->{if(fail[0])throw new RuntimeException("dispatch");queued.add(task);});UUID session=UUID.randomUUID();assertThrows(RuntimeException.class,()->listener.finalCoreDestroyed(session));assertEquals(1,games.clearSuccesses);fail[0]=false;listener.finalCoreDestroyed(session);assertEquals(1,queued.size());assertEquals(1,games.clearSuccesses);}
 @Test void queue未実行でもCLEARは既に確定し再起動Recovery対象になる(){FakeGames games=new FakeGames();List<Runnable>queued=new ArrayList<>();UUID session=UUID.randomUUID();new GameCoreProgressListener((id,count)->{},()->games,queued::add).finalCoreDestroyed(session);assertEquals(List.of("clear:"+session),games.events);assertEquals(1,queued.size());}
 @Test void Recovery失敗はCLEAR確定を巻き戻さず同じ処理を再試行できる(){FakeGames games=new FakeGames();games.failRecovery=true;List<Runnable>queued=new ArrayList<>();UUID session=UUID.randomUUID();new GameCoreProgressListener((id,count)->{},()->games,queued::add).finalCoreDestroyed(session);assertThrows(RuntimeException.class,queued.getFirst()::run);assertEquals(1,games.clearSuccesses);games.failRecovery=false;queued.getFirst().run();assertEquals(1,games.recoverySuccesses);}
 @Test void 通常Core進行は既存Tier接続へ渡す(){List<String>events=new ArrayList<>();UUID session=UUID.randomUUID();new GameCoreProgressListener((id,count)->events.add(id+":"+count),FakeGames::new,Runnable::run).normalCoreDestroyed(session,2,3);assertEquals(List.of(session+":2"),events);}
 private static final class FakeGames implements GameApplicationService{final List<String>events=new ArrayList<>();boolean failClear,failRecovery,clear;int clearSuccesses,recoverySuccesses;public GameSession current(){return GameSession.idle();}public OperationResult startRecruiting(String s){throw new UnsupportedOperationException();}public OperationResult closeRecruiting(String s){throw new UnsupportedOperationException();}public OperationResult startMapSetup(String s){throw new UnsupportedOperationException();}public void validateMapSetup(String s){}public OperationResult closeMapSetup(String s){throw new UnsupportedOperationException();}public OperationResult completeGame(UUID id){if(failClear)throw new RuntimeException("clear");if(!clear){clear=true;clearSuccesses++;events.add("clear:"+id);}return new OperationResult("o",id.toString(),"CLEAR");}public OperationResult recoverClearGame(UUID id){if(failRecovery)throw new RuntimeException("recover");recoverySuccesses++;events.add("recover:"+id);return new OperationResult("o",id.toString(),"IDLE");}}
}
