package com.ryanjei.orushio.pve.map;
import static org.junit.jupiter.api.Assertions.*;import com.ryanjei.orushio.pve.application.GameRuntimeView;import com.ryanjei.orushio.pve.domain.*;import com.ryanjei.orushio.pve.logging.AuditSink;import java.nio.file.*;import java.time.Instant;import java.util.*;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;
class GameRuntimeLifecycleStepTest{
 @TempDir Path temp;
 @Test void templateからsession所有runtimeを作り元を変えずcleanupする()throws Exception{Fixture f=fixture();GameSession session=session(f.profile);String before=Files.readString(temp.resolve("maps/map-a/template/level.dat"));f.step.prepare(session);assertEquals("準備済み",f.step.runtimeView().worldState());assertTrue(Files.exists(f.gateway.world.directory()));assertEquals(session.sessionId().toString(),f.gateway.world.sessionId());assertEquals(1,f.gateway.prepared.size());assertEquals(before,Files.readString(temp.resolve("maps/map-a/template/level.dat")));assertEquals(1,f.step.resolveEnabledMarkers("enemyZones:0").size());f.step.cleanup(session);assertFalse(Files.exists(f.gateway.world.directory()));assertTrue(f.gateway.returned);}
 @Test void prepare失敗はrollbackできcleanup失敗は再試行できる()throws Exception{Fixture f=fixture();GameSession session=session(f.profile);f.gateway.failPrepare=true;assertThrows(RuntimeException.class,()->f.step.prepare(session));f.gateway.failPrepare=false;f.step.rollbackPreparation(session);assertFalse(Files.exists(f.gateway.world.directory()));Fixture retry=fixture();GameSession s=session(retry.profile);retry.step.prepare(s);retry.gateway.failCleanup=true;assertThrows(RuntimeException.class,()->retry.step.cleanup(s));assertTrue(Files.exists(retry.gateway.world.directory()));retry.gateway.failCleanup=false;retry.step.cleanup(s);assertFalse(Files.exists(retry.gateway.world.directory()));}
 @Test void disabledMarkerと別Areaを混同せず範囲外Markerを拒否する()throws Exception{MapProfile p=profile();SpawnMarker disabled=new SpawnMarker(UUID.randomUUID(),"enemyZones:0",new BlockPoint(2,64,2,0,0),false);MapProfile value=new MapProfile(p.mapId(),p.displayName(),p.enabled(),p.templateDirectory(),p.points(),p.areas(),p.createdAt(),List.of(disabled));assertTrue(RuntimeMap.resolve(value).enabledMarkers("enemyZones:0").isEmpty());assertThrows(IllegalArgumentException.class,()->RuntimeMap.resolve(new MapProfile(p.mapId(),p.displayName(),p.enabled(),p.templateDirectory(),p.points(),p.areas(),p.createdAt(),List.of(new SpawnMarker(UUID.randomUUID(),"enemyZones:0",new BlockPoint(99,64,99,0,0),true)))));}
 @Test void 再起動後session一致runWorldだけ再発見してcleanupする()throws Exception{Fixture f=fixture();GameSession session=session(f.profile);var target=f.worlds.create(f.profile,"run",session.sessionId().toString());var unrelated=f.worlds.create(f.profile,"run",UUID.randomUUID().toString());var setup=f.worlds.create(f.profile,"setup",session.sessionId().toString());GameRuntimeLifecycleStep restarted=new GameRuntimeLifecycleStep(f.repository,f.worlds,f.gateway,new NoAudit());restarted.cleanup(session);assertFalse(Files.exists(target.directory()));assertTrue(Files.exists(unrelated.directory()));assertTrue(Files.exists(setup.directory()));assertTrue(f.gateway.returned);}
 @Test void sessionだけ残存時もownership全確認後に限りabsenceを成功扱いする()throws Exception{Fixture f=fixture();GameSession session=session(f.profile);f.worlds.prepareStartupRecovery(session.sessionId().toString());f.worlds.recoverPreparedWorlds();GameRuntimeLifecycleStep restarted=new GameRuntimeLifecycleStep(f.repository,f.worlds,f.gateway,new NoAudit());assertDoesNotThrow(()->restarted.cleanup(session));assertEquals(GameRuntimeView.idle(),restarted.runtimeView());assertFalse(f.gateway.returned);}
 @Test void startupRecoveryはsession一致runを保護しsetupと無関係runだけ回収する()throws Exception{Fixture f=fixture();GameSession session=session(f.profile);var target=f.worlds.create(f.profile,"run",session.sessionId().toString());var unrelated=f.worlds.create(f.profile,"run",UUID.randomUUID().toString());var setup=f.worlds.create(f.profile,"setup",session.sessionId().toString());f.worlds.prepareStartupRecovery(session.sessionId().toString());f.worlds.recoverPreparedWorlds();assertTrue(Files.exists(target.directory()));assertFalse(Files.exists(unrelated.directory()));assertFalse(Files.exists(setup.directory()));}
 @Test void 再発見後unload失敗はworldを保持し再試行できる()throws Exception{Fixture f=fixture();GameSession session=session(f.profile);var target=f.worlds.create(f.profile,"run",session.sessionId().toString());GameRuntimeLifecycleStep restarted=new GameRuntimeLifecycleStep(f.repository,f.worlds,f.gateway,new NoAudit());f.gateway.failCleanup=true;assertThrows(RuntimeException.class,()->restarted.cleanup(session));assertTrue(Files.exists(target.directory()));assertEquals("復旧が必要",restarted.runtimeView().worldState());f.gateway.failCleanup=false;restarted.cleanup(session);assertFalse(Files.exists(target.directory()));}
 @Test void delete時ownership不一致はRECOVERY対象を保持し修復後再試行できる()throws Exception{Fixture f=fixture();GameSession session=session(f.profile);var target=f.worlds.create(f.profile,"run",session.sessionId().toString());Path marker=target.directory().resolve(".orushio-world-owner");String owner=Files.readString(marker);GameRuntimeLifecycleStep restarted=new GameRuntimeLifecycleStep(f.repository,f.worlds,f.gateway,new NoAudit());f.gateway.onCleanup=()->{try{Files.writeString(marker,owner.replace(target.ownershipId(),"wrong"));}catch(Exception e){throw new RuntimeException(e);}};assertThrows(MapIoException.class,()->restarted.cleanup(session));assertTrue(Files.exists(target.directory()));Files.writeString(marker,owner);f.gateway.onCleanup=()->{};restarted.cleanup(session);assertFalse(Files.exists(target.directory()));}
 @Test void Runtime状態は準備中から転送完了または安全な失敗表示へ進む()throws Exception{Fixture f=fixture();GameSession session=session(f.profile);f.gateway.onPrepare=()->{GameRuntimeView view=f.step.runtimeView();assertEquals("準備済み",view.worldState());assertEquals("準備済み",view.mapState());assertEquals("参加者を転送中",view.transferState());};f.step.prepare(session);assertEquals("転送完了",f.step.runtimeView().transferState());f.step.cleanup(session);Fixture failed=fixture();failed.gateway.failPrepare=true;assertThrows(RuntimeException.class,()->failed.step.prepare(session(failed.profile)));assertEquals("準備失敗",failed.step.runtimeView().worldState());assertFalse(failed.step.runtimeView().error().isBlank());}
 private Fixture fixture()throws Exception{MapProfile p=profile();Path template=temp.resolve("maps/map-a/template");Files.createDirectories(template);Files.writeString(template.resolve("level.dat"),"original");MapProfileRepository repo=new MapProfileRepository(){public List<MapProfile>findAll(){return List.of(p);}public Optional<MapProfile>find(MapProfileId id){return Optional.of(p);}public void save(MapProfile p){}public void delete(MapProfileId id){}};TemporaryWorldManager worlds=new TemporaryWorldManager(temp.resolve("maps"),temp.resolve("worlds"));FakeGateway gateway=new FakeGateway();GameRuntimeLifecycleStep step=new GameRuntimeLifecycleStep(repo,worlds,gateway,new NoAudit());return new Fixture(p,repo,worlds,step,gateway);}
 private static MapProfile profile(){MapProfile base=MapProfileTest.complete("map-a").withEnabled(true);Map<String,List<Cuboid>> areas=new HashMap<>(base.areas());areas.put("enemyZones",List.of(new Cuboid(0,50,0,10,90,10)));return new MapProfile(base.mapId(),base.displayName(),true,base.templateDirectory(),base.points(),areas,base.createdAt(),List.of(new SpawnMarker(UUID.randomUUID(),"enemyZones:0",new BlockPoint(2,64,2,0,0),true)));}
 private static GameSession session(MapProfile p){UUID player=UUID.randomUUID();return new GameSession(UUID.randomUUID(),GameState.PREPARING,List.of(new Participant(player,"P",true)),Instant.now(),p.mapId().value(),1,60,2,1,null,null,Set.of());}
 private record Fixture(MapProfile profile,MapProfileRepository repository,TemporaryWorldManager worlds,GameRuntimeLifecycleStep step,FakeGateway gateway){}private static final class FakeGateway implements GameRuntimeGateway{TemporaryWorldManager.OwnedWorld world;List<Participant>prepared=List.of();boolean returned,failPrepare,failCleanup;Runnable onPrepare=()->{},onCleanup=()->{};public void prepare(TemporaryWorldManager.OwnedWorld w,RuntimeMap m,List<Participant>p){world=w;prepared=p;onPrepare.run();if(failPrepare)throw new RuntimeException("prepare");}public void returnParticipantsAndUnload(TemporaryWorldManager.OwnedWorld w,List<Participant>p){world=w;if(failCleanup)throw new RuntimeException("cleanup");onCleanup.run();returned=true;}public void reconnectParticipant(TemporaryWorldManager.OwnedWorld w,RuntimeMap m,UUID p){}public void returnPendingToLobby(UUID p){}}private static final class NoAudit implements AuditSink{public void record(String a,String b,String c,String d){}public boolean healthy(){return true;}}
}
