package com.ryanjei.orushio.pve.map;
import static org.junit.jupiter.api.Assertions.*;import com.ryanjei.orushio.pve.domain.MapProfileId;import java.nio.file.*;import java.util.*;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;
class LegacyMapProfileCompatibilityTest{
 @TempDir Path root;
 @Test void 廃止SetupMarkerを持つ実機旧形式を削除せず一覧取得する()throws Exception{Path file=profile("legacy","FARM_RESPAWN;GAME_START;FINAL_AREA_ENTRY;FINAL_AREA_DESTINATION;CHECKPOINT");String before=Files.readString(file);YamlMapProfileRepository repository=new YamlMapProfileRepository(root);List<MapProfile>maps=repository.findAll();assertEquals(List.of("legacy"),maps.stream().map(p->p.mapId().value()).toList());assertTrue(maps.getFirst().setupMarkers().isEmpty());assertFalse(maps.getFirst().setupComplete());assertEquals(before,Files.readString(file));}
 @Test void SetupMarkerなしの旧形式と現行Markerあり形式を同時に読める()throws Exception{profile("old","");Path modern=profile("modern","");String value=Files.readString(modern);Files.writeString(modern,value.replace("setupMarkers: \"\"","setupMarkers: \""+UUID.randomUUID()+",WARP,1,64,1,0.0,0.0,true\""));List<MapProfile>maps=new YamlMapProfileRepository(root).findAll();assertEquals(List.of("modern","old"),maps.stream().map(p->p.mapId().value()).toList());assertEquals(SetupMarkerType.WARP,maps.getFirst().setupMarkers().getFirst().markerType());}
 @Test void 破損Mapを隔離して正常Map一覧を返し個別読込では理由を保持する()throws Exception{profile("healthy","");profile("broken","UNKNOWN_MARKER");YamlMapProfileRepository repository=new YamlMapProfileRepository(root);assertEquals(List.of("healthy"),repository.findAll().stream().map(p->p.mapId().value()).toList());assertEquals(1,repository.loadIssues().size());assertTrue(repository.loadIssues().getFirst().contains("UNKNOWN_MARKER"));RuntimeException failure=assertThrows(RuntimeException.class,()->repository.find(new MapProfileId("broken")));assertTrue(rootMessage(failure).contains("UNKNOWN_MARKER"));}
 @Test void 登録Mapゼロ件も正常な空一覧を返す(){assertTrue(new YamlMapProfileRepository(root).findAll().isEmpty());}
 private Path profile(String mapId,String legacyTypes)throws Exception{Path file=root.resolve(mapId).resolve("profile.yml");Files.createDirectories(file.getParent());String markers=legacyTypes.isBlank()?"":Arrays.stream(legacyTypes.split(";")).map(type->UUID.randomUUID()+","+type+",1,64,1,0.0,0.0,true").reduce((a,b)->a+";"+b).orElse("");Files.writeString(file,"schemaVersion: \"1\"\nmapId: \""+mapId+"\"\ndisplayName: \""+mapId+"\"\nenabled: \"false\"\ntemplateDirectory: \"template\"\ncreatedAt: \"2026-01-01T00:00:00Z\"\nspawnMarkers: \"\"\nsetupMarkers: \""+markers+"\"\n");return file;}
 private static String rootMessage(Throwable failure){Throwable value=failure;while(value.getCause()!=null)value=value.getCause();return String.valueOf(value.getMessage());}
}
