package com.ryanjei.orushio.pve.map;
import static org.junit.jupiter.api.Assertions.*;import com.ryanjei.orushio.pve.domain.MapProfileId;import java.time.Instant;import java.util.*;import org.junit.jupiter.api.Test;
public class MapProfileTest{
 @Test void 必須不足では有効化できない(){MapProfile p=empty("a");assertFalse(p.setupComplete());assertThrows(IllegalArgumentException.class,()->p.withEnabled(true));}
 @Test void 必須項目が揃えば有効化できる(){assertTrue(complete("a").withEnabled(true).enabled());}
 @Test void 初期リスポーンは一件必須でWarpは一件以上_SavePointは任意(){MapProfile complete=complete("a");List<SetupMarker>none=complete.setupMarkers().stream().filter(m->m.markerType()!=SetupMarkerType.INITIAL_RESPAWN).toList();assertFalse(copy(complete,none).setupComplete());List<SetupMarker>two=new ArrayList<>(complete.setupMarkers());two.add(marker(SetupMarkerType.INITIAL_RESPAWN,new BlockPoint(2,64,2,0,0)));assertFalse(copy(complete,two).setupComplete());List<SetupMarker>many=new ArrayList<>(complete.setupMarkers());many.add(marker(SetupMarkerType.WARP,new BlockPoint(3,64,3,0,0)));many.add(marker(SetupMarkerType.SAVE_POINT,new BlockPoint(4,64,4,0,0)));assertTrue(copy(complete,many).setupComplete());}
 static MapProfile empty(String id){return new MapProfile(new MapProfileId(id),id,false,"template",Map.of(),Map.of(),Instant.now());}
 public static MapProfile complete(String id){Cuboid farm=new Cuboid(0,60,0,10,70,10),enemy=new Cuboid(20,60,20,30,70,30);Map<String,List<Cuboid>>areas=new HashMap<>();areas.put("farmRegion",List.of(farm));areas.put("enemyZones",List.of(enemy));areas.put("finalRegion",List.of(new Cuboid(90,60,90,130,80,130)));List<SetupMarker>markers=new ArrayList<>();markers.add(marker(SetupMarkerType.INITIAL_RESPAWN,new BlockPoint(0,64,0,0,0)));for(int i=0;i<3;i++)markers.add(marker(SetupMarkerType.NORMAL_CORE,new BlockPoint(10+i,64,10,0,0)));markers.add(marker(SetupMarkerType.FINAL_CORE,new BlockPoint(100,64,100,0,0)));markers.add(marker(SetupMarkerType.FINAL_GATE,new BlockPoint(80,64,80,0,0)));markers.add(marker(SetupMarkerType.WARP,new BlockPoint(1,64,1,0,0)));return new MapProfile(new MapProfileId(id),id,false,"template",Map.of(),areas,Instant.now(),List.of(),markers);}
 private static SetupMarker marker(SetupMarkerType type,BlockPoint point){return new SetupMarker(UUID.randomUUID(),type,point,true);}private static MapProfile copy(MapProfile p,List<SetupMarker>m){return new MapProfile(p.mapId(),p.displayName(),false,p.templateDirectory(),p.points(),p.areas(),p.createdAt(),p.spawnMarkers(),m);}
}
