package com.ryanjei.orushio.pve.map;
import static org.junit.jupiter.api.Assertions.*;
import com.ryanjei.orushio.pve.domain.MapProfileId;
import java.time.Instant;import java.util.*;import org.junit.jupiter.api.Test;
public class MapProfileTest{
 @Test void 必須不足では有効化できない(){MapProfile p=empty("a");assertFalse(p.setupComplete());assertThrows(IllegalArgumentException.class,()->p.withEnabled(true));}
 @Test void 必須項目が揃えば有効化できる(){assertTrue(complete("a").withEnabled(true).enabled());}
 @Test void FinalAreaDestinationは有効な1件だけを必須とする(){MapProfile complete=complete("a");List<SetupMarker>none=complete.setupMarkers().stream().filter(m->m.markerType()!=SetupMarkerType.FINAL_AREA_DESTINATION).toList();MapProfile missing=new MapProfile(complete.mapId(),complete.displayName(),false,complete.templateDirectory(),complete.points(),complete.areas(),complete.createdAt(),complete.spawnMarkers(),none);assertFalse(missing.setupComplete());assertThrows(IllegalArgumentException.class,()->missing.withEnabled(true));List<SetupMarker>two=new ArrayList<>(complete.setupMarkers());two.add(new SetupMarker(UUID.randomUUID(),SetupMarkerType.FINAL_AREA_DESTINATION,new BlockPoint(101,64,100,0,0),true));MapProfile duplicate=new MapProfile(complete.mapId(),complete.displayName(),false,complete.templateDirectory(),complete.points(),complete.areas(),complete.createdAt(),complete.spawnMarkers(),two);assertFalse(duplicate.setupComplete());assertThrows(IllegalArgumentException.class,()->duplicate.withEnabled(true));}
 static MapProfile empty(String id){return new MapProfile(new MapProfileId(id),id,false,"template",Map.of(),Map.of(),Instant.now());}
 public static MapProfile complete(String id){BlockPoint p=new BlockPoint(0,64,0,0,0);Map<String,List<BlockPoint>>points=new HashMap<>();for(String k:MapProfile.REQUIRED_SINGLE_POINTS)points.put(k,List.of(p));points.put("normalCoreCandidates",List.of(p,p,p));points.put("shopPoints",List.of(p));Cuboid c=new Cuboid(0,0,0,1,1,1);Map<String,List<Cuboid>>areas=new HashMap<>();for(String k:MapProfile.REQUIRED_AREA_COUNTS.keySet())areas.put(k,List.of(c));areas.put("finalRegion",List.of(new Cuboid(90,60,90,130,80,130)));SetupMarker destination=new SetupMarker(UUID.randomUUID(),SetupMarkerType.FINAL_AREA_DESTINATION,new BlockPoint(100,64,100,0,0),true);return new MapProfile(new MapProfileId(id),id,false,"template",points,areas,Instant.now(),List.of(),List.of(destination));}
}
