package com.ryanjei.orushio.pve.map;

import static org.junit.jupiter.api.Assertions.*;
import com.ryanjei.orushio.pve.application.DefaultGameApplicationService;
import com.ryanjei.orushio.pve.domain.*;
import com.ryanjei.orushio.pve.logging.AuditSink;
import com.ryanjei.orushio.pve.persistence.ActiveSessionRepository;
import java.nio.file.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class MapSetupRecoveryTest {
 @TempDir Path temp;
 @Test void MAP_SETUPをshutdownで保存せず破棄しIDLEへ戻す()throws Exception{Fixture f=fixture();UUID admin=UUID.randomUUID();f.service.startSetup("map-a",admin,"IDLE");f.service.issueSetupMarker(admin,SetupMarkerType.NORMAL_CORE);f.service.recordSetupMarker(admin,f.world.token,new BlockPoint(1,64,1,0,0));Path setupWorld=f.world.owned.directory();MapProfile before=f.profiles.find(new MapProfileId("map-a")).orElseThrow();f.service.shutdownMapSetupSafely();assertEquals(GameState.IDLE,f.games.current().state());assertTrue(f.evidence.load().isEmpty());assertFalse(Files.exists(setupWorld));assertEquals(before,f.profiles.find(new MapProfileId("map-a")).orElseThrow());assertTrue(f.world.completed);assertTrue(f.audit.codes.contains("MAP_SETUP_SHUTDOWN_DISCARD_COMPLETED"));}
 @Test void IDLEのshutdownは何もしない()throws Exception{Fixture f=fixture();f.service.shutdownMapSetupSafely();assertEquals(GameState.IDLE,f.games.current().state());assertFalse(f.world.completed);}
 @Test void 再起動相当の残留Evidenceと所有Worldを手動復旧し再Setupできる()throws Exception{Fixture f=fixture();UUID admin=UUID.randomUUID();f.service.startSetup("map-a",admin,"IDLE");TemporaryWorldManager.OwnedWorld owned=f.world.owned;MapProfile before=f.profiles.find(new MapProfileId("map-a")).orElseThrow();f.worlds.requireRecovery(owned,"test");DefaultMapAdministrationService restarted=f.restarted();MapAdministrationService.SetupRecoveryView view=restarted.setupRecovery();assertTrue(view.recoveryRequired());assertTrue(view.safeToRecover());restarted.discardSetupRecovery();assertEquals(GameState.IDLE,f.games.current().state());assertFalse(Files.exists(owned.directory()));assertTrue(f.evidence.load().isEmpty());assertFalse(f.worlds.recoveryRequired());assertEquals(before,f.profiles.find(new MapProfileId("map-a")).orElseThrow());assertDoesNotThrow(()->restarted.startSetup("map-a",admin,"IDLE"));}
 @Test void ownership不一致は削除せずRecoveryを維持する()throws Exception{Fixture f=fixture();UUID admin=UUID.randomUUID();f.service.startSetup("map-a",admin,"IDLE");TemporaryWorldManager.OwnedWorld owned=f.world.owned;MapSetupEvidenceRepository.Evidence actual=f.evidence.load().orElseThrow();f.evidence.save(new MapSetupEvidenceRepository.Evidence(actual.sessionId(),actual.mapId(),actual.administrator(),actual.worldName(),"wrong"));f.worlds.requireRecovery(owned,"test");DefaultMapAdministrationService restarted=f.restarted();assertFalse(restarted.setupRecovery().safeToRecover());assertThrows(SecurityException.class,restarted::discardSetupRecovery);assertTrue(Files.exists(owned.directory()));assertTrue(f.evidence.load().isPresent());assertEquals(GameState.MAP_SETUP,f.games.current().state());assertTrue(f.audit.codes.contains("MAP_SETUP_RECOVERY_REJECTED"));}
 @Test void Evidence不正は安全側で拒否する()throws Exception{Fixture f=fixture();Files.createDirectories(temp.resolve("sessions"));Files.writeString(temp.resolve("sessions/map-setup.yml"),"schemaVersion: \"1\"\nactive: \"true\"\nmapId: \"map-a\"\n");MapAdministrationService.SetupRecoveryView view=f.service.setupRecovery();assertTrue(view.recoveryRequired());assertFalse(view.safeToRecover());assertThrows(SecurityException.class,f.service::discardSetupRecovery);}
 private Fixture fixture()throws Exception{Path maps=temp.resolve("maps"),worldRoot=temp.resolve("worlds"),template=maps.resolve("map-a/template");Files.createDirectories(template);Files.writeString(template.resolve("level.dat"),"original");Files.writeString(maps.resolve("map-a/.orushio-map-owner"),"map-a");Profiles profiles=new Profiles();profiles.save(MapProfileTest.empty("map-a"));Session sessions=new Session();DefaultGameApplicationService games=new DefaultGameApplicationService(sessions);TemporaryWorldManager worlds=new TemporaryWorldManager(maps,worldRoot);World world=new World();Codes audit=new Codes();MapSetupEvidenceRepository evidence=new MapSetupEvidenceRepository(temp.resolve("sessions/map-setup.yml"));DefaultMapAdministrationService service=new DefaultMapAdministrationService(maps,profiles,new SafeWorldZipImporter(maps,SafeWorldZipImporter.Limits.defaults()),worlds,world,games,new MapSelectionService(new Random(1)),audit,evidence);return new Fixture(maps,profiles,games,worlds,world,audit,evidence,service);}
 record Fixture(Path maps,Profiles profiles,DefaultGameApplicationService games,TemporaryWorldManager worlds,World world,Codes audit,MapSetupEvidenceRepository evidence,DefaultMapAdministrationService service){DefaultMapAdministrationService restarted(){return new DefaultMapAdministrationService(maps,profiles,new SafeWorldZipImporter(maps,SafeWorldZipImporter.Limits.defaults()),worlds,world,games,new MapSelectionService(new Random(1)),audit,evidence);}}
 static final class Profiles implements MapProfileRepository{final Map<MapProfileId,MapProfile>values=new HashMap<>();public List<MapProfile>findAll(){return List.copyOf(values.values());}public Optional<MapProfile>find(MapProfileId id){return Optional.ofNullable(values.get(id));}public void save(MapProfile value){values.put(value.mapId(),value);}public void delete(MapProfileId id){values.remove(id);}}
 static final class Session implements ActiveSessionRepository{GameSession value;public Optional<GameSession>load(){return Optional.ofNullable(value);}public void save(GameSession value){this.value=value;}}
 static final class World implements MapWorldGateway{TemporaryWorldManager.OwnedWorld owned;SetupMarkerToken token;boolean completed;public void loadForSetup(TemporaryWorldManager.OwnedWorld world,UUID admin){owned=world;}public void unload(TemporaryWorldManager.OwnedWorld world){}public void giveSetupMarkerBlock(TemporaryWorldManager.OwnedWorld world,UUID admin,SetupMarkerToken token){this.token=token;}public void completeSetup(TemporaryWorldManager.OwnedWorld world,UUID admin,String message){completed=true;} }
 static final class Codes implements AuditSink{final List<String>codes=new ArrayList<>();public void record(String t,String c,String code,String operation){codes.add(code);}public boolean healthy(){return true;}}
}
