package com.ryanjei.orushio.pve.map;
import static org.junit.jupiter.api.Assertions.*;import com.ryanjei.orushio.pve.application.*;import com.ryanjei.orushio.pve.bootstrap.StartupState;import com.ryanjei.orushio.pve.domain.*;import com.ryanjei.orushio.pve.logging.AuditSink;import com.ryanjei.orushio.pve.persistence.*;import java.nio.file.*;import java.time.Instant;import java.util.*;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;
class RestartRuntimeRecoveryIntegrationTest{
 @TempDir Path temp;
 @Test void 正常未完了sessionをRECOVERINGへ保存し再発見cleanup後だけIDLEにする()throws Exception{Path mapsRoot=temp.resolve("maps"),worldRoot=temp.resolve("worlds"),template=mapsRoot.resolve("map-a/template");Files.createDirectories(template);Files.writeString(template.resolve("level.dat"),"original");MapProfile profile=complete();MapProfileRepository profiles=new MemoryProfiles(profile);UUID player=UUID.randomUUID();GameSession active=new GameSession(UUID.randomUUID(),GameState.ACTIVE,List.of(new Participant(player,"P",false)),Instant.now(),"map-a",1,60,2,1,Instant.now(),Instant.now().plusSeconds(60),Set.of());YamlActiveSessionRepository sessions=new YamlActiveSessionRepository(temp.resolve("sessions/active.yml"));sessions.save(active);TemporaryWorldManager worlds=new TemporaryWorldManager(mapsRoot,worldRoot);var owned=worlds.create(profile,"run",active.sessionId().toString());StartupState startup=StartupState.load(temp);assertFalse(startup.diagnosticMode());assertTrue(startup.recoverableGameSession());worlds.prepareStartupRecovery(active.sessionId().toString());worlds.recoverPreparedWorlds();GameSession recovering=StartupState.recoverySessionAfterRestart(startup.session().orElseThrow());sessions.save(recovering);FakeGateway gateway=new FakeGateway();GameRuntimeLifecycleStep runtime=new GameRuntimeLifecycleStep(profiles,worlds,gateway,new NoAudit());DefaultGameApplicationService games=new DefaultGameApplicationService(sessions,recovering,List::of,profiles,new MemorySettings(),List.of(runtime),new NoAudit());assertEquals(GameState.RECOVERING,games.current().state());assertThrows(DomainException.class,()->games.prepareGame("RECOVERING","map-a"));games.abortGame(recovering.sessionId().toString(),"RECOVERY");assertEquals(GameState.IDLE,games.current().state());assertFalse(Files.exists(owned.directory()));assertTrue(gateway.cleaned);}
 private static MapProfile complete(){MapProfile base=MapProfileTest.complete("map-a");return new MapProfile(base.mapId(),base.displayName(),true,base.templateDirectory(),base.points(),base.areas(),base.createdAt());}
 private record MemoryProfiles(MapProfile profile)implements MapProfileRepository{public List<MapProfile>findAll(){return List.of(profile);}public Optional<MapProfile>find(MapProfileId id){return id.equals(profile.mapId())?Optional.of(profile):Optional.empty();}public void save(MapProfile ignored){}public void delete(MapProfileId ignored){}}
 private static final class MemorySettings implements GameLaunchSettingsRepository{public GameLaunchSettings load(String id){return GameLaunchSettings.defaults();}public void save(String id,GameLaunchSettings value){}}
 private static final class FakeGateway implements GameRuntimeGateway{boolean cleaned;public void prepare(TemporaryWorldManager.OwnedWorld w,RuntimeMap m,List<Participant>p){}public void returnParticipantsAndUnload(TemporaryWorldManager.OwnedWorld w,List<Participant>p){cleaned=true;}public void reconnectParticipant(TemporaryWorldManager.OwnedWorld w,RuntimeMap m,UUID p){}public void returnPendingToLobby(UUID p){}}
 private static final class NoAudit implements AuditSink{public void record(String a,String b,String c,String d){}public boolean healthy(){return true;}}
}
