package com.ryanjei.orushio.pve.map;

import com.ryanjei.orushio.pve.application.GameApplicationService;
import com.ryanjei.orushio.pve.domain.MapProfileId;
import com.ryanjei.orushio.pve.logging.AuditSink;
import java.nio.file.*;
import java.util.*;

public final class DefaultMapAdministrationService implements MapAdministrationService {
    private final Path mapsRoot; private final MapProfileRepository repository; private final SafeWorldZipImporter importer;
    private final TemporaryWorldManager worlds; private final MapWorldGateway worldGateway; private final GameApplicationService games; private final MapSelectionService selection; private final AuditSink audit;
    private Draft draft;
    public DefaultMapAdministrationService(Path mapsRoot,MapProfileRepository repository,SafeWorldZipImporter importer,TemporaryWorldManager worlds,MapWorldGateway worldGateway,GameApplicationService games,MapSelectionService selection){this(mapsRoot,repository,importer,worlds,worldGateway,games,selection,new AuditSink(){public void record(String t,String c,String code,String operation){}public boolean healthy(){return true;}});}
    public DefaultMapAdministrationService(Path mapsRoot,MapProfileRepository repository,SafeWorldZipImporter importer,TemporaryWorldManager worlds,MapWorldGateway worldGateway,GameApplicationService games,MapSelectionService selection,AuditSink audit){this.mapsRoot=mapsRoot.toAbsolutePath().normalize();this.repository=repository;this.importer=importer;this.worlds=worlds;this.worldGateway=worldGateway;this.games=games;this.selection=selection;this.audit=audit;}
    @Override public synchronized List<MapProfile> list(){return repository.findAll();}
    @Override public synchronized Optional<String> fixedNextMapId(){return selection.fixedNext().map(MapProfileId::value);}
    @Override public synchronized MapProfile importZip(Path zip,String mapId,String displayName){return importer.importZip(zip,new MapProfileId(mapId),displayName);}
    @Override public synchronized MapProfile setEnabled(String mapId,boolean enabled){MapProfile profile=require(mapId).withEnabled(enabled);repository.save(profile);if(!enabled)selection.clearFixed(profile.mapId());return profile;}
    @Override public synchronized void fixNext(String mapId){selection.fixNext(require(mapId));}
    @Override public synchronized void delete(String mapId){MapProfile profile=require(mapId);if(draft!=null&&draft.profile.mapId().equals(profile.mapId()))throw new IllegalStateException("セットアップ中のマップは削除できません。");if(worlds.hasOwnedWorld(profile.mapId()))throw new IllegalStateException("一時ワールド使用中のマップは削除できません。");Path dir=mapsRoot.resolve(profile.mapId().value()).normalize();try{Path marker=dir.resolve(".orushio-map-owner");if(!dir.getParent().equals(mapsRoot)||!Files.isRegularFile(marker,LinkOption.NOFOLLOW_LINKS)||Files.isSymbolicLink(marker)||!Files.readString(marker).equals(profile.mapId().value()))throw new IllegalStateException("マップ所有情報を確認できません。");SafeFiles.deleteTree(dir);repository.delete(profile.mapId());selection.clearFixed(profile.mapId());}catch(Exception exception){if(exception instanceof IllegalStateException state)throw state;throw new MapIoException("MAP_DELETE","マップを安全に削除できません。",exception);}}
    @Override public synchronized SetupView startSetup(String mapId,UUID administrator,String expectedGameState){if(draft!=null)throw new IllegalStateException("別のセットアップが進行中です。");MapProfile profile=require(mapId);games.startMapSetup(expectedGameState);TemporaryWorldManager.OwnedWorld world=null;try{world=worlds.create(profile,"setup");worldGateway.loadForSetup(world,administrator);draft=new Draft(profile,administrator,world);return setup();}catch(RuntimeException exception){if(world==null){games.closeMapSetup(games.current().sessionId().toString());throw exception;}try{worldGateway.unload(world);}catch(Exception rollback){exception.addSuppressed(rollback);draft=new Draft(profile,administrator,world);worlds.requireRecovery(world,"ロード途中の一時ワールドをアンロードできません。");throw exception;}try{games.closeMapSetup(games.current().sessionId().toString());}catch(Exception rollback){exception.addSuppressed(rollback);draft=new Draft(profile,administrator,world);throw exception;}try{worlds.delete(world);}catch(Exception rollback){exception.addSuppressed(rollback);draft=new Draft(profile,administrator,world);worlds.requireRecovery(world,"ロード途中の一時ワールドを削除できません。");throw exception;}throw exception;}}
    @Override public synchronized SetupView setup(){if(draft==null)return SetupView.inactive();MapProfile current=draft.current();Map<String,Integer> counts=new LinkedHashMap<>();Map<String,List<SetupEntry>> entries=new LinkedHashMap<>();MapFieldCatalog.FIELDS.forEach(field->{if(field.area()){List<Cuboid> values=current.areas().getOrDefault(field.key(),List.of());counts.put(field.key(),values.size());entries.put(field.key(),values.stream().map(value->new SetupEntry(null,value)).toList());}else{List<BlockPoint> values=current.points().getOrDefault(field.key(),List.of());counts.put(field.key(),values.size());entries.put(field.key(),values.stream().map(value->new SetupEntry(value,null)).toList());}});List<MarkerAreaView> markerAreas=current.logicalAreas().stream().filter(area->Set.of("enemyZones","farmRegion","resourceZones","finalRegion").contains(area.fieldKey())).map(area->{List<SpawnMarker> markers=current.spawnMarkers().stream().filter(marker->marker.areaId().equals(area.areaId())).toList();return new MarkerAreaView(area.areaId(),area.label()+" "+(area.index()+1),markers.size(),markers);}).toList();return new SetupView(true,draft.profile.mapId().value(),draft.profile.displayName(),draft.administrator.toString(),draft.markerAreaId!=null?"spawnMarker":draft.field==null?"":draft.field,draft.area,current.missingRequirements(),counts,entries,markerAreas,draft.revision);}
    @Override public synchronized void selectField(UUID administrator,String field,boolean area){Draft value=authorized(administrator);Set<String> allowed=area?Set.of("farmRegion","gateRegions","finalRegion","enemyZones","resourceZones","checkpoints"):Set.of("farmSpawn","combatEntry","normalCoreCandidates","finalCore","finalEntryTrigger","shopPoints");if(!allowed.contains(field))throw new IllegalArgumentException("登録項目が不正です。");value.field=field;value.area=area;value.first=null;value.markerAreaId=null;value.markerId=null;}
    @Override public synchronized void recordClick(UUID administrator,BlockPoint point,boolean secondaryCorner){Draft value=authorized(administrator);if(value.markerAreaId!=null){LogicalArea area=value.current().logicalAreas().stream().filter(a->a.areaId().equals(value.markerAreaId)).findFirst().orElseThrow(()->new IllegalStateException("対象Areaがありません。"));if(!inside(area.region(),point))throw new IllegalArgumentException("Spawn Markerは所属Area内へ登録してください。");if(value.markerId==null){value.markers.add(new SpawnMarker(UUID.randomUUID(),value.markerAreaId,point,true));audit.record(UUID.randomUUID().toString(),"ADMIN","SPAWN_MARKER_ADDED","MAP_SETUP_CLICK");}else{int index=markerIndex(value,value.markerId);value.markers.set(index,value.markers.get(index).withPosition(point));}value.revision++;return;}if(value.field==null)throw new IllegalStateException("管理画面で登録項目を選択してください。");if(!value.area){List<BlockPoint> target=value.points.computeIfAbsent(value.field,key->new ArrayList<>());if(MapProfile.REQUIRED_SINGLE_POINTS.contains(value.field))target.clear();target.add(point);value.revision++;return;}if(!secondaryCorner){value.first=point;return;}if(value.first==null)throw new IllegalStateException("範囲の1点目を先に指定してください。");List<Cuboid> target=value.areas.computeIfAbsent(value.field,key->new ArrayList<>());if(Set.of("farmRegion","finalRegion").contains(value.field))target.clear();target.add(Cuboid.between(value.first,point));value.first=null;value.revision++;}
    @Override public synchronized void removeSetupEntry(UUID administrator,String field,boolean area,int index){Draft value=authorized(administrator);MapFieldCatalog.Field definition=field(field,area);if(index<0)throw new IllegalArgumentException("削除対象が不正です。");if(definition.area()){if(value.markers.stream().anyMatch(marker->marker.areaId().startsWith(field+":")))throw new IllegalStateException("この種類のAreaにあるSpawn Markerを先に削除してください。");removeAt(value.areas.get(definition.key()),index);}else removeAt(value.points.get(definition.key()),index);value.revision++;}
    @Override public synchronized void teleportSetupEntry(UUID administrator,String field,boolean area,int index){Draft value=authorized(administrator);MapFieldCatalog.Field definition=field(field,area);BlockPoint target;if(definition.area()){Cuboid region=getAt(value.areas.get(definition.key()),index);target=new BlockPoint(midpoint(region.minX(),region.maxX()),midpoint(region.minY(),region.maxY()),midpoint(region.minZ(),region.maxZ()),0,0);}else target=getAt(value.points.get(definition.key()),index);worldGateway.teleportSetupAdministrator(value.world,value.administrator,target);}
    @Override public synchronized void selectSpawnMarker(UUID administrator,String areaId,String markerId){Draft value=authorized(administrator);if(value.current().logicalAreas().stream().noneMatch(area->area.areaId().equals(areaId)))throw new IllegalArgumentException("対象Areaがありません。");value.markerAreaId=areaId;value.markerId=markerId==null||markerId.isBlank()?null:UUID.fromString(markerId);if(value.markerId!=null){SpawnMarker marker=value.markers.get(markerIndex(value,value.markerId));if(!marker.areaId().equals(areaId))throw new IllegalArgumentException("Spawn Markerの所属Areaが一致しません。");}value.field=null;value.area=false;}
    @Override public synchronized void setSpawnMarkerEnabled(UUID administrator,UUID markerId,boolean enabled){Draft value=authorized(administrator);int index=markerIndex(value,markerId);value.markers.set(index,value.markers.get(index).withEnabled(enabled));value.revision++;}
    @Override public synchronized void removeSpawnMarker(UUID administrator,UUID markerId){Draft value=authorized(administrator);value.markers.remove(markerIndex(value,markerId));value.revision++;}
    @Override public synchronized void teleportSpawnMarker(UUID administrator,UUID markerId){Draft value=authorized(administrator);worldGateway.teleportSetupAdministrator(value.world,value.administrator,value.markers.get(markerIndex(value,markerId)).position());}
    @Override public synchronized MapProfile saveSetup(String expectedSessionId){Draft value=requiredDraft();games.validateMapSetup(expectedSessionId);MapProfile previous=value.profile;MapProfile saved=value.current();repository.save(saved);try{games.closeMapSetup(expectedSessionId);}catch(RuntimeException failure){try{repository.save(previous);}catch(Exception rollback){failure.addSuppressed(rollback);worlds.requireRecovery(value.world,"ゲーム状態とMapProfileの保存を安全にrollbackできません。");}throw failure;}finishAfterSessionClosed(value,"「"+saved.displayName()+"」のセットアップを保存して終了しました。");return saved;}
    @Override public synchronized void discardSetup(String expectedSessionId){Draft value=requiredDraft();games.validateMapSetup(expectedSessionId);games.closeMapSetup(expectedSessionId);finishAfterSessionClosed(value,"セットアップ変更を破棄して終了しました。");}
    private void finishAfterSessionClosed(Draft value,String message){try{worldGateway.completeSetup(value.world,value.administrator,message);worlds.delete(value.world);draft=null;}catch(RuntimeException failure){worlds.requireRecovery(value.world,"セットアップ終了後の一時ワールド回収に失敗しました。");throw failure;}}
    private Draft authorized(UUID id){Draft value=requiredDraft();if(!value.administrator.equals(id))throw new SecurityException("このセットアップを操作する権限がありません。");return value;}
    private static MapFieldCatalog.Field field(String key,boolean area){return MapFieldCatalog.FIELDS.stream().filter(value->value.key().equals(key)&&value.area()==area).findFirst().orElseThrow(()->new IllegalArgumentException("設定項目が不正です。"));}
    private static <T>T getAt(List<T> values,int index){if(values==null||index<0||index>=values.size())throw new IllegalArgumentException("対象の座標が見つかりません。");return values.get(index);}
    private static <T>void removeAt(List<T> values,int index){getAt(values,index);values.remove(index);}
    private static int midpoint(int minimum,int maximum){return (int)(((long)minimum+(long)maximum)/2L);}private static boolean inside(Cuboid a,BlockPoint p){return p.x()>=a.minX()&&p.x()<=a.maxX()&&p.y()>=a.minY()&&p.y()<=a.maxY()&&p.z()>=a.minZ()&&p.z()<=a.maxZ();}private static int markerIndex(Draft value,UUID id){for(int i=0;i<value.markers.size();i++)if(value.markers.get(i).markerId().equals(id))return i;throw new IllegalArgumentException("Spawn Markerが見つかりません。");}
    private Draft requiredDraft(){if(draft==null)throw new IllegalStateException("セットアップは開始されていません。");return draft;}
    private MapProfile require(String id){return repository.find(new MapProfileId(id)).orElseThrow(()->new IllegalArgumentException("マップが見つかりません。"));}
    private static final class Draft {final MapProfile profile;final UUID administrator;final TemporaryWorldManager.OwnedWorld world;final Map<String,List<BlockPoint>> points=new LinkedHashMap<>();final Map<String,List<Cuboid>> areas=new LinkedHashMap<>();final List<SpawnMarker>markers=new ArrayList<>();String field,markerAreaId;UUID markerId;boolean area;BlockPoint first;long revision;Draft(MapProfile profile,UUID administrator,TemporaryWorldManager.OwnedWorld world){this.profile=profile;this.administrator=administrator;this.world=world;profile.points().forEach((key,value)->points.put(key,new ArrayList<>(value)));profile.areas().forEach((key,value)->areas.put(key,new ArrayList<>(value)));markers.addAll(profile.spawnMarkers());}MapProfile current(){return profile.withDraft(points,areas,markers);}}
}
