package com.ryanjei.orushio.pve.map;

import com.ryanjei.orushio.pve.application.GameApplicationService;
import com.ryanjei.orushio.pve.domain.MapProfileId;
import com.ryanjei.orushio.pve.logging.AuditSink;
import java.nio.file.*;
import java.util.*;

public final class DefaultMapAdministrationService implements MapAdministrationService {
    private final Path mapsRoot; private final MapProfileRepository repository; private final SafeWorldZipImporter importer;
    private final TemporaryWorldManager worlds; private final MapWorldGateway worldGateway; private final GameApplicationService games; private final MapSelectionService selection; private final AuditSink audit;
    private final MapSetupEvidenceRepository setupEvidence;
    private Draft draft;
    public DefaultMapAdministrationService(Path mapsRoot,MapProfileRepository repository,SafeWorldZipImporter importer,TemporaryWorldManager worlds,MapWorldGateway worldGateway,GameApplicationService games,MapSelectionService selection){this(mapsRoot,repository,importer,worlds,worldGateway,games,selection,new AuditSink(){public void record(String t,String c,String code,String operation){}public boolean healthy(){return true;}});}
    public DefaultMapAdministrationService(Path mapsRoot,MapProfileRepository repository,SafeWorldZipImporter importer,TemporaryWorldManager worlds,MapWorldGateway worldGateway,GameApplicationService games,MapSelectionService selection,AuditSink audit){this(mapsRoot,repository,importer,worlds,worldGateway,games,selection,audit,new MapSetupEvidenceRepository(mapsRoot.toAbsolutePath().normalize().getParent().resolve("sessions/map-setup.yml")));}
    DefaultMapAdministrationService(Path mapsRoot,MapProfileRepository repository,SafeWorldZipImporter importer,TemporaryWorldManager worlds,MapWorldGateway worldGateway,GameApplicationService games,MapSelectionService selection,AuditSink audit,MapSetupEvidenceRepository setupEvidence){this.mapsRoot=mapsRoot.toAbsolutePath().normalize();this.repository=repository;this.importer=importer;this.worlds=worlds;this.worldGateway=worldGateway;this.games=games;this.selection=selection;this.audit=audit;this.setupEvidence=setupEvidence;}
    @Override public synchronized List<MapProfile> list(){return repository.findAll();}
    @Override public synchronized Optional<String> fixedNextMapId(){return selection.fixedNext().map(MapProfileId::value);}
    @Override public synchronized MapProfile importZip(Path zip,String mapId,String displayName){return importer.importZip(zip,new MapProfileId(mapId),displayName);}
    @Override public synchronized MapProfile setEnabled(String mapId,boolean enabled){MapProfile profile=require(mapId).withEnabled(enabled);repository.save(profile);if(!enabled)selection.clearFixed(profile.mapId());return profile;}
    @Override public synchronized void fixNext(String mapId){selection.fixNext(require(mapId));}
    @Override public synchronized void delete(String mapId){MapProfile profile=require(mapId);if(draft!=null&&draft.profile.mapId().equals(profile.mapId()))throw new IllegalStateException("セットアップ中のマップは削除できません。");if(worlds.hasOwnedWorld(profile.mapId()))throw new IllegalStateException("一時ワールド使用中のマップは削除できません。");Path dir=mapsRoot.resolve(profile.mapId().value()).normalize();try{Path marker=dir.resolve(".orushio-map-owner");if(!dir.getParent().equals(mapsRoot)||!Files.isRegularFile(marker,LinkOption.NOFOLLOW_LINKS)||Files.isSymbolicLink(marker)||!Files.readString(marker).equals(profile.mapId().value()))throw new IllegalStateException("マップ所有情報を確認できません。");SafeFiles.deleteTree(dir);repository.delete(profile.mapId());selection.clearFixed(profile.mapId());}catch(Exception exception){if(exception instanceof IllegalStateException state)throw state;throw new MapIoException("MAP_DELETE","マップを安全に削除できません。",exception);}}
    @Override public synchronized SetupView startSetup(String mapId,UUID administrator,String expectedGameState){if(draft!=null)throw new IllegalStateException("別のセットアップが進行中です。");MapProfile profile=require(mapId);games.startMapSetup(expectedGameState);TemporaryWorldManager.OwnedWorld world=null;try{world=worlds.create(profile,"setup",games.current().sessionId().toString());worldGateway.loadForSetup(world,administrator);draft=new Draft(profile,administrator,world);saveEvidence(draft);return setup();}catch(RuntimeException exception){if(world==null){games.closeMapSetup(games.current().sessionId().toString());throw exception;}try{worldGateway.unload(world);}catch(Exception rollback){exception.addSuppressed(rollback);draft=new Draft(profile,administrator,world);saveEvidenceSafely(draft,exception);worlds.requireRecovery(world,"ロード途中の一時ワールドをアンロードできません。");throw exception;}try{games.closeMapSetup(games.current().sessionId().toString());}catch(Exception rollback){exception.addSuppressed(rollback);draft=new Draft(profile,administrator,world);saveEvidenceSafely(draft,exception);throw exception;}try{setupEvidence.markInactive();worlds.delete(world);draft=null;}catch(Exception rollback){exception.addSuppressed(rollback);draft=new Draft(profile,administrator,world);saveEvidenceSafely(draft,exception);worlds.requireRecovery(world,"ロード途中の一時ワールドを削除できません。");throw exception;}throw exception;}}
    @Override public synchronized SetupView setup(){if(draft==null)return SetupView.inactive();MapProfile current=draft.current();Map<String,Integer> counts=new LinkedHashMap<>();Map<String,List<SetupEntry>> entries=new LinkedHashMap<>();MapFieldCatalog.FIELDS.forEach(field->{if(field.area()){List<Cuboid> values=current.areas().getOrDefault(field.key(),List.of());counts.put(field.key(),values.size());entries.put(field.key(),values.stream().map(value->new SetupEntry(null,value)).toList());}else{List<BlockPoint> values=current.points().getOrDefault(field.key(),List.of());counts.put(field.key(),values.size());entries.put(field.key(),values.stream().map(value->new SetupEntry(value,null)).toList());}});List<MarkerAreaView> markerAreas=current.logicalAreas().stream().filter(area->Set.of("enemyZones","farmRegion","resourceZones","finalRegion").contains(area.fieldKey())).map(area->{List<SpawnMarker> markers=current.spawnMarkers().stream().filter(marker->marker.areaId().equals(area.areaId())).toList();return new MarkerAreaView(area.areaId(),area.label()+" "+(area.index()+1),markers.size(),markers);}).toList();List<MarkerTypeView>types=Arrays.stream(SetupMarkerType.values()).map(type->{List<SetupMarker>markers=current.setupMarkers().stream().filter(marker->marker.markerType()==type).toList();return new MarkerTypeView(type,type.label(),markers.size(),markers);}).toList();return new SetupView(true,draft.profile.mapId().value(),draft.profile.displayName(),draft.administrator.toString(),draft.markerAreaId!=null?"spawnMarker":draft.field==null?"":draft.field,draft.area,current.missingRequirements(),counts,entries,markerAreas,types,draft.revision);}
    @Override public synchronized void selectField(UUID administrator,String field,boolean area){Draft value=authorized(administrator);selectField(value,field,area,null);notify(value,field,"の設定を開始しました。"+(area?"範囲の1地点目を指定してください。":"地点を指定してください。"));}
    @Override public synchronized void selectFieldEntry(UUID administrator,String field,boolean area,int index){Draft value=authorized(administrator);MapFieldCatalog.Field definition=field(field,area);if(definition.area())getAt(value.areas.get(field),index);else getAt(value.points.get(field),index);selectField(value,field,area,index);notify(value,field,"の変更を開始しました。"+(area?"範囲の1地点目を指定してください。":"新しい地点を指定してください。"));}
    private static void selectField(Draft value,String field,boolean area,Integer editIndex){Set<String> allowed=area?Set.of("farmRegion","gateRegions","finalRegion","enemyZones","resourceZones","checkpoints"):Set.of("farmSpawn","combatEntry","normalCoreCandidates","finalCore","finalEntryTrigger","shopPoints");if(!allowed.contains(field))throw new IllegalArgumentException("登録項目が不正です。");value.field=field;value.area=area;value.editIndex=editIndex;value.first=null;value.markerAreaId=null;value.markerId=null;}
    @Override public synchronized void recordClick(UUID administrator,BlockPoint point,boolean secondaryCorner){Draft value=authorized(administrator);if(value.markerAreaId!=null){LogicalArea area=value.current().logicalAreas().stream().filter(a->a.areaId().equals(value.markerAreaId)).findFirst().orElseThrow(()->new IllegalStateException("対象Areaがありません。"));if(!inside(area.region(),point))throw new IllegalArgumentException("Spawn Markerは所属Area内へ登録してください。");if(value.markerId==null){value.markers.add(new SpawnMarker(UUID.randomUUID(),value.markerAreaId,point,true));audit.record(UUID.randomUUID().toString(),"ADMIN","SPAWN_MARKER_ADDED","MAP_SETUP_CLICK");}else{int index=markerIndex(value,value.markerId);value.markers.set(index,value.markers.get(index).withPosition(point));}value.revision++;return;}if(value.field==null)throw new IllegalStateException("管理画面で登録項目を選択してください。");if(!value.area){List<BlockPoint> target=value.points.computeIfAbsent(value.field,key->new ArrayList<>());if(value.editIndex!=null){getAt(target,value.editIndex);target.set(value.editIndex,point);}else{if(MapProfile.REQUIRED_SINGLE_POINTS.contains(value.field))target.clear();target.add(point);}value.editIndex=null;value.revision++;return;}if(!secondaryCorner){value.first=point;return;}if(value.first==null)throw new IllegalStateException("範囲の1点目を先に指定してください。");List<Cuboid> target=value.areas.computeIfAbsent(value.field,key->new ArrayList<>());Cuboid replacement=Cuboid.between(value.first,point);if(value.editIndex!=null){getAt(target,value.editIndex);target.set(value.editIndex,replacement);}else{if(Set.of("farmRegion","finalRegion").contains(value.field))target.clear();target.add(replacement);}value.editIndex=null;value.first=null;value.revision++;}
    @Override public synchronized void removeSetupEntry(UUID administrator,String field,boolean area,int index){Draft value=authorized(administrator);MapFieldCatalog.Field definition=field(field,area);if(index<0)throw new IllegalArgumentException("削除対象が不正です。");if(definition.area()){if(value.markers.stream().anyMatch(marker->marker.areaId().startsWith(field+":")))throw new IllegalStateException("この種類のAreaにあるSpawn Markerを先に削除してください。");removeAt(value.areas.get(definition.key()),index);}else removeAt(value.points.get(definition.key()),index);value.editIndex=null;value.first=null;value.revision++;notify(value,field,"を削除しました。");}
    @Override public synchronized void teleportSetupEntry(UUID administrator,String field,boolean area,int index){Draft value=authorized(administrator);MapFieldCatalog.Field definition=field(field,area);BlockPoint target;if(definition.area()){Cuboid region=getAt(value.areas.get(definition.key()),index);target=new BlockPoint(midpoint(region.minX(),region.maxX()),midpoint(region.minY(),region.maxY()),midpoint(region.minZ(),region.maxZ()),0,0);}else target=getAt(value.points.get(definition.key()),index);worldGateway.teleportSetupAdministrator(value.world,value.administrator,target);}
    @Override public synchronized void selectSpawnMarker(UUID administrator,String areaId,String markerId){Draft value=authorized(administrator);LogicalArea target=value.current().logicalAreas().stream().filter(area->area.areaId().equals(areaId)).findFirst().orElseThrow(()->new IllegalArgumentException("対象Areaがありません。"));value.markerAreaId=areaId;value.markerId=markerId==null||markerId.isBlank()?null:UUID.fromString(markerId);if(value.markerId!=null){SpawnMarker marker=value.markers.get(markerIndex(value,value.markerId));if(!marker.areaId().equals(areaId))throw new IllegalArgumentException("Spawn Markerの所属Areaが一致しません。");}value.field=null;value.area=false;value.editIndex=null;value.first=null;worldGateway.notifySetupAdministrator(value.administrator,"[OPBP] "+target.label()+"のスポーン地点"+(value.markerId==null?"を追加します。地点を指定してください。":"を変更します。新しい地点を指定してください。"));}
    @Override public synchronized void setSpawnMarkerEnabled(UUID administrator,UUID markerId,boolean enabled){Draft value=authorized(administrator);int index=markerIndex(value,markerId);value.markers.set(index,value.markers.get(index).withEnabled(enabled));value.revision++;worldGateway.notifySetupAdministrator(value.administrator,"[OPBP] スポーン地点を"+(enabled?"有効":"無効")+"にしました。");}
    @Override public synchronized void removeSpawnMarker(UUID administrator,UUID markerId){Draft value=authorized(administrator);value.markers.remove(markerIndex(value,markerId));value.revision++;worldGateway.notifySetupAdministrator(value.administrator,"[OPBP] スポーン地点を削除しました。");}
    @Override public synchronized void teleportSpawnMarker(UUID administrator,UUID markerId){Draft value=authorized(administrator);worldGateway.teleportSetupAdministrator(value.world,value.administrator,value.markers.get(markerIndex(value,markerId)).position());}
    @Override public synchronized void issueSetupMarker(UUID administrator,SetupMarkerType markerType){Draft value=authorized(administrator);var token=new MapWorldGateway.SetupMarkerToken(markerType,games.current().sessionId().toString(),value.profile.mapId().value(),administrator);worldGateway.giveSetupMarkerBlock(value.world,administrator,token);worldGateway.notifySetupAdministrator(administrator,"[OPBP] "+markerType.label()+"地点ブロックを渡しました。設置してください。");}
    @Override public synchronized void recordSetupMarker(UUID administrator,MapWorldGateway.SetupMarkerToken token,BlockPoint position){Draft value=authorized(administrator);if(!token.administrator().equals(administrator)||!token.mapId().equals(value.profile.mapId().value())||!token.sessionId().equals(games.current().sessionId().toString()))throw new SecurityException("別のセットアップで発行された設定ブロックは使用できません。");if(value.setupMarkers.stream().anyMatch(marker->sameBlock(marker.position(),position)))throw new IllegalArgumentException("同じ座標には設定地点を重複登録できません。");value.setupMarkers.add(new SetupMarker(UUID.randomUUID(),token.markerType(),position,true));value.revision++;audit.record(UUID.randomUUID().toString(),"ADMIN","SETUP_MARKER_ADDED","MAP_SETUP_BLOCK_PLACE");}
    @Override public synchronized boolean ownsSetupWorld(UUID administrator,String worldName){Draft value=authorized(administrator);return value.world.worldName().equals(worldName);}
    @Override public synchronized void setSetupMarkerEnabled(UUID administrator,UUID markerId,boolean enabled){Draft value=authorized(administrator);int index=setupMarkerIndex(value,markerId);SetupMarker marker=value.setupMarkers.get(index);value.setupMarkers.set(index,marker.withEnabled(enabled));value.revision++;worldGateway.notifySetupAdministrator(administrator,"[OPBP] "+marker.markerType().label()+"地点を"+(enabled?"有効":"無効")+"にしました。");}
    @Override public synchronized void removeSetupMarker(UUID administrator,UUID markerId){Draft value=authorized(administrator);SetupMarker marker=value.setupMarkers.remove(setupMarkerIndex(value,markerId));value.revision++;worldGateway.notifySetupAdministrator(administrator,"[OPBP] "+marker.markerType().label()+"地点を削除しました。");}
    @Override public synchronized void teleportSetupMarker(UUID administrator,UUID markerId){Draft value=authorized(administrator);worldGateway.teleportSetupAdministrator(value.world,administrator,value.setupMarkers.get(setupMarkerIndex(value,markerId)).position());}
    @Override public synchronized MapProfile saveSetup(String expectedSessionId){Draft value=requiredDraft();games.validateMapSetup(expectedSessionId);MapProfile previous=value.profile;MapProfile saved=value.current();repository.save(saved);try{games.closeMapSetup(expectedSessionId);}catch(RuntimeException failure){try{repository.save(previous);}catch(Exception rollback){failure.addSuppressed(rollback);worlds.requireRecovery(value.world,"ゲーム状態とMapProfileの保存を安全にrollbackできません。");}throw failure;}finishAfterSessionClosed(value,"[OPBP] 「"+saved.displayName()+"」のセットアップを保存して終了しました。");return saved;}
    @Override public synchronized void discardSetup(String expectedSessionId){Draft value=requiredDraft();games.validateMapSetup(expectedSessionId);games.closeMapSetup(expectedSessionId);finishAfterSessionClosed(value,"[OPBP] セットアップ変更を破棄して終了しました。");}
    @Override public synchronized void shutdownMapSetupSafely(){if(draft==null||games.current().state()!=com.ryanjei.orushio.pve.domain.GameState.MAP_SETUP)return;try{discardSetup(games.current().sessionId().toString());audit.record(UUID.randomUUID().toString(),"SYSTEM","MAP_SETUP_SHUTDOWN_DISCARD_COMPLETED","PLUGIN_DISABLE");}catch(RuntimeException failure){audit.record(UUID.randomUUID().toString(),"SYSTEM","MAP_SETUP_SHUTDOWN_DISCARD_FAILED","PLUGIN_DISABLE");throw failure;}}
    @Override public synchronized SetupRecoveryView setupRecovery(){MapSetupEvidenceRepository.Evidence evidence;try{evidence=setupEvidence.load().orElse(null);}catch(RuntimeException failure){return new SetupRecoveryView(true,"","","","",false,"Map Setup証跡が不正なため自動復旧できません。");}if(evidence==null)return SetupRecoveryView.none();if(!worlds.startupRecoveryComplete())return new SetupRecoveryView(true,evidence.mapId(),evidence.administrator().toString(),evidence.sessionId(),evidence.worldName(),false,"起動時の一時World確認が完了するまでお待ちください。");try{List<TemporaryWorldManager.OwnedWorld>setupWorlds=worlds.setupWorlds();List<TemporaryWorldManager.OwnedWorld>matches=setupWorlds.stream().filter(world->matches(evidence,world)).toList();boolean idle=games.current().state()==com.ryanjei.orushio.pve.domain.GameState.IDLE;boolean sessionMatches=games.current().state()==com.ryanjei.orushio.pve.domain.GameState.MAP_SETUP&&games.current().sessionId().toString().equals(evidence.sessionId());boolean safe=(matches.size()==1&&setupWorlds.size()==1&&(idle||sessionMatches))||(setupWorlds.isEmpty()&&idle);String warning=safe?"未保存のMap Setup変更を破棄して復旧できます。":"Evidence、Session、一時Worldの所有情報を完全照合できません。";return new SetupRecoveryView(true,evidence.mapId(),evidence.administrator().toString(),evidence.sessionId(),evidence.worldName(),safe,warning);}catch(RuntimeException failure){return new SetupRecoveryView(true,evidence.mapId(),evidence.administrator().toString(),evidence.sessionId(),evidence.worldName(),false,"一時Worldの所有情報を安全に確認できません。");}}
    @Override public synchronized void discardSetupRecovery(){audit.record(UUID.randomUUID().toString(),"ADMIN","MAP_SETUP_RECOVERY_STARTED","MAP_SETUP_RECOVERY");SetupRecoveryView view=setupRecovery();if(!view.recoveryRequired()||!view.safeToRecover()){audit.record(UUID.randomUUID().toString(),"ADMIN","MAP_SETUP_RECOVERY_REJECTED","MAP_SETUP_RECOVERY");throw new SecurityException(view.warning().isBlank()?"安全に復旧できるMap Setupがありません。":view.warning());}try{MapSetupEvidenceRepository.Evidence evidence=setupEvidence.load().orElseThrow();List<TemporaryWorldManager.OwnedWorld>matches=worlds.setupWorlds().stream().filter(world->matches(evidence,world)).toList();if(matches.size()==1){TemporaryWorldManager.OwnedWorld world=matches.getFirst();worldGateway.completeSetup(world,evidence.administrator(),"[OPBP] 前回の未保存マップセットアップを破棄して復旧しました。");if(games.current().state()==com.ryanjei.orushio.pve.domain.GameState.MAP_SETUP)games.closeMapSetup(evidence.sessionId());worlds.delete(world);}setupEvidence.markInactive();worlds.clearRecovery();draft=null;audit.record(UUID.randomUUID().toString(),"ADMIN","MAP_SETUP_RECOVERY_COMPLETED","MAP_SETUP_RECOVERY");}catch(RuntimeException failure){audit.record(UUID.randomUUID().toString(),"ADMIN","MAP_SETUP_RECOVERY_FAILED","MAP_SETUP_RECOVERY");worlds.requireRecovery("Map Setup手動復旧が完了していません。");throw failure;}}
    private static boolean matches(MapSetupEvidenceRepository.Evidence evidence,TemporaryWorldManager.OwnedWorld world){return world.purpose().equals("setup")&&world.worldName().equals(evidence.worldName())&&world.mapId().value().equals(evidence.mapId())&&world.sessionId().equals(evidence.sessionId())&&world.ownershipId().equals(evidence.ownershipId());}
    private void finishAfterSessionClosed(Draft value,String message){try{worldGateway.completeSetup(value.world,value.administrator,message);worlds.delete(value.world);setupEvidence.markInactive();draft=null;}catch(RuntimeException failure){worlds.requireRecovery(value.world,"セットアップ終了後の一時ワールド回収に失敗しました。");throw failure;}}
    private void saveEvidence(Draft value){setupEvidence.save(new MapSetupEvidenceRepository.Evidence(games.current().sessionId().toString(),value.profile.mapId().value(),value.administrator,value.world.worldName(),value.world.ownershipId()));}
    private void saveEvidenceSafely(Draft value,RuntimeException failure){try{saveEvidence(value);}catch(RuntimeException evidenceFailure){failure.addSuppressed(evidenceFailure);worlds.requireRecovery(value.world,"Map Setup証跡を保存できません。");}}
    private Draft authorized(UUID id){Draft value=requiredDraft();if(!value.administrator.equals(id))throw new SecurityException("このセットアップを操作する権限がありません。");return value;}
    private static MapFieldCatalog.Field field(String key,boolean area){return MapFieldCatalog.FIELDS.stream().filter(value->value.key().equals(key)&&value.area()==area).findFirst().orElseThrow(()->new IllegalArgumentException("設定項目が不正です。"));}
    private static <T>T getAt(List<T> values,int index){if(values==null||index<0||index>=values.size())throw new IllegalArgumentException("対象の座標が見つかりません。");return values.get(index);}
    private static <T>void removeAt(List<T> values,int index){getAt(values,index);values.remove(index);}
    private static int midpoint(int minimum,int maximum){return (int)(((long)minimum+(long)maximum)/2L);}private static boolean inside(Cuboid a,BlockPoint p){return p.x()>=a.minX()&&p.x()<=a.maxX()&&p.y()>=a.minY()&&p.y()<=a.maxY()&&p.z()>=a.minZ()&&p.z()<=a.maxZ();}private static boolean sameBlock(BlockPoint a,BlockPoint b){return a.x()==b.x()&&a.y()==b.y()&&a.z()==b.z();}private static int markerIndex(Draft value,UUID id){for(int i=0;i<value.markers.size();i++)if(value.markers.get(i).markerId().equals(id))return i;throw new IllegalArgumentException("Spawn Markerが見つかりません。");}private static int setupMarkerIndex(Draft value,UUID id){for(int i=0;i<value.setupMarkers.size();i++)if(value.setupMarkers.get(i).markerId().equals(id))return i;throw new IllegalArgumentException("設定地点が見つかりません。");}
    private void notify(Draft value,String field,String suffix){worldGateway.notifySetupAdministrator(value.administrator,"[OPBP] "+MapFieldCatalog.label(field)+suffix);}
    private Draft requiredDraft(){if(draft==null)throw new IllegalStateException("セットアップは開始されていません。");return draft;}
    private MapProfile require(String id){return repository.find(new MapProfileId(id)).orElseThrow(()->new IllegalArgumentException("マップが見つかりません。"));}
    private static final class Draft {final MapProfile profile;final UUID administrator;final TemporaryWorldManager.OwnedWorld world;final Map<String,List<BlockPoint>> points=new LinkedHashMap<>();final Map<String,List<Cuboid>> areas=new LinkedHashMap<>();final List<SpawnMarker>markers=new ArrayList<>();final List<SetupMarker>setupMarkers=new ArrayList<>();String field,markerAreaId;UUID markerId;Integer editIndex;boolean area;BlockPoint first;long revision;Draft(MapProfile profile,UUID administrator,TemporaryWorldManager.OwnedWorld world){this.profile=profile;this.administrator=administrator;this.world=world;profile.points().forEach((key,value)->points.put(key,new ArrayList<>(value)));profile.areas().forEach((key,value)->areas.put(key,new ArrayList<>(value)));markers.addAll(profile.spawnMarkers());setupMarkers.addAll(profile.setupMarkers());}MapProfile current(){return profile.withDraft(points,areas,markers,setupMarkers);}}
}
