package com.ryanjei.orushio.pve.map;

import com.ryanjei.orushio.pve.application.GameApplicationService;
import com.ryanjei.orushio.pve.domain.MapProfileId;
import java.nio.file.*;
import java.util.*;

public final class DefaultMapAdministrationService implements MapAdministrationService {
    private final Path mapsRoot; private final MapProfileRepository repository; private final SafeWorldZipImporter importer;
    private final TemporaryWorldManager worlds; private final MapWorldGateway worldGateway; private final GameApplicationService games; private final MapSelectionService selection;
    private Draft draft;
    public DefaultMapAdministrationService(Path mapsRoot,MapProfileRepository repository,SafeWorldZipImporter importer,TemporaryWorldManager worlds,MapWorldGateway worldGateway,GameApplicationService games,MapSelectionService selection){this.mapsRoot=mapsRoot.toAbsolutePath().normalize();this.repository=repository;this.importer=importer;this.worlds=worlds;this.worldGateway=worldGateway;this.games=games;this.selection=selection;}
    @Override public synchronized List<MapProfile> list(){return repository.findAll();}
    @Override public synchronized Optional<String> fixedNextMapId(){return selection.fixedNext().map(MapProfileId::value);}
    @Override public synchronized MapProfile importZip(Path zip,String mapId,String displayName){return importer.importZip(zip,new MapProfileId(mapId),displayName);}
    @Override public synchronized MapProfile setEnabled(String mapId,boolean enabled){MapProfile profile=require(mapId).withEnabled(enabled);repository.save(profile);if(!enabled)selection.clearFixed(profile.mapId());return profile;}
    @Override public synchronized void fixNext(String mapId){selection.fixNext(require(mapId));}
    @Override public synchronized void delete(String mapId){MapProfile profile=require(mapId);if(draft!=null&&draft.profile.mapId().equals(profile.mapId()))throw new IllegalStateException("セットアップ中のマップは削除できません。");if(worlds.hasOwnedWorld(profile.mapId()))throw new IllegalStateException("一時ワールド使用中のマップは削除できません。");Path dir=mapsRoot.resolve(profile.mapId().value()).normalize();try{Path marker=dir.resolve(".orushio-map-owner");if(!dir.getParent().equals(mapsRoot)||!Files.isRegularFile(marker,LinkOption.NOFOLLOW_LINKS)||Files.isSymbolicLink(marker)||!Files.readString(marker).equals(profile.mapId().value()))throw new IllegalStateException("マップ所有情報を確認できません。");SafeFiles.deleteTree(dir);repository.delete(profile.mapId());selection.clearFixed(profile.mapId());}catch(Exception exception){if(exception instanceof IllegalStateException state)throw state;throw new MapIoException("MAP_DELETE","マップを安全に削除できません。",exception);}}
    @Override public synchronized SetupView startSetup(String mapId,UUID administrator,String expectedGameState){if(draft!=null)throw new IllegalStateException("別のセットアップが進行中です。");MapProfile profile=require(mapId);games.startMapSetup(expectedGameState);TemporaryWorldManager.OwnedWorld world=null;try{world=worlds.create(profile,"setup");worldGateway.loadForSetup(world,administrator);draft=new Draft(profile,administrator,world);return setup();}catch(RuntimeException exception){if(world!=null)try{worlds.delete(world);}catch(Exception ignored){}games.closeMapSetup(games.current().sessionId().toString());throw exception;}}
    @Override public synchronized SetupView setup(){if(draft==null)return SetupView.inactive();return new SetupView(true,draft.profile.mapId().value(),draft.administrator.toString(),draft.field==null?"":draft.field,draft.area,draft.current().missingRequirements());}
    @Override public synchronized void selectField(UUID administrator,String field,boolean area){Draft value=authorized(administrator);Set<String> allowed=area?Set.of("farmRegion","gateRegions","finalRegion","enemyZones","resourceZones","checkpoints"):Set.of("farmSpawn","combatEntry","normalCoreCandidates","finalCore","finalEntryTrigger","shopPoints");if(!allowed.contains(field))throw new IllegalArgumentException("登録項目が不正です。");value.field=field;value.area=area;value.first=null;}
    @Override public synchronized void recordClick(UUID administrator,BlockPoint point,boolean secondaryCorner){Draft value=authorized(administrator);if(value.field==null)throw new IllegalStateException("管理画面で登録項目を選択してください。");if(!value.area){value.points.computeIfAbsent(value.field,key->new ArrayList<>()).add(point);return;}if(!secondaryCorner){value.first=point;return;}if(value.first==null)throw new IllegalStateException("範囲の1点目を先に指定してください。");value.areas.computeIfAbsent(value.field,key->new ArrayList<>()).add(Cuboid.between(value.first,point));value.first=null;}
    @Override public synchronized MapProfile saveSetup(String expectedSessionId){Draft value=requiredDraft();MapProfile saved=value.current();repository.save(saved);finish(value,expectedSessionId);return saved;}
    @Override public synchronized void discardSetup(String expectedSessionId){finish(requiredDraft(),expectedSessionId);}
    private void finish(Draft value,String sessionId){worldGateway.unload(value.world);worlds.delete(value.world);games.closeMapSetup(sessionId);draft=null;}
    private Draft authorized(UUID id){Draft value=requiredDraft();if(!value.administrator.equals(id))throw new SecurityException("このセットアップを操作する権限がありません。");return value;}
    private Draft requiredDraft(){if(draft==null)throw new IllegalStateException("セットアップは開始されていません。");return draft;}
    private MapProfile require(String id){return repository.find(new MapProfileId(id)).orElseThrow(()->new IllegalArgumentException("マップが見つかりません。"));}
    private static final class Draft {final MapProfile profile;final UUID administrator;final TemporaryWorldManager.OwnedWorld world;final Map<String,List<BlockPoint>> points=new LinkedHashMap<>();final Map<String,List<Cuboid>> areas=new LinkedHashMap<>();String field;boolean area;BlockPoint first;Draft(MapProfile profile,UUID administrator,TemporaryWorldManager.OwnedWorld world){this.profile=profile;this.administrator=administrator;this.world=world;profile.points().forEach((key,value)->points.put(key,new ArrayList<>(value)));profile.areas().forEach((key,value)->areas.put(key,new ArrayList<>(value)));}MapProfile current(){return profile.withDraft(points,areas);}}
}
