package com.ryanjei.orushio.pve.map;

import com.ryanjei.orushio.pve.domain.MapProfileId;
import java.io.*;
import java.nio.file.*;
import java.time.Instant;
import java.util.*;
import java.util.zip.*;

public final class SafeWorldZipImporter {
    public record Limits(long maxZipBytes,long maxExpandedBytes,int maxFiles){public static Limits defaults(){return new Limits(512L*1024*1024,2L*1024*1024*1024,20_000);}}
    private final Path mapsRoot; private final Limits limits;
    public SafeWorldZipImporter(Path mapsRoot,Limits limits){this.mapsRoot=mapsRoot.toAbsolutePath().normalize();this.limits=limits;}
    public MapProfile importZip(Path zip,MapProfileId id,String displayName){Path map=mapsRoot.resolve(id.value()).normalize(),staging=mapsRoot.resolve(".import-"+UUID.randomUUID()).normalize();if(!map.getParent().equals(mapsRoot)||Files.exists(map))throw new MapIoException("MAP_EXISTS","同じmapIdがすでに存在します。");try{if(!Files.isRegularFile(zip)||Files.size(zip)==0||Files.size(zip)>limits.maxZipBytes())throw new MapIoException("ZIP_SIZE","ZIPサイズが許容範囲外です。");rejectSymlinkEntries(zip);Files.createDirectories(staging);extract(zip,staging);Path world=findWorld(staging);Files.createDirectories(map);SafeFiles.copyTree(world,map.resolve("template"));Files.writeString(map.resolve(".orushio-map-owner"),id.value(),StandardOpenOption.CREATE_NEW);MapProfile profile=new MapProfile(id,displayName,false,"template",Map.of(),Map.of(),Instant.now());new YamlMapProfileRepository(mapsRoot).save(profile);return profile;}catch(MapIoException error){safeDelete(map);throw error;}catch(Exception error){safeDelete(map);throw new MapIoException("INVALID_ZIP","ワールドZIPを登録できません。",error);}finally{safeDelete(staging);}}
    private void extract(Path zip,Path staging)throws IOException{long total=0;int files=0;boolean any=false;try(ZipInputStream input=new ZipInputStream(Files.newInputStream(zip))){for(ZipEntry entry;(entry=input.getNextEntry())!=null;){any=true;String name=entry.getName().replace('\\','/');if(name.isBlank()||name.startsWith("/")||name.matches("^[A-Za-z]:.*"))throw new MapIoException("ZIP_PATH","絶対パスを含むZIPは利用できません。");Path output=staging.resolve(name).normalize();if(!output.startsWith(staging))throw new MapIoException("ZIP_SLIP","展開先外のパスを含むZIPは利用できません。");if(entry.isDirectory()){Files.createDirectories(output);continue;}if(++files>limits.maxFiles())throw new MapIoException("ZIP_FILE_LIMIT","ZIPのファイル数が上限を超えています。");Files.createDirectories(output.getParent());try(OutputStream out=Files.newOutputStream(output,StandardOpenOption.CREATE_NEW)){byte[] buffer=new byte[8192];for(int read;(read=input.read(buffer))>=0;){total+=read;if(total>limits.maxExpandedBytes())throw new MapIoException("ZIP_EXPANDED_LIMIT","ZIPの展開サイズが上限を超えています。");out.write(buffer,0,read);}}}}catch(ZipException error){throw new MapIoException("INVALID_ZIP","ZIPが破損しています。",error);}if(!any||files==0)throw new MapIoException("EMPTY_ZIP","空のZIPは登録できません。");}
    private static Path findWorld(Path staging)throws IOException{if(Files.isRegularFile(staging.resolve("level.dat")))return staging;try(var directories=Files.list(staging)){List<Path> candidates=directories.filter(Files::isDirectory).filter(path->Files.isRegularFile(path.resolve("level.dat"))).toList();if(candidates.size()==1)return candidates.getFirst();}throw new MapIoException("WORLD_NOT_FOUND","Java版ワールドのlevel.datを直下または1階層下に確認できません。");}
    private static void rejectSymlinkEntries(Path zip)throws IOException{try(RandomAccessFile file=new RandomAccessFile(zip.toFile(),"r")){long start=Math.max(0,file.length()-65_557),eocd=-1;for(long position=file.length()-22;position>=start;position--){file.seek(position);if(readIntLE(file)==0x06054b50){eocd=position;break;}}if(eocd<0)throw new MapIoException("INVALID_ZIP","ZIP中央ディレクトリを確認できません。");file.seek(eocd+10);int entries=readShortLE(file);file.seek(eocd+16);long centralOffset=Integer.toUnsignedLong(readIntLE(file));file.seek(centralOffset);for(int index=0;index<entries;index++){if(readIntLE(file)!=0x02014b50)throw new MapIoException("INVALID_ZIP","ZIP中央ディレクトリが不正です。");file.skipBytes(24);int nameLength=readShortLE(file),extraLength=readShortLE(file),commentLength=readShortLE(file);file.skipBytes(4);long external=Integer.toUnsignedLong(readIntLE(file));file.skipBytes(4);int unixMode=(int)(external>>>16);if((unixMode&0xF000)==0xA000)throw new MapIoException("ZIP_SYMLINK","シンボリックリンクを含むZIPは利用できません。");file.skipBytes(nameLength+extraLength+commentLength);}}}
    private static int readShortLE(RandomAccessFile file)throws IOException{return file.readUnsignedByte()|(file.readUnsignedByte()<<8);}private static int readIntLE(RandomAccessFile file)throws IOException{return readShortLE(file)|(readShortLE(file)<<16);}
    private static void safeDelete(Path path){try{if(Files.exists(path))SafeFiles.deleteTree(path);}catch(IOException ignored){}}
}
