package com.ryanjei.orushio.pve.map;
import com.ryanjei.orushio.pve.domain.MapProfileId;import com.ryanjei.orushio.pve.persistence.*;import java.nio.file.*;import java.time.Instant;import java.util.*;import java.util.stream.Collectors;
public final class YamlMapProfileRepository implements MapProfileRepository{
 private static final Set<String>RETIRED_SETUP_MARKER_TYPES=Set.of("FARM_RESPAWN","GAME_START","FINAL_AREA_ENTRY","FINAL_AREA_DESTINATION","CHECKPOINT");
 private static final System.Logger LOGGER=System.getLogger(YamlMapProfileRepository.class.getName());
 private final Path root;private volatile List<String>loadIssues=List.of();public YamlMapProfileRepository(Path root){this.root=root.toAbsolutePath().normalize();}
 public List<MapProfile> findAll(){if(!Files.isDirectory(root)){loadIssues=List.of();return List.of();}List<MapProfile>values=new ArrayList<>();List<String>issues=new ArrayList<>();try(var s=Files.list(root)){for(Path directory:s.filter(Files::isDirectory).sorted().toList()){try{load(directory.resolve("profile.yml")).ifPresent(values::add);}catch(RuntimeException failure){String message=directory.getFileName()+" のMapProfileを読み込めません: "+rootMessage(failure);issues.add(message);LOGGER.log(System.Logger.Level.WARNING,message,failure);}}}catch(Exception e){throw new RepositoryException("マップ一覧を読み込めません。",e);}loadIssues=List.copyOf(issues);values.sort(Comparator.comparing(p->p.mapId().value()));return List.copyOf(values);}
 public List<String>loadIssues(){return loadIssues;}
 public Optional<MapProfile> find(MapProfileId id){return load(path(id).resolve("profile.yml"));}
 public void save(MapProfile p){Map<String,String>v=new LinkedHashMap<>();v.put("schemaVersion","1");v.put("mapId",p.mapId().value());v.put("displayName",p.displayName());v.put("enabled",Boolean.toString(p.enabled()));v.put("templateDirectory",p.templateDirectory());v.put("createdAt",p.createdAt().toString());p.points().forEach((k,l)->{if(!MapProfile.RETIRED_POINT_FIELDS.contains(k))v.put("points."+k,encodePoints(l));});p.areas().forEach((k,l)->{if(!MapProfile.RETIRED_AREA_FIELDS.contains(k))v.put("areas."+k,encodeAreas(l));});v.put("spawnMarkers",encodeMarkers(p.spawnMarkers()));v.put("setupMarkers",encodeSetupMarkers(p.setupMarkers()));new AtomicYamlStore(path(p.mapId()).resolve("profile.yml")).write(v);}
 public void delete(MapProfileId id){try{Files.deleteIfExists(path(id).resolve("profile.yml"));}catch(Exception e){throw new RepositoryException("MapProfileを削除できません。",e);}}
 private Optional<MapProfile> load(Path f){return new AtomicYamlStore(f).read().map(v->{if(!"1".equals(v.get("schemaVersion")))throw new RepositoryException("未対応のMapProfile schemaVersionです。");Map<String,List<BlockPoint>>p=new LinkedHashMap<>();Map<String,List<Cuboid>>a=new LinkedHashMap<>();v.forEach((k,x)->{if(k.startsWith("points."))p.put(k.substring(7),decodePoints(x));if(k.startsWith("areas."))a.put(k.substring(6),decodeAreas(x));});List<SetupMarker>setup=new ArrayList<>(decodeSetupMarkers(v.getOrDefault("setupMarkers","")));boolean requestedEnabled=strictBoolean(v.get("enabled"));MapProfile candidate=new MapProfile(new MapProfileId(v.get("mapId")),v.get("displayName"),false,v.get("templateDirectory"),p,a,Instant.parse(v.get("createdAt")),decodeMarkers(v.getOrDefault("spawnMarkers","")),setup);return requestedEnabled&&candidate.setupComplete()?candidate.withEnabled(true):candidate;});}
 private Path path(MapProfileId id){Path p=root.resolve(id.value()).normalize();if(!p.getParent().equals(root))throw new RepositoryException("mapIdの保存先が不正です。");return p;}
 private static String point(BlockPoint p){return p.x()+","+p.y()+","+p.z()+","+p.yaw()+","+p.pitch();}private static BlockPoint point(String v){String[]p=v.split(",");if(p.length!=5)throw new RepositoryException("地点データが不正です。");return new BlockPoint(Integer.parseInt(p[0]),Integer.parseInt(p[1]),Integer.parseInt(p[2]),Float.parseFloat(p[3]),Float.parseFloat(p[4]));}
 private static String encodePoints(List<BlockPoint>l){return l.stream().map(YamlMapProfileRepository::point).collect(Collectors.joining(";"));}private static List<BlockPoint>decodePoints(String s){return s.isBlank()?List.of():Arrays.stream(s.split(";")).map(YamlMapProfileRepository::point).toList();}
 private static String encodeAreas(List<Cuboid>l){return l.stream().map(a->a.minX()+","+a.minY()+","+a.minZ()+","+a.maxX()+","+a.maxY()+","+a.maxZ()).collect(Collectors.joining(";"));}private static List<Cuboid>decodeAreas(String s){if(s.isBlank())return List.of();return Arrays.stream(s.split(";")).map(v->{String[]a=v.split(",");if(a.length!=6)throw new RepositoryException("範囲データが不正です。");return new Cuboid(Integer.parseInt(a[0]),Integer.parseInt(a[1]),Integer.parseInt(a[2]),Integer.parseInt(a[3]),Integer.parseInt(a[4]),Integer.parseInt(a[5]));}).toList();}
 private static String encodeMarkers(List<SpawnMarker>l){return l.stream().map(m->m.markerId()+","+m.areaId()+","+point(m.position())+","+m.enabled()).collect(Collectors.joining(";"));}private static List<SpawnMarker>decodeMarkers(String s){if(s.isBlank())return List.of();return Arrays.stream(s.split(";")).map(v->{String[]p=v.split(",");if(p.length!=8)throw new RepositoryException("Spawn Markerデータが不正です。");return new SpawnMarker(UUID.fromString(p[0]),p[1],new BlockPoint(Integer.parseInt(p[2]),Integer.parseInt(p[3]),Integer.parseInt(p[4]),Float.parseFloat(p[5]),Float.parseFloat(p[6])),strictBoolean(p[7]));}).toList();}
 private static String encodeSetupMarkers(List<SetupMarker>l){return l.stream().map(m->m.markerId()+","+m.markerType()+","+point(m.position())+","+m.enabled()).collect(Collectors.joining(";"));}private static List<SetupMarker>decodeSetupMarkers(String s){if(s.isBlank())return List.of();List<SetupMarker>result=new ArrayList<>();for(String value:s.split(";")){String[]p=value.split(",");if(p.length!=8)throw new RepositoryException("設定Markerデータが不正です。");if(RETIRED_SETUP_MARKER_TYPES.contains(p[1]))continue;SetupMarkerType type;try{type=SetupMarkerType.valueOf(p[1]);}catch(IllegalArgumentException failure){throw new RepositoryException("未知のSetup Marker種別です: "+p[1],failure);}result.add(new SetupMarker(UUID.fromString(p[0]),type,new BlockPoint(Integer.parseInt(p[2]),Integer.parseInt(p[3]),Integer.parseInt(p[4]),Float.parseFloat(p[5]),Float.parseFloat(p[6])),strictBoolean(p[7])));}return List.copyOf(result);}
 private static String rootMessage(Throwable failure){Throwable current=failure;while(current.getCause()!=null)current=current.getCause();return current.getMessage()==null?current.getClass().getSimpleName():current.getMessage();}
 private static boolean strictBoolean(String v){if(!"true".equals(v)&&!"false".equals(v))throw new RepositoryException("真偽値が不正です。");return Boolean.parseBoolean(v);}
}
