package com.ryanjei.orushio.pve.map;
import com.ryanjei.orushio.pve.domain.MapProfileId;import com.ryanjei.orushio.pve.persistence.*;import java.nio.file.*;import java.time.Instant;import java.util.*;import java.util.stream.Collectors;
public final class YamlMapProfileRepository implements MapProfileRepository{
 private final Path root;public YamlMapProfileRepository(Path root){this.root=root.toAbsolutePath().normalize();}
 public List<MapProfile> findAll(){if(!Files.isDirectory(root))return List.of();try(var s=Files.list(root)){return s.filter(Files::isDirectory).map(p->load(p.resolve("profile.yml"))).flatMap(Optional::stream).sorted(Comparator.comparing(p->p.mapId().value())).toList();}catch(Exception e){throw new RepositoryException("マップ一覧を読み込めません。",e);}}
 public Optional<MapProfile> find(MapProfileId id){return load(path(id).resolve("profile.yml"));}
 public void save(MapProfile p){Map<String,String>v=new LinkedHashMap<>();v.put("schemaVersion","1");v.put("mapId",p.mapId().value());v.put("displayName",p.displayName());v.put("enabled",Boolean.toString(p.enabled()));v.put("templateDirectory",p.templateDirectory());v.put("createdAt",p.createdAt().toString());p.points().forEach((k,l)->v.put("points."+k,encodePoints(l)));p.areas().forEach((k,l)->v.put("areas."+k,encodeAreas(l)));v.put("spawnMarkers",encodeMarkers(p.spawnMarkers()));new AtomicYamlStore(path(p.mapId()).resolve("profile.yml")).write(v);}
 public void delete(MapProfileId id){try{Files.deleteIfExists(path(id).resolve("profile.yml"));}catch(Exception e){throw new RepositoryException("MapProfileを削除できません。",e);}}
 private Optional<MapProfile> load(Path f){return new AtomicYamlStore(f).read().map(v->{Map<String,List<BlockPoint>>p=new LinkedHashMap<>();Map<String,List<Cuboid>>a=new LinkedHashMap<>();v.forEach((k,x)->{if(k.startsWith("points."))p.put(k.substring(7),decodePoints(x));if(k.startsWith("areas."))a.put(k.substring(6),decodeAreas(x));});return new MapProfile(new MapProfileId(v.get("mapId")),v.get("displayName"),strictBoolean(v.get("enabled")),v.get("templateDirectory"),p,a,Instant.parse(v.get("createdAt")),decodeMarkers(v.getOrDefault("spawnMarkers","")));});}
 private Path path(MapProfileId id){Path p=root.resolve(id.value()).normalize();if(!p.getParent().equals(root))throw new RepositoryException("mapIdの保存先が不正です。");return p;}
 private static String point(BlockPoint p){return p.x()+","+p.y()+","+p.z()+","+p.yaw()+","+p.pitch();}private static BlockPoint point(String v){String[]p=v.split(",");if(p.length!=5)throw new RepositoryException("地点データが不正です。");return new BlockPoint(Integer.parseInt(p[0]),Integer.parseInt(p[1]),Integer.parseInt(p[2]),Float.parseFloat(p[3]),Float.parseFloat(p[4]));}
 private static String encodePoints(List<BlockPoint>l){return l.stream().map(YamlMapProfileRepository::point).collect(Collectors.joining(";"));}private static List<BlockPoint>decodePoints(String s){return s.isBlank()?List.of():Arrays.stream(s.split(";")).map(YamlMapProfileRepository::point).toList();}
 private static String encodeAreas(List<Cuboid>l){return l.stream().map(a->a.minX()+","+a.minY()+","+a.minZ()+","+a.maxX()+","+a.maxY()+","+a.maxZ()).collect(Collectors.joining(";"));}private static List<Cuboid>decodeAreas(String s){if(s.isBlank())return List.of();return Arrays.stream(s.split(";")).map(v->{String[]a=v.split(",");if(a.length!=6)throw new RepositoryException("範囲データが不正です。");return new Cuboid(Integer.parseInt(a[0]),Integer.parseInt(a[1]),Integer.parseInt(a[2]),Integer.parseInt(a[3]),Integer.parseInt(a[4]),Integer.parseInt(a[5]));}).toList();}
 private static String encodeMarkers(List<SpawnMarker>l){return l.stream().map(m->m.markerId()+","+m.areaId()+","+point(m.position())+","+m.enabled()).collect(Collectors.joining(";"));}private static List<SpawnMarker>decodeMarkers(String s){if(s.isBlank())return List.of();return Arrays.stream(s.split(";")).map(v->{String[]p=v.split(",");if(p.length!=8)throw new RepositoryException("Spawn Markerデータが不正です。");return new SpawnMarker(UUID.fromString(p[0]),p[1],new BlockPoint(Integer.parseInt(p[2]),Integer.parseInt(p[3]),Integer.parseInt(p[4]),Float.parseFloat(p[5]),Float.parseFloat(p[6])),strictBoolean(p[7]));}).toList();}
 private static boolean strictBoolean(String v){if(!"true".equals(v)&&!"false".equals(v))throw new RepositoryException("真偽値が不正です。");return Boolean.parseBoolean(v);}
}
