package com.ryanjei.orushio.pve.progression;
import com.ryanjei.orushio.pve.application.GameLifecycleStep;import com.ryanjei.orushio.pve.domain.*;import com.ryanjei.orushio.pve.logging.AuditSink;import com.ryanjei.orushio.pve.map.*;import java.util.*;
public final class FinalAreaProgressionStep implements GameLifecycleStep{
 public enum ContactResult{IGNORED,ENTERED,WARPED,SAVE_POINT_ACTIVATED}
 private final GameRuntimeContextResolver runtimes;private final FinalAreaGateway gateway;private final AuditSink audit;private RuntimeState runtime;
 public FinalAreaProgressionStep(GameRuntimeContextResolver runtimes,FinalAreaGateway gateway,AuditSink audit){this.runtimes=Objects.requireNonNull(runtimes);this.gateway=Objects.requireNonNull(gateway);this.audit=Objects.requireNonNull(audit);}
 public synchronized void prepare(GameSession session){if(runtime!=null){require(session.sessionId());return;}GameRuntimeContext context=runtimes.resolve(session.sessionId()).orElseThrow(()->new IllegalStateException("進行用Runtimeがありません。"));MapProfile profile=context.map().profile();BlockPoint initial=profile.requireSingleEnabledMarker(SetupMarkerType.INITIAL_RESPAWN);Cuboid finalRegion=profile.areas().getOrDefault("finalRegion",List.of()).stream().findFirst().orElseThrow(()->new IllegalArgumentException("最終エリア範囲がありません。"));runtime=new RuntimeState(session.sessionId(),context.worldName(),session.requiredNormalCores(),initial,finalRegion,markers(profile,SetupMarkerType.WARP),markers(profile,SetupMarkerType.SAVE_POINT),session.participants());}
 public synchronized void rollbackPreparation(GameSession session){clear(session);}public synchronized void cleanup(GameSession session){clear(session);}public int cleanupOrder(){return 9;}
 public synchronized void normalCoreDestroyed(UUID sessionId,int destroyed){RuntimeState value=require(sessionId);if(destroyed<value.destroyedNormal||destroyed>value.required)throw new IllegalStateException("通常Core進行が不正です。");value.destroyedNormal=destroyed;if(destroyed==value.required&&!value.unlocked){value.unlocked=true;audit("FINAL_AREA_UNLOCKED");}}
 public synchronized void finalCoreDestroyed(UUID sessionId){RuntimeState value=require(sessionId);if(value.finalCoreDestroyed)return;value.finalCoreDestroyed=true;audit("FINAL_CORE_DESTROYED");}
 public synchronized ContactResult contact(GameSession session,UUID playerId,String world,int x,int y,int z){if(runtime==null||session.state()!=GameState.ACTIVE||!session.isParticipant(playerId)||!runtime.sessionId.equals(session.sessionId())||!runtime.world.equals(world))return ContactResult.IGNORED;BlockKey block=new BlockKey(x,y,z);BlockKey previous=runtime.lastBlocks.put(playerId,block);if(block.equals(previous))return ContactResult.IGNORED;boolean enteredNow=runtime.unlocked&&contains(runtime.finalRegion,block)&&runtime.entered.add(playerId);if(enteredNow)audit("FINAL_AREA_ENTERED");BlockPoint save=runtime.saveMarkers.get(block);if(save!=null){BlockPoint old=runtime.playerSaves.put(playerId,save);if(!sameBlock(old,save)){runtime.activated.add(playerId);audit("SAVE_POINT_ACTIVATED");return ContactResult.SAVE_POINT_ACTIVATED;}}if(runtime.warpMarkers.containsKey(block)){gateway.teleport(runtime.sessionId,runtime.world,playerId,runtime.playerSaves.getOrDefault(playerId,runtime.initial));return ContactResult.WARPED;}return enteredNow?ContactResult.ENTERED:ContactResult.IGNORED;}
 public synchronized boolean participantRespawnedHandled(GameSession session,UUID playerId){if(runtime==null||session.state()!=GameState.ACTIVE||!session.isParticipant(playerId)||!runtime.sessionId.equals(session.sessionId()))return false;gateway.teleport(runtime.sessionId,runtime.world,playerId,runtime.playerSaves.getOrDefault(playerId,runtime.initial));return true;}
 public synchronized FinalAreaProgressionView progressionView(){if(runtime==null)return FinalAreaProgressionView.idle();List<FinalAreaProgressionView.ParticipantProgress>players=runtime.participants.stream().map(p->new FinalAreaProgressionView.ParticipantProgress(p.playerUuid(),p.lastKnownName(),runtime.entered.contains(p.playerUuid()),runtime.activated.contains(p.playerUuid()))).toList();return new FinalAreaProgressionView(runtime.destroyedNormal,runtime.required,runtime.unlocked,runtime.finalCoreDestroyed,players);}
 public synchronized boolean isUnlocked(UUID id){return runtime!=null&&runtime.sessionId.equals(id)&&runtime.unlocked;}
 private static Map<BlockKey,BlockPoint>markers(MapProfile profile,SetupMarkerType type){Map<BlockKey,BlockPoint>result=new LinkedHashMap<>();for(SetupMarker marker:profile.enabledSetupMarkers(type))if(result.put(BlockKey.of(marker.position()),marker.position())!=null)throw new IllegalArgumentException("同じBlockに"+type.label()+"が重複しています。");return Map.copyOf(result);}
 private void clear(GameSession session){if(runtime==null)return;require(session.sessionId());runtime=null;}private RuntimeState require(UUID id){if(runtime==null||!runtime.sessionId.equals(id))throw new IllegalStateException("別Sessionの進行状態は操作できません。");return runtime;}private void audit(String code){audit.record(UUID.randomUUID().toString(),"SYSTEM",code,"MAP_PROGRESSION");}
 private static boolean sameBlock(BlockPoint a,BlockPoint b){return a!=null&&a.x()==b.x()&&a.y()==b.y()&&a.z()==b.z();}private static boolean contains(Cuboid a,BlockKey p){return p.x>=a.minX()&&p.x<=a.maxX()&&p.y>=a.minY()&&p.y<=a.maxY()&&p.z>=a.minZ()&&p.z<=a.maxZ();}private record BlockKey(int x,int y,int z){static BlockKey of(BlockPoint p){return new BlockKey(p.x(),p.y(),p.z());}}
 private static final class RuntimeState{final UUID sessionId;final String world;final int required;final BlockPoint initial;final Cuboid finalRegion;final Map<BlockKey,BlockPoint>warpMarkers,saveMarkers;final List<Participant>participants;final Set<UUID>entered=new HashSet<>(),activated=new HashSet<>();final Map<UUID,BlockPoint>playerSaves=new HashMap<>();final Map<UUID,BlockKey>lastBlocks=new HashMap<>();int destroyedNormal;boolean unlocked,finalCoreDestroyed;RuntimeState(UUID id,String world,int required,BlockPoint initial,Cuboid finalRegion,Map<BlockKey,BlockPoint>warps,Map<BlockKey,BlockPoint>saves,List<Participant>participants){sessionId=id;this.world=world;this.required=required;this.initial=initial;this.finalRegion=finalRegion;warpMarkers=warps;saveMarkers=saves;this.participants=List.copyOf(participants);for(Participant participant:participants)playerSaves.put(participant.playerUuid(),initial);}}
}
