package com.ryanjei.orushio.pve.progression;

import com.ryanjei.orushio.pve.application.GameLifecycleStep;
import com.ryanjei.orushio.pve.domain.*;
import com.ryanjei.orushio.pve.logging.AuditSink;
import com.ryanjei.orushio.pve.map.*;
import java.util.*;

public final class FinalAreaProgressionStep implements GameLifecycleStep{
 public enum ContactResult{IGNORED,LOCKED,ENTERED,CHECKPOINT_ACTIVATED}
 private final GameRuntimeContextResolver runtimes;private final FinalAreaGateway gateway;private final AuditSink audit;private RuntimeState runtime;
 public FinalAreaProgressionStep(GameRuntimeContextResolver runtimes,FinalAreaGateway gateway,AuditSink audit){this.runtimes=Objects.requireNonNull(runtimes);this.gateway=Objects.requireNonNull(gateway);this.audit=Objects.requireNonNull(audit);}
 public synchronized void prepare(GameSession session){if(runtime!=null){require(session);return;}GameRuntimeContext context=runtimes.resolve(session.sessionId()).orElseThrow(()->new IllegalStateException("最終エリア用Runtimeがありません。"));MapProfile profile=context.map().profile();BlockPoint entry=profile.requireSingleEnabledMarker(SetupMarkerType.FINAL_AREA_ENTRY);BlockPoint destination=profile.requireSingleEnabledMarker(SetupMarkerType.FINAL_AREA_DESTINATION);Cuboid finalRegion=profile.areas().getOrDefault("finalRegion",List.of()).stream().findFirst().orElseThrow(()->new IllegalArgumentException("最終エリア範囲がありません。"));if(!contains(finalRegion,destination))throw new IllegalArgumentException("最終エリア転送先が最終エリア範囲外です。");Map<BlockKey,BlockPoint> checkpoints=new LinkedHashMap<>();for(SetupMarker marker:profile.enabledSetupMarkers(SetupMarkerType.CHECKPOINT)){if(!contains(finalRegion,marker.position()))throw new IllegalArgumentException("Checkpointが最終エリア範囲外です。");BlockPoint previous=checkpoints.put(BlockKey.of(marker.position()),marker.position());if(previous!=null)throw new IllegalArgumentException("同じBlockにCheckpointが重複しています。");}runtime=new RuntimeState(session.sessionId(),context.worldName(),session.requiredNormalCores(),entry,destination,checkpoints,session.participants());}
 public synchronized void rollbackPreparation(GameSession session){clear(session);}public synchronized void cleanup(GameSession session){clear(session);}public int cleanupOrder(){return 9;}
 public synchronized void normalCoreDestroyed(UUID sessionId,int destroyed){RuntimeState value=require(sessionId);if(destroyed<value.destroyedNormal||destroyed>value.required)throw new IllegalStateException("通常Core進行が不正です。");value.destroyedNormal=destroyed;if(destroyed==value.required&&!value.unlocked){value.unlocked=true;audit("FINAL_AREA_UNLOCKED");}}
 public synchronized void finalCoreDestroyed(UUID sessionId){RuntimeState value=require(sessionId);if(value.finalCoreDestroyed)return;value.finalCoreDestroyed=true;audit("FINAL_CORE_DESTROYED");}
 public synchronized ContactResult contact(GameSession session,UUID playerId,String world,int x,int y,int z){if(runtime==null||session.state()!=GameState.ACTIVE||!session.isParticipant(playerId)||!runtime.sessionId.equals(session.sessionId())||!runtime.world.equals(world))return ContactResult.IGNORED;BlockKey block=new BlockKey(x,y,z);BlockKey previous=runtime.lastBlocks.put(playerId,block);if(block.equals(previous))return ContactResult.IGNORED;if(block.equals(BlockKey.of(runtime.entry))){if(!runtime.unlocked){gateway.notifyLocked(runtime.sessionId,runtime.world,playerId);return ContactResult.LOCKED;}if(runtime.entered.add(playerId)){gateway.teleport(runtime.sessionId,runtime.world,playerId,runtime.destination);audit("FINAL_AREA_ENTERED");return ContactResult.ENTERED;}return ContactResult.IGNORED;}BlockPoint checkpoint=runtime.checkpoints.get(block);if(checkpoint!=null&&runtime.entered.contains(playerId)){BlockPoint old=runtime.playerCheckpoints.put(playerId,checkpoint);if(!sameBlock(old,checkpoint)){audit("CHECKPOINT_ACTIVATED");return ContactResult.CHECKPOINT_ACTIVATED;}}return ContactResult.IGNORED;}
 public synchronized boolean participantRespawnedHandled(GameSession session,UUID playerId){if(runtime==null||session.state()!=GameState.ACTIVE||!session.isParticipant(playerId)||!runtime.sessionId.equals(session.sessionId()))return false;BlockPoint checkpoint=runtime.playerCheckpoints.get(playerId);if(checkpoint==null)return false;gateway.teleport(runtime.sessionId,runtime.world,playerId,checkpoint);return true;}
 public synchronized FinalAreaProgressionView progressionView(){if(runtime==null)return FinalAreaProgressionView.idle();List<FinalAreaProgressionView.ParticipantProgress>players=runtime.participants.stream().map(p->new FinalAreaProgressionView.ParticipantProgress(p.playerUuid(),p.lastKnownName(),runtime.entered.contains(p.playerUuid()),runtime.playerCheckpoints.containsKey(p.playerUuid()))).toList();return new FinalAreaProgressionView(runtime.destroyedNormal,runtime.required,runtime.unlocked,runtime.finalCoreDestroyed,players);}
 private void clear(GameSession session){if(runtime==null)return;require(session.sessionId());runtime=null;}
 private RuntimeState require(UUID sessionId){if(runtime==null||!runtime.sessionId.equals(sessionId))throw new IllegalStateException("別Sessionの最終エリア状態は操作できません。");return runtime;}private void require(GameSession session){require(session.sessionId());}
 private void audit(String code){audit.record(UUID.randomUUID().toString(),"SYSTEM",code,"FINAL_AREA_PROGRESSION");}
 private static boolean sameBlock(BlockPoint a,BlockPoint b){return a!=null&&a.x()==b.x()&&a.y()==b.y()&&a.z()==b.z();}
 private static boolean contains(Cuboid area,BlockPoint point){return point.x()>=area.minX()&&point.x()<=area.maxX()&&point.y()>=area.minY()&&point.y()<=area.maxY()&&point.z()>=area.minZ()&&point.z()<=area.maxZ();}
 private record BlockKey(int x,int y,int z){static BlockKey of(BlockPoint p){return new BlockKey(p.x(),p.y(),p.z());}}
 private static final class RuntimeState{final UUID sessionId;final String world;final int required;final BlockPoint entry,destination;final Map<BlockKey,BlockPoint>checkpoints;final List<Participant>participants;final Set<UUID>entered=new HashSet<>();final Map<UUID,BlockPoint>playerCheckpoints=new HashMap<>();final Map<UUID,BlockKey>lastBlocks=new HashMap<>();int destroyedNormal;boolean unlocked,finalCoreDestroyed;RuntimeState(UUID sessionId,String world,int required,BlockPoint entry,BlockPoint destination,Map<BlockKey,BlockPoint>checkpoints,List<Participant>participants){this.sessionId=sessionId;this.world=world;this.required=required;this.entry=entry;this.destination=destination;this.checkpoints=Map.copyOf(checkpoints);this.participants=List.copyOf(participants);}}
}
